### DISCUSSION TITLE
admission webhook "admission-webhook.cstor.openebs.io" denied the request: invalid cspc specification: invalid pool spec: block device has file system {vfat}

### DISCUSSION THREAD

**Discussion by minhhungit** [openebs/openebs#3581] [Q&A] [answered]
Hi team, when create CStorPoolCluster I got this error, what should I do please:
```
Error from server (BadRequest): error when creating "1.cspc.yaml": admission webhook "admission-webhook.cstor.openebs.io" denied the request: invalid cspc specification: invalid pool spec: block device has file system {vfat}
```

This is my yaml file:
```yaml
# https://openebs.io/docs/user-guides/cstor
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "kworker01"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-65f8b3212fd52fbcc07e91357513cee7"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "kworker02"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-2272b1f0f44ec38bc442fef85b44654"
     poolConfig:
       dataRaidGroupType: "stripe"

#   - nodeSelector:
#       kubernetes.io/hostname: "kworker02"
#     dataRaidGroups:
#       - blockDevices:
#           - blockDeviceName: "blockdevice-68fe3e5ca57fbd2727ebc7aeafaade69"
#     poolConfig:
#       dataRaidGroupType: "stripe"

```
```
$ kubectl get bd -n openebs
NAME                                           NODENAME    SIZE          CLAIMSTATE   STATUS   AGE
blockdevice-2272b1f0f44ec38bc442fef85b44654d   kworker02   16069427200   Unclaimed    Active   14m
blockdevice-65f8b3212fd52fbcc07e91357513cee7   kworker01   15731785728   Unclaimed    Active   17m
blockdevice-68fe3e5ca57fbd2727ebc7aeafaade69   kworker02   14680064000   Unclaimed    Active   14m
```
