### DISCUSSION TITLE
Very low speed in creating new replicas - cstor

### DISCUSSION THREAD

**Discussion by mohammada315** [openebs/openebs#3691] [Q&A]
dear openebs developers
I have a Kubernetes cluster with 10 nodes ( 32Core , 128Gi ram , 128Gi SSD for host OS )
And now I am using c-stor ( replication 3 ) ( in HDD hard raid 5 )
When one of the nodes fails and I want to move the replicas
This operation is very slow
For example, a 200 GB replica takes 15-20 hours to upgrade from 2 to 3 replicas
For example in this example
![Screenshot_2024-02-09_15-41-31](https://github.com/openebs/openebs/assets/29116372/880d5e33-303f-433a-b0eb-88eb11cb34d4)

To improve performance I made some changes according to [this document](https://openebs.io/docs/user-guides/cstor/advanced)

```
apiVersion: cstor.openebs.io/v1
kind: CStorVolumePolicy
metadata:
  name: csi-volume-policy
  namespace: openebs
spec:
  replica:
    zvolWorkers: "16"
  target:
    luWorkers: 16
    queueDepth: "128"

```
After editing the CVCs, the situation improved, but the speed is still low
