### ISSUE TITLE
OpenEBS storage policy for DevOps

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1010]
## A Brief Introduction
This issue talks about putting policy into the hands of operators & hence offering finest level of granularity. This issue talks about implementation of OpenEBS storage policy via a generic MayaPolicy.

NOTE: This is key to implement #976 

Details are available in [OpenEBS for DevOps](https://docs.google.com/document/d/1oX_AcDMuhg2HVn3nmYDaZ-ABQv_V0v_DhbbySUImAhg) and [Volume Policy 0.6.0](https://docs.google.com/presentation/d/1PFbHNfNOHFr5JhdXeON_s5cqEY2gwaQ9it1wAD_cZRc/edit#slide=id.g2efbdf9cdf_0_172)

The Yaml specifications & test steps  are mentioned in this issue as separate comments.

**Comment by AmitKumarDas** [comment]
### YAML Specifications

#### StorageClass specification
- Watch out for `openebs.io/storage-policy`. This is understood by maya operator.
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-percona
  annotations:
    openebs.io/provisioner: provisioner-iscsi
    provisioner.openebs.io/version: 0.6.0
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-policy: "my-stor-policy"
```

#### StoragePolicy specification
- Maya exposes StoragePolicy as a Kubernetes `CustomResource`
```yaml
apiVersion: openebs.io/0.6.0
kind: MayaStoragePolicy
metadata:
  name: my-stor-policy
  annotations:
    # Below is updated by the maya operator once this CR is installed
    openebs.io/referredTemplate:
spec:
  # name of the template
  baseTemplate: 
  policies:
    type: ReplicaCount
      value: 2
    type: ReplicaImage
      value: openebs.io/jiva:0.6.0
    type: IsMonitoring
      value: On
    type: StoragePool
      refer: my-host-dir
    type: Quota
      yaml:
    type: QOS
      yaml:
    type: Snapshot
      yaml:
status:
  phase:
  message:
  reason:
  conditions:
    - type:
      status:
      lastProbeTime:
      lastTransitionTime:
      reason:
      message:
```

**Comment by AmitKumarDas** [comment]
## YAML Specifications -- Low Level

### MayaRun Specification
- This specification understood by maya-runner operator
- This is expressed as a K8s ConfigMap
- MayaRun is the declarative code that maya uses to provision openebs volume in K8s
- MayaRun is a specification that executes various MayaTemplate specs
- Below is a sample MayaRun template:
  - Notice how this is referred from the StorageClass as openebs.io/storage-policy
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: maya-run-tpl-0.6.0
  labels:
    openebs.io/kind: MayaRun
    mayarun.openebs.io/version: 0.6.0
  annotations:
    openebs.io/operator: maya-runner
    operator.openebs.io/version: 0.6.0
data:
  yaml: |
    inputs:
      - namespace: storageguy
      - storage-engine-type: cstor
      - owner: abc-123-123
      - replica-image: openebs/jiva:0.5.0
      - replica-count: 2
      - controller-image: openebs/jiva:0.5.0
      - monitoring-image: openebs/vol-monitor:0.1.0
      - volume-mon-lbl-key: openebs.io/monitoring
      - volume-mon-lbl-val: vol-mon
      - capacity: 20G
      - storage-pool-path: /var/openebs
    imports:
      - template: storage-service-tpl-0.6.0
      - template: storage-config-tpl-0.6.0
      - template: storage-controller-tpl-0.6.0
      - template: storage-replica-tpl-0.6.0
```

### MayaTemplate Specification
- MayaTemplate is expressed as a K8s ConfigMap
- MayaTemplate can embed any K8s Kind
- This template specification is used by MayaRun
  - In other words, MayaRun composes a set of MayaTemplate(s)

#### OpenEBS Service As MayaTemplate
- Below is a sample MayaTemplate spec that represents an `openebs service`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-service-tpl-0.6.0
  labels:
    openebs.io/kind: MayaTemplate
    mayatemplate.openebs.io/version: 0.6.0
  annotations:
    openebs.io/operator: maya-runner
    operator.openebs.io/version: 0.6.0
    mayatemplate.openebs.io/meta: |
      namespace: {{inputs “namespace”}}
      apiVersion: v1
      kind: Service
      action: put
data:
  yaml: |
    apiVersion: {{.APIVersion}}
    Kind: {{.Kind}}
    metadata:
      labels:
        openebs.io/controller-service: {{inputs “storage-engine-type”}}-controller-svc
        openebs.io/storage-engine-type: {{inputs “storage-engine-type”}}
        openebs.io/pv: {{.Owner}}
      name: {{.Owner}}-ctrl-svc
      namespace: {{.Namespace}}
    spec:
      ports:
      - name: iscsi
        port: 3260
        protocol: TCP
        targetPort: 3260
      - name: api
        port: 9501
        protocol: TCP
        targetPort: 9501
      selector:
        openebs.io/controller: {{inputs “storage-engine-type”}}-controller
        openebs.io/pv: {{.Owner}}
```

#### OpenEBS Config As MayaTemplate
- Below is a sample MayaTemplate spec that represents an `openebs config`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-config-tpl-0.6.0
  labels:
    openebs.io/kind: MayaTemplate
    mayatemplate.openebs.io/version: 0.6.0
  annotations:
    openebs.io/operator: maya-runner
    operator.openebs.io/version: 0.6.0
    mayatemplate.openebs.io/meta: |
      namespace: {{inputs “namespace”}}
      apiVersion: v1
      kind: ConfigMap
      action: put
data:
  yaml: |
    apiVersion: {{.APIVersion}}
    Kind: {{.Kind}}
    metadata:
      labels:
        openebs.io/storage-config: {{inputs “storage-engine-type”}}-config
        openebs.io/storage-engine-type: {{inputs “storage-engine-type”}}
        openebs.io/pv: {{.Owner}}
      name: {{.Owner}}-config
      namespace: {{.Namespace}}
    data: |
      pools:
      - type: src
        create: no
        name: spool
        cachefile: /tmp/cstor/spool.cache
        pooltype:
        diskpaths: /tmp/cstor/sdisk.img
      datasets:
      - type: src
        id: 0 
        create: no
        name: svol
        parent: spool
        volblocksize: 4096
        size: 10737418240
        readonly: off
        sync: always
        copies: 1
        logbias: latency
        compression: on
```

#### OpenEBS Controller As MayaTemplate
- Below is a sample MayaTemplate spec that represents an `openebs controller`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-controller-tpl-0.6.0
  labels:
    openebs.io/kind: MayaTemplate
    mayatemplate.openebs.io/version: 0.6.0
  annotations:
    openebs.io/operator: maya-runner
    operator.openebs.io/version: 0.6.0
    mayatemplate.openebs.io/meta: |
      namespace: {{inputs “namespace”}}
      apiVersion: v1
      kind: Deployment
      action: put
data:
  yaml: |
    apiVersion: {{.APIVersion}}
    Kind: {{.Kind}}
    metadata:
      labels:
        openebs.io/controller: {{inputs “storage-engine-type”}}-controller
        openebs.io/storage-engine-type: {{inputs “storage-engine-type”}}
        openebs.io/pv: {{.Owner}}
      name: {{.Owner}}-ctrl
      namespace: {{.Namespace}}
    spec:
      replicas: 1
      selector:
        matchLabels:
          {{inputs “volume-mon-lbl-key”}}: {{inputs “volume-mon-lbl-val”}}
          openebs.io/controller: {{inputs “storage-engine-type”}}-controller
          openebs.io/pv: {{.Owner}}
      template:
        metadata:
          labels:
            {{inputs “volume-mon-lbl-key”}}: {{inputs “volume-mon-lbl-val”}}
            openebs.io/controller: {{inputs “storage-engine-type”}}-controller
            openebs.io/pv: {{.Owner}}
        spec:
          containers:
          - args:
            - controller
            - --frontend
            - gotgt
            - --clusterIP
            - {{stores “service-ip”}}
            - {{.Owner}}
            command:
            - launch
            image: {{inputs “controller-image”}}
            name: {{.Owner}}-ctrl-con
            ports:
            - containerPort: 3260
              protocol: TCP
            - containerPort: 9501
              protocol: TCP
          - args:
            - -c=http://127.0.0.1:9501
            command:
            - maya-volume-exporter
            image: {{inputs “monitoring-image”}}
            name: maya-volume-exporter
            ports:
            - containerPort: 9500
              protocol: TCP
          tolerations:
          - effect: NoExecute
            key: node.alpha.kubernetes.io/notReady
            operator: Exists
            tolerationSeconds: 0
          - effect: NoExecute
            key: node.alpha.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 0
```

#### OpenEBS Replica As MayaTemplate
- Below is a sample MayaTemplate spec that represents an `openebs replica`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-replica-tpl-0.6.0
  labels:
    openebs.io/kind: MayaTemplate
    mayatemplate.openebs.io/version: 0.6.0
  annotations:
    openebs.io/operator: maya-runner
    operator.openebs.io/version: 0.6.0
    mayatemplate.openebs.io/meta: |
      namespace: {{inputs “namespace”}}
      apiVersion: v1
      kind: Deployment
      action: put
data:
  yaml: |
    apiVersion: {{.APIVersion}}
    Kind: {{.Kind}}
    metadata:
      labels:
        openebs.io/replica: {{inputs “storage-engine-type”}}-replica
        openebs.io/storage-engine-type: {{inputs “storage-engine-type”}}
        openebs.io/pv: {{.Owner}}
      name: {{.Owner}}-rep
      namespace: {{.Namespace}}
    spec:
      replicas: {{inputs “replica-count”}}
      selector:
        matchLabels:
          openebs.io/replica: {{inputs “storage-engine-type”}}-replica
          openebs.io/pv: {{.Owner}}
      template:
        metadata:
          labels:
            openebs.io/replica: {{inputs “storage-engine-type”}}-replica
            openebs.io/pv: {{.Owner}}
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    openebs.io/replica: {{inputs “storage-engine-type”}}-replica
                    openebs.io/pv: {{.Owner}}
                topologyKey: kubernetes.io/hostname
          containers:
          - args:
            - replica
            - --frontendIP
            - {{stores “service-ip”}}
            - --size
            - {{inputs “capacity”}}
            - /openebs
            command:
            - launch
            image: {{inputs “replica-image”}}
            name: {{.Owner}}-rep-con
            ports:
            - containerPort: 9502
              protocol: TCP
            - containerPort: 9503
              protocol: TCP
            - containerPort: 9504
              protocol: TCP
            volumeMounts:
            - name: openebs
              mountPath: /openebs
            - name: volume-config
              mountPath: /etc/config
          tolerations:
          - effect: NoExecute
            key: node.alpha.kubernetes.io/notReady
            operator: Exists
          - effect: NoExecute
            key: node.alpha.kubernetes.io/unreachable
            operator: Exists
          volumes:
          - name: openebs
            hostPath:
              path: {{inputs “storage-pool-path”}}/{{.Owner}}
          - name: volume-config
            configMap:
              name: {{.Owner}}
```

**Comment by AmitKumarDas** [comment]
```go
////////////////////////////////////////
//  pkg/types/
////////////////////////////////////////


// MayaPolicyType is a typed representation of various
// maya policies
type MayaPolicyType string

const (
  ReplicaCountMPT MayaPolicyType = "ReplicaCount"
  
  ReplicaImageMPT MayaPolicyType = "ReplicaImage"
  
  IsMonitoringMPT MayaPolicyType = "IsMonitoring"

  StoragePoolMPT MayaPolicyType = "StoragePool"

  QuotaMPT MayaPolicyType = "Quota"
  
  SnapshotMPT MayaPolicyType = "Snapshot"
)

// Policy represents a generic policy understood by maya
// It can compose of a value or refer to a resource or 
// even compose its yaml representation
type Policy struct {
  
  Type MayaPolicyType
  
  Value string
  
  Refer string
  
  Yaml string
}

// Verification comprises of properties that represents the
// verification results of an entity
type Verification struct {
  Type string
  
  Status string
  
  LastProbeTime string
  
  LastTransitioTime string
  
  Reason string
  
  Message string
}

// StoragePolicy represents a StoragePolicy specification
type StoragePolicy struct {

  metav1.TypeMeta   `json:",inline"`
  metav1.ObjectMeta `json:"metadata,omitempty"`

  Spec StoragePolicySpec `json:"spec"`
  
  Status StoragePolicyStatus `json:"status"`
}

// StoragePolicySpec refers to a RunTemplate and an array
// of policies
type StoragePolicySpec struct {
  RunTemplate string
  
  Policies []Policy
}

// StoragePolicyStatus holds the overall status of StoragePolicy 
// as well verification results of individual policy
type StoragePolicyStatus struct {
  Phase string
  
  Message string
  
  Reason string
  
  Verifications []Verification
}

////////////////////////////////////////
//  pkg/maya/maya.go
////////////////////////////////////////

// TemplateInfo composes various properties that provides
// information about a template
type TemplateInfo struct {
  // Kind of the template contents
  Kind
  // APIVersion of the template contents
  APIVersion
  // Namespace of the template contents
  Namespace
  // Action to be invoked on the template contents
  Action RunAction
}

// TemplateInfoFilter is a typed function that flags
// if the provided template suits the invoking function's 
// requirement
func TemplateInfoFilter func(TemplateInfo) bool

// OpenEBSKind represents various kinds of openebs objects
type OpenEBSKind string

const (
  MayaRunOEK OpenEBSKind = "MayaRun"

  MayaTemplateOEK OpenEBSKind = "MayaTemplate"
)

// TemplateSelector helps in selecting or identifying 
// required template
type TemplateSelector struct {
  Kind OpenEBSKind
  
  Select TemplateInfoFilter
  
  // Path is the nested path found in the selected 
  // template
  Path ...string
}

type MayaRunner struct {
}

func (m MayaRunner) Run() {}

func (m MayaRunner) Verify() {}

type RunTemplate struct {
  Inputs      map[string]string
  Stores      map[string]string
  Imports    []MayaTemplate
  Verifications []MayaVerification
}

type MayaTemplate struct {
  TemplateInfo
}

func (m MayaTemplate) GenerateDeployment() MayaDeployment {}

type K8sOperation {
  Verb Verb // add, update, get, delete, watch, inform, list, event
  
  Namespace string
  
  IsAllNamespaces bool
  
  Config  K8sConfig
}


////////////////////////////////////////
//     pkg/maya/policy.go
////////////////////////////////////////

// PolicyOpType represents the kind of policy action
type PolicyOpType string

const (
  // OnPOT indicates activation of the policy
  OnPOT PolicyOpType = "On"
  // OffPOT indicates de-activation of the policy
  OffPOT PolicyOpType = "Off"
  // CustomPOT indicates a custom policy logic
  CustomPOT PolicyOpType = "Custom"
  // InputsPOT indicates the policy has to populate
  // the inputs placeholder
  InputsPOT PolicyOpType = "Inputs"
  // StoresPOT indicates the policy has to populate
  // the stores placeholder
  StoresPOT PolicyOpType = "Stores"
)

// PolicyVerifyFn verifies the enforcement of any policy
type PolicyVerifyFn func() bool

// PolicyValueFn provides the policy value to be enforced
type PolicyValueFn func() interface{}

// PolicyOperation provides details of the 
// operation that a specific policy object would
// execute
type PolicyOperation struct {
  OpType PolicyOpType

  Operate PolicyOperateFn

  Verify PolicyVerifyFn
}

// PolicyEnforcer holds the contract methods implemented
// by all maya policies
type PolicyEnforcer interface {
  // Enforce implements the logic to enforce this policy
  Enforce() error
  // Verify implements the logic to verify the enforcement
  // of this policy. This is typically a post enforcement
  // logic.
  Verify() Verification
}

func NewPolicyEnforcer(policy Policy) (PolicyEnforcer, error) {
  if policy.Type == ReplicaCountMPT {
    return NewReplicaCountPolicy(policy), nil
  } else if policy.Type == ReplicaImageMPT {
    return NewReplicaImagePolicy(policy), nil
  }
  
  return nil, fmt.Errorf("Invalid policy '%v'", policy)
}

////////////////////////////////////////
//    pkg/maya/storage_policy.go
////////////////////////////////////////

type ReplicaCountStoragePolicy struct {
  Policy
  
  Template TemplateSelector
  
  Operation PolicyOperation
}

type ReplicaImageStoragePolicy struct {
  Policy
}

type IsMonitoringStoragePolicy struct {
  Policy
}

type StoragePoolStoragePolicy struct {
  Policy
}

type QuotaStoragePolicy struct {
  Policy
}

type SnapshotStoragePolicy struct {
  Policy
}

func (s StoragePolicy) Enforce() {
  // get all the storage policies
  // invoke Enforce() methods of all its policies
  // invoke MayaRun.Run()
}

func (s StoragePolicy) Verify() {
  // make use of Verify() method of all its policies
}
```

**Comment by AmitKumarDas** [comment]
### StorageClass

- $ cat 060-1-sc.yaml 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-percona-0.6.0
  annotations:
    provisioner.openebs.io/version: 0.6.0
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/volume-policy: openebs-policy-0.6.0
```
