### ISSUE TITLE
Support for cStor volume in maya

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1015]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

cStor is a new volume controller that runs inside a container (currently docker). Maya should support cStor as a new volume type.

**Comment by AmitKumarDas** [comment]
@payes can you please provide the Kubernetes yaml specifications to run cStor in Kubernetes ?

**Comment by payes** [comment]
> # prometheus-deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cstor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cstor 
    spec:
      containers:
        - name: cstor
          imagePullPolicy: IfNotPresent 
          image: payes/cstor:latest
          command: ["/bin/bash"]
          args: [ "-c", "chmod +x /init.sh; /init.sh volname=cstor_vol path=/tmp/cstor size=8g"]
          ports:
            - containerPort: 3260
              name: iscsi
            - containerPort: 22
              name: sshdname
          resources:
            requests:
#              # A memory request of 250M means it will try to ensure minimum
#              # 250MB RAM .
#              memory: "128M"
#              # A cpu request of 128m means it will try to ensure minimum
#              # .125 CPU; where 1 CPU means :
#              # 1 *Hyperthread* on a bare-metal Intel processor with Hyperthreading
              cpu: "50m"
#            limits:
#              memory: "700M"
#              cpu: "500m"
          volumeMounts:
            - name: cstor-volume
              mountPath: /tmp/cstor
      volumes:
        # All the time series stored in this volume in form of .db file.
        - name: cstor-volume
          hostPath:
            path: /tmp/cstor
---
apiVersion: v1
kind: Service
metadata:
  name: cstor
spec:
  ports:
  - name: iscsi
    port: 3260
    targetPort: 3260
  - name: sshname
    port: 22
    targetPort: 22
  selector:
    name: cstor
  type: LoadBalancer

**Comment by payes** [comment]
```yaml
#cstor deployment yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cstor1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cstor1 
    spec:
      containers:
        - name: cstor1
          imagePullPolicy: IfNotPresent 
          image: openebs/cstor:latest
          command: ["/bin/bash"]
          args: [ "-c", "/init.sh volname=cstor1_vol path=/tmp/cstor size=8g externalIP= yaml=cstor_mi.yaml"]
          ports:
            - containerPort: 3260
              name: iscsi
            - containerPort: 22
              name: sshdname
          resources:
            requests:
          volumeMounts:
            - name: cstor1-volume
              mountPath: /tmp/cstor
      volumes:
        - name: cstor1-volume
          hostPath:
            path: /tmp/cstor1
---
apiVersion: v1
kind: Service
metadata:
  name: cstor1
spec:
  ports:
  - name: iscsi
    port: 3260
    targetPort: 3260
  - name: sshname
    port: 22
    targetPort: 22
  selector:
    name: cstor1
  type: LoadBalancer
```
```yaml
#cstor config map
pools:
 - type: src
   create: true
   name: spool
   cachefile: /tmp/cstor/spool.cache
   pooltype:
   diskpaths: /tmp/cstor/sdisk.img

datasets:
 - type: src
   id: 0 
   create: true
   open: true
   externalIP:
   name: svol
   parent: spool
   volblocksize: 4096
   size: 10737418240
   readonly: off
   sync: always
   copies: 1
   logbias: latency
   compression: on
```
