### ISSUE TITLE
Explore available fault-injection tools for resiliency tests on kubernetes 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1048]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

**What happened**:

Here are some potential tools for fault-injection on kubernetes clusters. This issue has been raised to track the evaluation & comparison between said tools *for OpenEBS test purposes* 

- https://github.com/gaia-adm/pumba
- https://github.com/bloomberg/powerfulseal
- https://github.com/asobti/kube-monkey
- https://github.com/linki/chaoskube

**What you expected to happen**:

- Choose the appropriate tool for OpenEBS test requirements

**Comment by ksatchit** [comment]
Here is the analysis after evaluation efforts of potential (opensource) fault-injection/resiliency tools for e2e.

## Powerfulseal

- Pros
  - Install via pip, runs as binary on master/node
  - Has both interactive/autonomous mode of operation (long weekend runs) 
  - Can kill pods by specifying matches for namespace, deployment, labels, with various filters (state, IP, regex, injection period etc., 
  - Can kill nodes as well

- Cons
   - Built for python 3, needed changes to run for python 2.7 (our env is based on this) 
   - Node kill (which is what differentiates it from other chaos tools for K8s) supported only for openstack (recent support for AWS). Needs separate inventory file/derives kubernetes inventory only for Openstack/AWS
   -  Demoed/Unveiled at KubeCon 2017, Austin, with not enough examples
   - Couldn't find any dedicated Slack channel/IRC
 
## Chaoskube

- Pros 
  - Can kill pods by specifying matches for namespace, deployment, labels with filters, regex
  - Simple to run - has a helm-based install & a deployment manifest
  - Fits into test approach where a "no-policy" deployment (w/ --dry-run) can be made upfront and test scripts can invoke chaoskube binary within pod with desired filters/regex.
  - Uses in-cluster config (kube-config) by default
  - Can setup autonomous mode with execution filters like day/time etc.., 
  - Written in GO - can extend it based on requirements. GoDocs reference available
  - Wider usage trends (~1.5 years old w/ active contributions) 
  
- Cons
   - Does "only" pod kills, no node kills OR network faults 
   - Pod kills are via kubectl (or mostly emulating kubectl delete pod) - So *relatively* graceful termination flow 
   - Uses RBAC as kill/delete is via kubernetes. Need the cluster setup to support/need right (admin) credentials to apply 
   - No slack channel/IRC

## Pumba 

- Pros
  - Standard, mature GO-based tool (2 yrs) with active development 
  - Can really "kill" container (SIGTERM, SIGKILL) - docker pause/stop/kill/remove, takes regex filters
  - Can perform network faults (delay -w/ jitter, packet loss) 
  - Runs as a binary on the node, regular releases available. Can run as daemonset on kubernetes
  - Has a Gitter-chat channel 
 
- Cons: 
   - This tool is built with docker in mind, more than kubernetes - warrants running the tool on node where pod/container runs
   - Can run as container, but needs to be scheduled on target node w/ /var/run/docker.sock mounted (daemonset) 
   - The execution filters - days/time etc., are not as extensive as powerfulseal/chaoskube

Other notable options : kube-monkey (enhanced version on chaoskube with focus on more execution filters) 

## Current thoughts : 

- A combination of chaoskube & pumba can be used in the test scripts/playbooks to generate pod failures and network failures. Would like to avoid powerfulseal just yet (atleast temporarily, cloud-drivers are coming up which we can watch and adopt). An alternate means to automate node-failure cases needs to be looked at (chaosmonkey/simoorg ? ). 

- None of the aforementioned tools are providing for a pre-inject condition/post-inject health-check by themselves. So looks like this is something that we will have to handle in the test-scripts itself

## Sample Test Outputs: 

- Chaoskube: 

  ```
  apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: chaoskube
    labels:
      app: chaoskube
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: chaoskube
      spec:
        serviceAccountName: chaoskube
        containers:
        - name: chaoskube
          image: quay.io/linki/chaoskube:v0.8.0
          args:
          # Provided below are possible flags to set in chaoskube.
          # This deployment will create a vanilla chaoskube w/o policies
          # which will be configured by a test playbook
       
          # kill a pod every 10 minutes
          #- --interval=10m
        
          # only target pods in the test environment
          #- --labels=openebs/controller=jiva-controller
        
          # only consider pods with this annotation
          #- --annotations=chaos.alpha.kubernetes.io/enabled=true
        
          # exclude all pods in the kube-system namespace
          #- --namespaces=!kube-system
        
          # don't kill anything on weekends
          #- --excluded-weekdays=Sat,Sun
        
          # don't kill anything during the night or at lunchtime
          #- --excluded-times-of-day=22:00-08:00,11:00-13:00
        
          # don't kill anything as a joke or on christmas eve
          #- --excluded-days-of-year=Apr1,Dec24
        
          # let's make sure we all agree on what the above times mean
          #- --timezone=UTC
        
          # terminate pods for real: this disables dry-run mode which is on by default
          #- --no-dry-run 

  ```
  ```
  karthik@MayaMaster:~/resiliency/chaoskube$ kubectl apply -f chaoskube.yaml
  deployment "chaoskube" created
  serviceaccount "chaoskube" created

  karthik@MayaMaster:~/resiliency/chaoskube$ kubectl apply -f rbac.yaml
  clusterrole "chaoskube" configured
  clusterrolebinding "chaoskube" configured
  ```
  ```
  / $ chaoskube --labels 'openebs/controller=jiva-controller' --no-dry-run --interval 30s --debug
  DEBU[0000] reading config                                annotations= debug=true dryRun=false 
  excludedDaysOfYear= excludedTimesOfDay= excludedWeekdays= interval=30s kubeconfig= 
  labels="openebs/controller=jiva-controller" master= namespaces= timezone=UTC
  INFO[0000] starting up                                   dryRun=false interval=30s version=v0.8.0
  DEBU[0000] using cluster config                          kubeconfig= master=
  INFO[0000] connected to cluster                          master="https://10.96.0.1:443" serverVersion=v1.8.2
  INFO[0000] setting pod filter                            annotations= labels="openebs/controller=jiva-
  controller" namespaces=
  INFO[0000] setting quiet times                           daysOfYear="[]" timesOfDay="[]" weekdays="[]"
  INFO[0000] setting timezone                              location=UTC name=UTC offset=0
  DEBU[0000] found candidates                              count=1
  INFO[0000] terminating pod                               name=pvc-748af881-279f-11e8-b04f-000c298ff5fc-ctrl-
  7cbb7fbf96-nds2n namespace=default
  DEBU[0000] sleeping                                      duration=30s
  ```
  ```
  karthik@MayaMaster:~/resiliency$ kubectl get pods
  NAME                                                             READY     STATUS        RESTARTS   AGE
  chaoskube-55fc8f5f6d-tl7hb                                       1/1       Running       0          8m 
  maya-apiserver-5d5944b47c-jq62q                                  1/1       Running       0          6h
  openebs-provisioner-6b8df9746c-4wrwq                             1/1       Running       0          6h
  percona-5b9df94795-zv48m                                         1/1       Running       0          13m
  pvc-748af881-279f-11e8-b04f-000c298ff5fc-ctrl-7cbb7fbf96-5xf46   2/2       Running       0          4s
  pvc-748af881-279f-11e8-b04f-000c298ff5fc-ctrl-7cbb7fbf96-nds2n   0/2       Terminating   0          46s
  pvc-748af881-279f-11e8-b04f-000c298ff5fc-rep-59487444f7-8qh6w    1/1       Running       0          13m
  ```
- Pumba
   
  ```
  karthik@MayaHost02:~$ sudo ./pumba_linux_amd64 --help
  : 
  COMMANDS:
     kill     kill specified containers
     netem    emulate the properties of wide area networks
     pause    pause all processes
     stop     stop containers
     rm       remove containers
     start    start containers
     help, h  Shows a list of commands or help for one command

  GLOBAL OPTIONS:
     --host value, -H value      daemon socket to connect to (default: "unix:///var/run/docker.sock [$DOCKER_HOST]
     --tls                       use TLS; implied by --tlsverify
     --tlsverify                 use TLS and verify the remote [$DOCKER_TLS_VERIFY]
     --tlscacert value           trust certs signed only by this CA (default: "/etc/ssl/docker/ca.pem")
     --tlscert value             client certificate for TLS authentication (default: "/etc/ssl/docker/cert.pem")
     --tlskey value              client key for TLS authentication (default: "/etc/ssl/docker/key.pem")
     --debug                     enable debug mode with verbose logging
     --json                      produce log in JSON format: Logstash and Splunk friendly
     --slackhook value           web hook url; send Pumba log events to Slack
     --slackchannel value        Slack channel (default #pumba) (default: "#pumba")
     --interval value, -i value  recurrent interval for chaos command; use with optional unit suffix: 'ms/s/m/h'
     --random, -r                randomly select single matching container from list of target containers
     --dry                       dry run does not create chaos, only logs planned chaos commands
     --help, -h                  show help
     --version, -v               print the version
  ```
  ```
  karthik@MayaHost02:~$ sudo ./pumba_linux_amd64 --interval 10s kill re2:percona
  INFO[0000] Kill containers
  INFO[0000] Killing /k8s_percona_percona-5b9df94795-hgfss_default_d8633e67-27a2-11e8-b04f-
  000c298ff5fc_2 (0ff8fbef6436f22962dae09fd44b739c00fbf857c5f3314bb6a63916e1082f11) with signal 
  SIGKILL
  INFO[0000] Killing /k8s_POD_percona-5b9df94795-hgfss_default_d8633e67-27a2-11e8-b04f-
  000c298ff5fc_3 (f5e6cafcf27b5d7a26ebef119b7c4e603da40a7e2275e73ffd5a00eded52352f) with signal 
  SIGKILL
  INFO[0010] Kill containers
  INFO[0010] Killing /k8s_POD_percona-5b9df94795-hgfss_default_d8633e67-27a2-11e8-b04f-
  000c298ff5fc_4 (ba661a82952f277f823594c7d00ec4494f3df04c8e526d1876ed9d7d63854945) with s 
  signal SIGKILL
  ```
  ```
  karthik@MayaMaster:~/resiliency$ kubectl get pods
  NAME                                                             READY     STATUS             RESTARTS   AGE
  maya-apiserver-5d5944b47c-jq62q                                  1/1       Running            0          6h
  openebs-provisioner-6b8df9746c-4wrwq                             1/1       Running            0          6h
  percona-5b9df94795-hgfss                                         0/1       CrashLoopBackOff   2          7m
  pvc-748af881-279f-11e8-b04f-000c298ff5fc-ctrl-7cbb7fbf96-jmfrl   2/2       Running            0          16m
  pvc-748af881-279f-11e8-b04f-000c298ff5fc-rep-59487444f7-8qh6w    1/1       Running            0          
  31m
  ```
  ```
  karthik@MayaHost02:~$ sudo ./pumba_linux_amd64 netem --duration 240s --interface eth0 delay --
  time 3000 jitter 50 --correlation 20 re2:ctrl
  INFO[0000] netem: delay for containers
  ```
