### ISSUE TITLE
Support for grouping of policies in VolumeParameterGroup

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1185]
The current VolumePolicy spec as per #1010 is:
```yaml
spec:
  policies: 
  - name: VolumeMonitor
    enabled: "true"
    value: openebs/m-exporter:0.5.0
  - name: ControllerImage
    value: openebs/jiva:0.5.0
  - name: ReplicaImage
    value: openebs/jiva:0.5.0
  - name: ReplicaCount
    value: "2"
  - name: StoragePool
    value: ssd
```

The proposed custom parameters can be specified as an `extension` attribute as shown below:
```yaml
spec:
  policies: 
  - name: VolumeMonitor
    enabled: "true"
    extension:
    - image: |
        repository: openebs/m-exporter
        tag: 0.5.0
        pullPolicy: IfNotPresent
  - name: ControllerImage
    extension:
      image: openebs/jiva:0.5.0
      pullPolicy: IfNotPresent
  - name: ReplicaImage
    value: openebs/jiva:0.5.0
  - name: ReplicaCount
    value: "2"
  - name: StoragePool
    value: nvme
    extension:
    - default: ssd
```

This extension attribute should be able to hold an arbitrary key:object pairs i.e. 
```go
map[string]interface{}
```
