### ISSUE TITLE
Update the openebs operator to include VolumePolicy as a CRD

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1190]
This should be included into operator.

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: volumepolicies.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: volumepolicies
    # singular name to be used as an alias on the CLI and for display
    singular: volumepolicy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: VolumePolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - vp
```
