### ISSUE TITLE
VolumePolicy should set an identity for a task rather than setting the identity based on the order of the task

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1191]
This is the current VolumePolicy

```yaml
apiVersion: openebs.io/v1alpha1
kind: VolumePolicy
metadata:
  name: openebs-policy-0.6.0
spec:
  policies:
  - name: VolumeMonitor
    enabled: "true"
    value: openebs/m-exporter:0.5.0
  - name: ControllerImage
    value: openebs/jiva:0.5.0
  - name: ReplicaImage
    value: openebs/jiva:0.5.0
  - name: ReplicaCount
    value: "2"
  - name: StoragePool
    value: ssd
  run:
    searchNamespace: default
    tasks:
    - template: volume-service-0.6.0
    - template: volume-path-0.6.0
    - template: volume-controller-0.6.0
    - template: volume-replica-0.6.0
```

This is the proposed one with identity for a task:

```yaml
apiVersion: openebs.io/v1alpha1
kind: VolumePolicy
metadata:
  name: openebs-policy-0.6.0
spec:
  policies:
  - name: VolumeMonitor
    enabled: "true"
    value: openebs/m-exporter:0.5.0
  - name: ControllerImage
    value: openebs/jiva:0.5.0
  - name: ReplicaImage
    value: openebs/jiva:0.5.0
  - name: ReplicaCount
    value: "2"
  - name: StoragePool
    value: ssd
  run:
    searchNamespace: default
    tasks:
    - template: volume-service-0.6.0
      identity: vsvc
    - template: volume-path-0.6.0
      identity: vpath
    - template: volume-controller-0.6.0
      identity: vctrl
    - template: volume-replica-0.6.0
      identity: vrep
```

NOTE: The identity should be uniquely named in the VolumePolicy.
