### ISSUE TITLE
Grafana pod using OpenEBS PV for grafana.db seen to show different data on different cluster nodes 

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1278]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

**What happened**:

A grafana pod using OpenEBS PV for storing grafana data (/var/lib/grafana) shows different data (wrt users created) - as viewed on the grafana dashboard when the application pod resides on different cluster node. A sample sequence of steps describing the problem is shown here : 

a/ When grafana in Node-1 : create some users - user1/2/3
b/ Redeploy grafana (kill grafana pod) 
c/ When grafana moved to Node-2 : user1/2/3 are present. So create user 4/5/6
d/ Wait for some time (few seconds) 
e/ Redeploy grafana back to Node1 (by kill pod) 
f/ Observed that only user1/2/3 present, 4/5/6 not present

**What you expected to happen**:

The users/data in general should be same irrespective of where the application pod resides

**How to reproduce it (as minimally and precisely as possible)**:

Create users/dashboard/organizations and delete the grafana pod and check if the same if visible when the grafana pod comes up on another node.

**Anything else we need to know?**:

- The OpenEBS PV is created on GPD 
- Revision.counter file shows the same value on the storage replica backend

**Comment by kmova** [comment]
@ksatchit Can you share the grafana yaml file and the way volumes paths are configured.

**Comment by ksatchit** [comment]
- The grafana yaml used is provided below : 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: maya-grafana
  name: maya-grafana
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: maya-grafana
    spec:
      securityContext:
        fsGroup: 107
      containers:
      - image: grafana/grafana:4.6.3
        name: master-grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/grafana"
          - name: maya-grafana-store
            mountPath: /var/lib/grafana
            # /var holds grafana db and plugins 
      volumes:
        - name: config-volume
          configMap:
            name: maya-grafana-cfgmap
        - name: maya-grafana-store
          persistentVolumeClaim:
            claimName: grafana-claim
---
# grafana-service
apiVersion: v1
kind: Service
metadata:
  name: maya-grafana-service
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: maya-grafana
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: openebs-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40G
```

- A storage pool custom resource was created using path "/mnt/openebs" which in turn was the location where the GPD was mounted after an ext4 format operation (this operation was repeated on both the nodes). This custom storage pool was referenced in the StorageClass "openebs-grafana" used in the persistent volume claim seen above. 

```
karthik_s@maya-gcloud:~/grafana$ kubectl describe sp sp-mntdir-v0
Name:         sp-mntdir-v0
Namespace:    
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"openebs.io/v1alpha1","kind":"StoragePool","metadata":{"annotations":{},"name":"sp-mntdir-v0","namespace":"","type":"hostdir"},"spec":{"p...
API Version:  openebs.io/v1alpha1
Kind:         StoragePool
Metadata:
  Cluster Name:                   
  Creation Timestamp:             2018-01-24T12:02:28Z
  Deletion Grace Period Seconds:  <nil>
  Deletion Timestamp:             <nil>
  Generation:                     0
  Resource Version:               1416816
  Self Link:                      /apis/openebs.io/v1alpha1/sp-mntdir-v0
  Type:                           hostdir
  UID:                            72e54401-00fe-11e8-988d-42010a800039
Spec:
  Path:  /mnt/openebs
Events:  <none>
```
```
karthik_s@maya-gcloud:~/grafana$ kubectl describe sc openebs-grafana
Name:            openebs-grafana
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"openebs-grafana","namespace":""},"parameters":{"openebs.io/capacity":"40G","openebs.io/jiva-replica-count":"2","openebs.io/jiva-replica-image":"openebs/jiva:0.5.1","openebs.io/storage-pool":"sp-mntdir-v0"},"provisioner":"openebs.io/provisioner-iscsi"}

Provisioner:  openebs.io/provisioner-iscsi
Parameters:   openebs.io/capacity=40G,openebs.io/jiva-replica-count=2,openebs.io/jiva-replica-image=openebs/jiva:0.5.1,openebs.io/storage-pool=sp-mntdir-v0
Events:       <none>
```
