### ISSUE TITLE
VolumePolicy should support taint tolerations in volume controller & volume replicas

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1304]
Operator might want to **dedicate** nodes for volume pod controllers & volume pod replicas. In other words **dedicated nodes for storage**.
e.g.
- operator will taint the node as follows:
```
kubectl taint nodes node1 ssd=yes:NoExecute
kubectl taint nodes node1 ssd=yes:NoSchedule
```
- volume pods (replica &/or controller) need to tolerate above taints as follows:
```
tolerations:
- key: "ssd"
  operator: "Equal"
  value: "yes"
  effect: "NoSchedule"
- key: "ssd"
  operator: "Equal"
  value: "yes"
  effect: "NoExecute"
```

**Comment by AmitKumarDas** [comment]
> Posting these trials & eventual success as `yaml oriented programming` is very new to the team.

### 1/ 

- the volume policy snippet looks like below:
```yaml
  - name: StorageTaints
    value: |-
      - key: ssd
        operator: Equal
        value: yes
        effect: NoSchedule
      - key: ssd
        operator: Equal
        value: yes
        effect: NoExecute
```
- the replica template snippet looks like:
```yaml
          tolerations:
          {{- if ne $isStorageTaints "false" -}}
          {{ $storageTaintsVal }}
          {{- end -}}
```
- Error
```bash
Failed to run: Will rollback: Error: 'error converting YAML to JSON: yaml: line 63: did not find expected key' 

Values: 'map[string]interface {}{
  "TaskResult":map[string]interface {}{
    "vctrl":map[string]string{"objectName":"jivavolpol-ctrl"}, 
    "vsvc":map[string]string{"objectName":"jivavolpol-ctrl-svc", "serviceIP":"10.96.221.33"}, 
    "vpath":map[string]string{"objectName":"ssd", "storagePoolPath":"/var/myebs"}, 
    "vctrl-annotations":map[string]string{"openebs.io/volume-type":"jiva", "openebs.io/volume-monitor":"true"}}, 
  "Volume":map[string]string{
    "runNamespace":"default", 
    "owner":"jivavolpol", 
    "capacity":"2G"}, 
  "Policy":map[string]interface {}{
    "StoragePool":map[string]string{"value":"ssd", "enabled":""}, 
    "StorageTaints":map[string]string{"enabled":"", "value":"- key: ssd\n  operator: Equal\n  value: yes\n  effect: NoSchedule\n- key: ssd\n  operator: Equal\n  value: yes\n  effect: NoExecute"}, 
  "ControllerImage":map[string]string{"enabled":"", "value":"openebs/jiva:0.5.0"}, 
  "ReplicaImage":map[string]string{"enabled":"", "value":"openebs/jiva:0.5.0"}, 
  "ReplicaCount":map[string]string{"enabled":"", "value":"1"}}}'
```

### 2/
- the volume policy snippet looks like:
```yaml
  - name: StorageTaints
    value: |-
      - key: ssd
        operator: Equal
        value: yes
        effect: NoSchedule
      - key: ssd
        operator: Equal
        value: yes
        effect: NoExecute
```
- the replica template snippet looks like:
```yaml
          tolerations:
          {{- if ne $isStorageTaints "false" -}}
          {{ $storageTaintsVal | indent 11 }}
          {{- end -}}
```
- Error
```bash
Failed to run: Will rollback: Error: 'error converting YAML to JSON: yaml: line 59: block sequence entries are not allowed in this context' 

Values: 'map[string]interface {}{
  "Volume":map[string]string{"owner":"jivavolpol", "capacity":"2G", "runNamespace":"default"}, 
  "Policy":map[string]interface {}{
    "StorageTaints":map[string]string{"enabled":"", "value":"- key: ssd\n  operator: Equal\n  value: yes\n  effect: NoSchedule\n- key: ssd\n  operator: Equal\n  value: yes\n  effect: NoExecute"}, 
    "ControllerImage":map[string]string{"enabled":"", "value":"openebs/jiva:0.5.0"}, "ReplicaImage":map[string]string{"value":"openebs/jiva:0.5.0", "enabled":""}, 
    "ReplicaCount":map[string]string{"enabled":"", "value":"1"}, "StoragePool":map[string]string{"enabled":"", "value":"ssd"}}, 
  "TaskResult":map[string]interface {}{
    "vsvc":map[string]string{"objectName":"jivavolpol-ctrl-svc", "serviceIP":"10.106.73.104"}, 
    "vpath":map[string]string{"objectName":"ssd", "storagePoolPath":"/var/myebs"}, 
    "vctrl":map[string]string{"objectName":"jivavolpol-ctrl"}, 
    "vctrl-annotations":map[string]string{"openebs.io/volume-monitor":"true", "openebs.io/volume-type":"jiva"}}}'
```

### 3/
- the volume policy snippet looks like:
```yaml
  - name: StorageTaints
    value: |-
      key: ssd
      operator: Equal
      value: yes
      effect: NoSchedule
```
- the replica template snippet looks like below:
```yaml
          tolerations:
          {{- if ne $isStorageTaints "false" -}}
          - {{ $storageTaintsVal | indent 11 }}
          {{- end -}}
```
- Error:
```bash
error converting YAML to JSON: yaml: line 60: mapping values are not allowed in this context  
```

### 4/
- the volume policy looks like:
```yaml
  - name: StorageTaints
    value: |-
      key: ssd
      operator: Equal
      value: yes
      effect: NoSchedule
```
- the replica template looks like below:
```yaml
          tolerations:
          {{- if ne $isStorageTaints "false" -}}
          - {{ $storageTaintsVal }}
          {{- end -}}
```
- Error:
```bash
error converting YAML to JSON: yaml: line 60: mapping values are not allowed in this context  
```

### 5/
- volume policy snippet looks like:
```yaml
  - name: StorageTaints
    value: |-
      t1:
        key: ssd
        operator: Equal
        value: yes
        effect: NoSchedule
```
- replica template snippet looks like:
```yaml
    {{- $isStorageTaints := .Policy.StorageTaints.value | default "false" -}}
    {{- $storageTaintsVal := fromYaml .Policy.StorageTaints.value -}}
    
          tolerations:
          {{- if ne $isStorageTaints "false" }}
          {{- range $k, $v := $storageTaintsVal }}
            - {{ $v }}
          {{- end }}
          {{- end }}
```
- Error:
```bash
error unmarshaling JSON: json: cannot unmarshal string into Go struct field PodSpec.tolerations of type v1.Toleration  03MAR2018 > kubectl -n openebs po

Failed to run: Will rollback: Error: 'error unmarshaling JSON: json: cannot unmarshal string into Go struct field PodSpec.tolerations of type v1.Toleration' 

Values: 'map[string]interface {}{
  "Volume":map[string]string{"runNamespace":"default", "owner":"jivavolpol", "capacity":"2G"}, 
  "Policy":map[string]interface {}{
    "StorageTaints":map[string]string{"enabled":"", "value":"t1:\n  key: ssd\n  operator: Equal\n  value: yes\n  effect: NoSchedule"}, 
    "ControllerImage":map[string]string{"enabled":"", "value":"openebs/jiva:0.5.0"}, 
    "ReplicaImage":map[string]string{"enabled":"", "value":"openebs/jiva:0.5.0"}, 
    "ReplicaCount":map[string]string{"enabled":"", "value":"1"}, 
    "StoragePool":map[string]string{"enabled":"", "value":"ssd"}}, 
  "TaskResult":map[string]interface {}{
    "vsvc":map[string]string{"objectName":"jivavolpol-ctrl-svc", "serviceIP":"10.96.13.229"}, 
    "vpath":map[string]string{"objectName":"ssd", "storagePoolPath":"/var/myebs"}, 
    "vctrl":map[string]string{"objectName":"jivavolpol-ctrl"}, 
    "vctrl-annotations":map[string]string{"openebs.io/volume-monitor":"true", "openebs.io/volume-type":"jiva"}
  }
}'
```

### 6/
- volume policy snippet looks like below:
```yaml
  - name: StorageTaints
    value: |-
      t1:
        key: ssd
        operator: Equal
        value: yes
        effect: NoSchedule
```
- replica template snippet looks like:
```yaml
    {{- $isStorageTaints := .Policy.StorageTaints.value | default "false" -}}
    {{- $storageTaintsVal := fromYaml .Policy.StorageTaints.value -}}
    
          tolerations:
          {{- if ne $isStorageTaints "false" }}
          {{- range $k, $v := $storageTaintsVal }}
          - 
          {{- range $kk, $vv := $v }}
            {{ $kk }}: {{ $vv }}
          {{- end }}
          {{- end }}
          {{- end }}
```
- Sucess !!! YEAH !!!

### 7/
- volume policy snippet looks like:
```yaml
  - name: NodeTolerations
    value: |-
      t1:
        key: node.openebs.io/disktype
        operator: Equal
        value: ssd
        effect: NoSchedule
      t2:
        key: node.openebs.io/disktype
        operator: Equal
        value: ssd
        effect: NoExecute
      t3:
        effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      t4:
        effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
```
- replica template snippet looks like:
```yaml
    {{- $isNodeTolerations := .Policy.NodeTolerations.value | default "false" -}}
    {{- $nodeTolerationsVal := fromYaml .Policy.NodeTolerations.value -}}

          tolerations:
          {{- if ne $isNodeTolerations "false" }}
          {{- range $k, $v := $nodeTolerationsVal }}
          - 
          {{- range $kk, $vv := $v }}
            {{ $kk }}: {{ $vv }}
          {{- end }}
          {{- end }}
          {{- end }}
```
- Success !!! Yes !!

### 8/
- volume policy snippet looks like:
```yaml
  - name: TaintTolerations
    value: |-
      t1:
        key: node.openebs.io/disktype
        operator: Equal
        value: ssd
        effect: NoSchedule
      t2:
        key: node.openebs.io/disktype
        operator: Equal
        value: ssd
        effect: NoExecute
  - name: EvictionTolerations
    value: |-
      t1:
        effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      t2:
        effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
```
- replica template snippet looks like:
```yaml
    {{- $isTaintTolerations := .Policy.TaintTolerations.value | default "false" -}}
    {{- $taintTolerationsVal := fromYaml .Policy.TaintTolerations.value -}}
    {{- $isEvictionTolerations := .Policy.EvictionTolerations.value | default "false" -}}
    {{- $evictionTolerationsVal := fromYaml .Policy.EvictionTolerations.value -}}

          tolerations:
          {{- if ne $isTaintTolerations "false" }}
          {{- range $k, $v := $taintTolerationsVal }}
          - 
          {{- range $kk, $vv := $v }}
            {{ $kk }}: {{ $vv }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if ne $isEvictionTolerations "false" }}
          {{- range $k, $v := $evictionTolerationsVal }}
          - 
          {{- range $kk, $vv := $v }}
            {{ $kk }}: {{ $vv }}
          {{- end }}
          {{- end }}
          {{- end }}
```
- SUCCESS !!! YEAH !!

### 9/
- Add taint to node
```bash
kubectl taint nodes amit-thinkpad-l470 jk=jv:NoSchedule
```
- So no pod will be scheduled on node `amit-thinkpad-l470` unless it satisfies above taint
- Here the taint key is jk & taint value is jv & taint effect is NoSchedule
- Try to ADD openebs volume without above taint toleration
```bash
kubectl get po
NAME                               READY     STATUS    RESTARTS   AGE
jivavolpol-ctrl-867d945cd5-br79c   0/2       Pending   0          8s
jivavolpol-rep-5485cc774c-zpc7d    0/1       Pending   0          8s
```
- As expected pods dont get scheduled
```bash
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute
                 node.alpha.kubernetes.io/unreachable:NoExecute
                 node.openebs.io/disktype=ssd:NoSchedule
                 node.openebs.io/disktype=ssd:NoExecute
                 node.openebs.io/disktype=ssd:NoSchedule
                 node.openebs.io/disktype=ssd:NoExecute

Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  7s (x12 over 2m)  default-scheduler  0/1 nodes are available: 1 PodToleratesNodeTaints
```
- Remove taint from node
```bash
kubectl taint nodes amit-thinkpad-l470 jk:NoSchedule-
```
- The pods begin to schedule on the node
- SUCCESS !!! YEAH

### 10/
- the volume policy snippet looks likes:
```yaml
  - name: TaintTolerations
    value: |-
      t1:
        key: node.openebs.io/disktype
        operator: Equal
        value: ssd
        effect: NoSchedule
      t2:
        key: node.openebs.io/disktype
        operator: Equal
        value: ssd
        effect: NoExecute
      t3:
        key: jk
        operator: Equal
        value: jv
        effect: NoSchedule
  - name: EvictionTolerations
    value: |-
      t1:
        effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      t2:
        effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
```
- the replica template looks like:
```yaml
    {{- $isTaintTolerations := .Policy.TaintTolerations.value | default "false" -}}
    {{- $taintTolerationsVal := fromYaml .Policy.TaintTolerations.value -}}
    {{- $isEvictionTolerations := .Policy.EvictionTolerations.value | default "false" -}}
    {{- $evictionTolerationsVal := fromYaml .Policy.EvictionTolerations.value -}}
    
          tolerations:
          {{- if ne $isTaintTolerations "false" }}
          {{- range $k, $v := $taintTolerationsVal }}
          - 
          {{- range $kk, $vv := $v }}
            {{ $kk }}: {{ $vv }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if ne $isEvictionTolerations "false" }}
          {{- range $k, $v := $evictionTolerationsVal }}
          - 
          {{- range $kk, $vv := $v }}
            {{ $kk }}: {{ $vv }}
          {{- end }}
          {{- end }}
          {{- end }}
```
- Add taint to node
```bash
kubectl taint nodes amit-thinkpad-l470 jk=jv:NoSchedule
```
- So no pod will be scheduled on node `amit-thinkpad-l470` unless it satisfies above taint
- Here the taint key is jk & taint value is jv & taint effect is NoSchedule
- Try to ADD openebs volume with above taint toleration
- As expected pods GETS scheduled
- Remove taint from node
```bash
kubectl taint nodes amit-thinkpad-l470 jk:NoSchedule-
```
- No effect on the scheduled pods
- Success !! Yeah !!
