### ISSUE TITLE
volumepolicies & configmaps should be added as a resource in ClusterRole

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#1311]
This is to avoid below errors while provisioning openebs volumes using VolumePolicy:

```bash
volumepolicies.openebs.io "openebs-policy-taints-0.6.0" is forbidden: User "system:serviceaccount:openebs:openebs-maya-operator" cannot get volumepolicies.openebs.io at the cluster scope
```

```bash
configmaps "volume-service-0.6.0" is forbidden: User "system:serviceaccount:openebs:openebs-maya-operator" cannot get configmaps in the namespace "openebs"
```

Below is the suggested ClusterRole
```yaml
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: openebs-maya-operator
  labels:
    chart: "openebs-0.5.3"
rules:
- apiGroups: ["*"]
  resources: ["nodes","nodes/proxy"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["namespaces", "services", "pods", "deployments", "events", "endpoints", "configmaps"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["persistentvolumes","persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["storagepools","volumepolicies"]
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```
