### ISSUE TITLE
couchbase stays in ContainerCreating state with openebs

### ISSUE THREAD

**Issue by dpoison** [openebs/openebs#1437]
We have k8s 1.9.0 running cluster. 

Trying to deploy couchbase with openebs. 

Here is the status of pods. 
```
kubectl get pods
NAME                                                            READY     STATUS              RESTARTS   AGE
couchbase-0                                                     0/1       ContainerCreating   0          30m
maya-apiserver-69f9db69-vtl5b                                   1/1       Running             0          29m
openebs-provisioner-77cb47986c-pc265                            1/1       Running             0          38m
php-apache-9955bbfb5-tcv8h                                      1/1       Running             1          91d
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-ctrl-dbbb78b97-8rs7l   2/2       Running             0          28m
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-rep-5c8d64f596-v6mwn   1/1       Running             0          28m
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-rep-5c8d64f596-w6wx5   1/1       Running             0          28m
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-rep-5c8d64f596-x456l   1/1       Running             0          28m
```
openebs-operator.yaml
```
# Define the Service Account
# Define the RBAC rules for the Service Account
# Launch the maya-apiserver ( deployment )
# Launch the maya-storagemanager ( deameon set )

# Create Maya Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-maya-operator
  namespace: default
---
# Define Role that allows operations on K8s pods/deployments
#  in "default" namespace
# TODO : change to new namespace, for isolated data network
# TODO : the rules should be updated with required group/resources/verb
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: openebs-maya-operator
rules:
- apiGroups: ["*"]
  resources: ["nodes","nodes/proxy"]
  verbs: ["get","list","watch","create","update"]
- apiGroups: ["*"]
  resources: ["namespaces","services","pods","deployments", "events", "endpoints"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["persistentvolumes","persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: [ "get", "list", "create" ]
- apiGroups: ["*"]
  resources: ["storagepools"]
  verbs: ["get", "list"] 
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
# Bind the Service Account with the Role Privileges.
# TODO: Check if default account also needs to be there
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openebs-maya-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: openebs-maya-operator
  namespace: default
- kind: User
  name: system:serviceaccount:default:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: openebs-maya-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maya-apiserver
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maya-apiserver
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: maya-apiserver
        imagePullPolicy: Always
        image: openebs/m-apiserver:0.5.3
        ports:
        - containerPort: 5656
        env:
        # OPENEBS_IO_KUBE_CONFIG enables maya api service to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        - name: OPENEBS_IO_KUBE_CONFIG
          value: "/etc/kubernetes/kubeconfig"
        # OPENEBS_IO_K8S_MASTER enables maya api service to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        - name: OPENEBS_IO_K8S_MASTER
          value: "http://192.168.51.77:443"
        - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
          value: "openebs/jiva:0.5.3"
        - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
          value: "openebs/jiva:0.5.3"
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "openebs/m-exporter:0.5.3"
        - name: OPENEBS_IO_JIVA_REPLICA_COUNT
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: maya-apiserver-service
spec:
  ports:
  - name: api
    port: 5656
    protocol: TCP
    targetPort: 5656
  selector:
    name: maya-apiserver
  sessionAffinity: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openebs-provisioner
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: openebs-provisioner
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: openebs-provisioner
        imagePullPolicy: Always
        image: openebs/openebs-k8s-provisioner:0.5.3
        env:
        # OPENEBS_IO_K8S_MASTER enables openebs provisioner to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        # - name: OPENEBS_IO_K8S_MASTER
        #  value: "http://192.168.51.77:443"
        # OPENEBS_IO_KUBE_CONFIG enables openebs provisioner to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        # - name: OPENEBS_IO_KUBE_CONFIG
        #  value: "/etc/kubernetes/kubeconfig"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENEBS_MONITOR_URL
          value: "http://127.0.0.1:32515/dashboard/db/openebs-volume-stats?orgId=1"
        - name: OPENEBS_MONITOR_VOLKEY
          value: "&var-OpenEBS"
        - name: MAYA_PORTAL_URL
          value: "https://mayaonline.io/"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: storagepoolclaims.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: storagepoolclaims
    # singular name to be used as an alias on the CLI and for display
    singular: storagepoolclaim
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StoragePoolClaim
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - spc
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: storagepools.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: storagepools
    # singular name to be used as an alias on the CLI and for display
    singular: storagepool
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StoragePool
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sp
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-standard
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: volumepolicies.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: volumepolicies
    # singular name to be used as an alias on the CLI and for display
    singular: volumepolicy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: VolumePolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - vp
```
openebs-config.yaml

```
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: default
  type: hostdir
spec:
  path: "/var/openebs" 
  nodes: [ "all" ]
  #maxVolSize: 10G #Max Volume Size
  #maxAllocatedSize: 100G #Max Total Space allocated from this directory/mount
---
```
openebs-storageclasses.yaml
```
# Define a storage classes supported by OpenEBS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-standalone
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-percona
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-jupyter
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-mongodb
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-cassandra
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-redis
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-kafka
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 10G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-zk
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-es-data-sc
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
```
couchbase-statefulset.yaml
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: couchbase
spec:
  serviceName: "couchbase"
  replicas: 1
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: couchbase
        image: saturnism/couchbase:k8s-petset
        ports:
        - containerPort: 8091
        volumeMounts:
        - name: couchbase-data
          mountPath: /opt/couchbase/var
        env:
          - name: COUCHBASE_MASTER
            value: "couchbase-0.couchbase.default.svc.cluster.local"
          - name: AUTO_REBALANCE
            value: "false"
  volumeClaimTemplates:
  - metadata:
      name: couchbase-data
      annotations:
        volume.beta.kubernetes.io/storage-class: openebs-standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5G
```
couchbase-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: couchbase
  labels:
    app: couchbase
spec:
  ports:
  - port: 8091
    name: couchbase
  # *.couchbase.default.svc.cluster.local
  clusterIP: None
  selector:
    app: couchbase
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-ui
  labels:
    app: couchbase-ui
spec:
  ports:
  - port: 8091
    name: couchbase
  selector:
    app: couchbase
  sessionAffinity: ClientIP
  type: NodePort
```
While **kubectl get svc** out put is 
```
NAME                                                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
couchbase                                           ClusterIP   None         <none>        8091/TCP            41m
couchbase-ui                                        NodePort    10.3.0.115   <none>        8091:30966/TCP      41m
kubernetes                                          ClusterIP   10.3.0.1     <none>        443/TCP             103d
maya-apiserver-service                              ClusterIP   10.3.0.248   <none>        5656/TCP            1h
php-apache                                          ClusterIP   10.3.0.235   <none>        80/TCP              91d
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-ctrl-svc   ClusterIP   10.3.0.124   <none>        3260/TCP,9501/TCP   58m
```
**kubectl get sc**
```
NAME                     PROVISIONER                    AGE
openebs-cassandra        openebs.io/provisioner-iscsi   1h
openebs-es-data-sc       openebs.io/provisioner-iscsi   1h
openebs-jupyter          openebs.io/provisioner-iscsi   1h
openebs-kafka            openebs.io/provisioner-iscsi   1h
openebs-mongodb          openebs.io/provisioner-iscsi   1h
openebs-percona          openebs.io/provisioner-iscsi   1h
openebs-redis            openebs.io/provisioner-iscsi   1h
openebs-standalone       openebs.io/provisioner-iscsi   1h
openebs-standard         openebs.io/provisioner-iscsi   1h
openebs-standard-0.6.0   openebs.io/provisioner-iscsi   1m
openebs-zk               openebs.io/provisioner-iscsi   1h
```
**kubectl get pv**
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                STORAGECLASS       REASON    AGE
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c   5G         RWO            Delete           Bound     default/couchbase-data-couchbase-0   openebs-standard             59m
```
**kubectl get pvc**
```
NAME                         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
couchbase-data-couchbase-0   Bound     pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c   5G         RWO            openebs-standard   1h
```
**kubectl describe pod couchbase-0**
```
Name:           couchbase-0
Namespace:      default
Node:           kvmw3.example.com/192.168.53.79
Start Time:     Wed, 18 Apr 2018 11:53:49 +0200
Labels:         app=couchbase
                controller-revision-hash=couchbase-6698fcc56
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"default","name":"couchbase","uid":"64aea41f-42ee-11e8-ae9c-b65097f6e89c","apiVer...
Status:         Pending
IP:
Controlled By:  StatefulSet/couchbase
Containers:
  couchbase:
    Container ID:
    Image:          saturnism/couchbase:k8s-petset
    Image ID:
    Port:           8091/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      COUCHBASE_MASTER:  couchbase-0.couchbase.default.svc.cluster.local
      AUTO_REBALANCE:    false
    Mounts:
      /opt/couchbase/var from couchbase-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7gbf9 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  couchbase-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  couchbase-data-couchbase-0
    ReadOnly:   false
  default-token-7gbf9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7gbf9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                 From                        Message
  ----     ------                 ----                ----                        -------
  Normal   Scheduled              43m                 default-scheduler           Successfully assigned couchbase-0 to kvmw3.example.com
  Normal   SuccessfulMountVolume  43m                 kubelet, kvmw3.example.com  MountVolume.SetUp succeeded for volume "default-token-7gbf9"
  Warning  FailedMount            46s (x19 over 41m)  kubelet, kvmw3.example.com  Unable to mount volumes for pod "couchbase-0_default(64dcbe15-42ee-11e8-ae9c-b65097f6e89c)": timeout expired waiting for volumes to attach/mount for pod "default"/"couchbase-0". list of unattached/unmounted volumes=[couchbase-data]

```
couchbase-0 stays in *ContainerCreating* state only. Can anyone help on this?

Thanks in advance.
