### ISSUE TITLE
User request: Include an example for MongDB with XFS

### ISSUE THREAD

**Issue by umamukkara** [openebs/openebs#1446]
## Is this a BUG REPORT or FEATURE REQUEST?
Documentation enhancement
FEATURE REQUEST

User (Jezek Jan) is looking for an example documentation for using OpenEBS for MongoDB where the filesystem used is XFS. 

The issue is being opened to request addition of one more example documentation covering the above scenario

**Comment by ChandanSagar** [comment]
To use MongoDB with XFS please follow the below steps.

Install openebs.
Attach disk to the node.
Follow the below commands to attach the disk. 
 ```
sudo mkdir /mnt/openebs_disk
 sudo mkfs.xfs /dev/sdb
 sudo mount  /dev/sdb /mnt/openebs_disk
```
 

Add the below entries to operator.yaml
```
cd openebs/k8s/
vi operator.yaml
vi openebs-operator.yaml
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
    name: test-mntdir             
    type: hostdir
spec:
    path: "/mnt/openebs_disk"   
```   

Also make the below changes  in image section openebs-provisioner. 
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openebs-provisioner
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: openebs-provisioner
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: openebs-provisioner
        imagePullPolicy: Always
        image: prateek14/openebs-k8s-provisioner:ci
        env:
        # OPENEBS_IO_K8S_MASTER enables openebs provisioner to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        #- name: OPENEBS_IO_K8S_MASTER
        #  value: "http://10.128.0.12:8080"
        # OPENEBS_IO_KUBE_CONFIG enables openebs provisioner to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        #- name: OPENEBS_IO_KUBE_CONFIG
        #  value: "/home/ubuntu/.kube/config"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENEBS_MONITOR_URL
          value: "http://127.0.0.1:32515/dashboard/db/openebs-volume-stats?orgId=1"
        - name: OPENEBS_MONITOR_VOLKEY
          value: "&var-OpenEBS"
        - name: MAYA_PORTAL_URL
          value: "https://mayaonline.io/"
```
		  
		  
In openebs-storageclasses.yaml update the below entries in the openebs-mongodb section. 
```
vi openebs/k8s/openebs-storageclasses.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-mongodb
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "test-mntdir"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
  openebs.io/fstype: "xfs"
```
		 		  
Follow the below commands to set the user context.
While executing below commands use the output of 2nd command in the 3rd command in the --cluster=<output> section.
```
gcloud container clusters list
kubectl config current-context
kubectl config set-context test-admin --cluster=gke_strong-eon-153112_us-central1-a_xfs-testing-cluster-1 --user=cluster-admin
kubectl config use-context test-admin
```

Now run the below commands.
```
kubectl apply -f openebs-operator.yaml
kubectl apply -f openebs-storageclasses.yaml
```

Follow the below commads and update the below entries.
```
cd demo/mongodb
vi mongo-statefulset.yml
 
spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: mongo
         image: mongo
         command:
           - mongod
           - "--replSet"
           - rs0
           - "--smallfiles"
           - "--noprealloc"
           - "--bind_ip_all"
```
		   
Now edit the mongo-loadgen.yaml in the --mongo-url section you can either mention your pod i/p or your pod name.		   

`vi mongo-loadgen.yaml` 

> --mongo-url='mongodb://mongo-0.mongo'


Now run the below commands.		   
`kubectl apply -f mongo-statefulset.yml`

To check the pod status rum the below command.
`kubectl get pods`
Once all your pods are running run the below command.
`kubectl apply -f mongo-loadgen.yaml`

Now Mongo-DB is running with xfs file system.

Verify the log 
`kubectl logs -f mongo-loadgen-kvh65 `
Update the mongo-loadgen-kvh65 from the output of  `kubectl get pods`
