### ISSUE TITLE
OpenEBS operator fails to deploy jiva controller with image specified in the storageclass parameter "openebs.io/jiva-replica-image"

### ISSUE THREAD

**Issue by ksatchit** [openebs/openebs#1673]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

**What happened**:

- A percona application was deployed using an openebs storage class with the following specification, with the openebs control plane (maya-apiserver & provisioner) at image version 0.6.0-RC4. 

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-standard
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "3"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
  openebs.io/jiva-replica-image: "openebs/jiva:0.5.4"
```

**What you expected to happen**:

- Expected creation of the jiva controller and replica deployments with openebs/jiva:0.5.4 , as the storage class should override the maya-apiserver defaults. However, it was observed that while the replica deployments occurred with 0.5.4, the controller used 0.6.0-RC4. 

- Ability to launch desired versions of the storage engine via storageclass parameters should work. 

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy an application with the above storage class referenced in the PVC, with openebs control plane/operator on 0.6.0-RC4.

**Anything else we need to know?**:

- The same cluster had other volumes created already with jiva:0.6.0-RC4
