### ISSUE TITLE
What is the default OpenEBS retention policy

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#177]
https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/

**Comment by kmova** [comment]
The default retention is the same used by the K8s. 
Delete.

**Comment by muratkars** [comment]
Not exactly an issue here to address. 
Support for a storage policy that can disable the Jiva Volume Space reclaim. You can specify the jiva volume space reclaim feature setting using the value for RetainReplicaData property. In the following example, the jiva volume space reclaim feature is enabled as true. Hence, retain the volume data post PVC deletion.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-default
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: RetainReplicaData
        enabled: true   
```
