### ISSUE TITLE
Unable to create mirrored pool with RAID type as mirrored

### ISSUE THREAD

**Issue by mittachaitu** [openebs/openebs#2301]
## Description

After deploying below yaml with pool type as mirrored, expected that pool type will be mirrored.
```
---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: mirroredexternalspc
  annotations:
    cas.openebs.io/config: |
      - name: CstorPoolImage
        value: openebs/cstor-pool:ci
      - name: CstorPoolMgmtImage
        value: openebs/cstor-pool-mgmt:ci
spec:
  name: mirroredexternalspc
  type: disk
  maxPools: 3
  poolSpec:
    poolType: mirrored
  disks:
    diskList:
      - disk-2bfe6b64844a2fa6029264222bee9857
      - disk-6a6bc74e0c4036c12bc6acfc2835f103
      - disk-a85acac653297ff19e58d88a5507b7d8
      - disk-b1396f8f4834a4a5bdbb8d74c858b709
      - disk-cc545c5217d6b5f68454aea48c8cb1ba
      - disk-e1ace2ff1ad8e492d195b7dbb1e10b99
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mirrored-externalsc
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "mirroredexternalspc"
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi
```
but striped pool is created.
## Expected Behavior

The pool must be created with a defined pool type(yaml).
## Current Behavior

The striped pool is created instead of mirrored type.
## Steps to Reproduce

- Deploy above-mentioned yaml after deploying openebs-operator and spc and corresponding pools will be created.
- Then exec into any one of the pool-pod which is created after applying yaml.
- Execute the command `zpool iostat -v && zpool history` and output will be:
```
zpool iostat -v
                                              capacity     operations     bandwidth 
pool                                        alloc   free   read  write   read  write
------------------------------------------  -----  -----  -----  -----  -----  -----
cstor-67551159-f2d6-11e8-8591-066430713c30  91.0M  19.8G      0     51  3.13K  2.87M
  xvdc                                      52.4M  9.89G      0     25  1.43K  1.50M
  xvdd                                      38.6M  9.90G      0     25  1.69K  1.37M
------------------------------------------  -----  -----  -----  -----  -----  -----

History for 'cstor-67551159-f2d6-11e8-8591-066430713c30':
2018-11-28.06:25:41 zpool create -f -o cachefile=/tmp/mirroredexternalspc.cache -O io.openebs:poolname=mirroredexternalspc-iv8x cstor-67551159-f2d6-11e8-8591-066430713c30 /dev/xvdc /dev/xvdd
2018-11-28.06:29:43 zfs create -b 4K -s -o compression=on -o io.openebs:targetip=100.65.191.26 -o io.openebs:volname=pvc-f6198474-f2d6-11e8-8591-066430713c30-mirroredexternalspc-iv8x -V 5G cstor-67551159-f2d6-11e8-8591-066430713c30/pvc-f6198474-f2d6-11e8-8591-066430713c30

``` 
## Your Environment

* `kubectl get nodes`:
```
NAME                                       STATUS    ROLES     AGE       VERSION
ip-10-0-1-155.us-west-1.compute.internal   Ready     master    2h        v1.11.0
ip-10-0-1-213.us-west-1.compute.internal   Ready     node      2h        v1.11.0
ip-10-0-1-250.us-west-1.compute.internal   Ready     node      2h        v1.11.0
ip-10-0-1-61.us-west-1.compute.internal    Ready     node      2h        v1.11.0
```
* `kubectl get pv`:
```
pvc-f6198474-f2d6-11e8-8591-066430713c30   5G         RWO            Delete           Bound     app-percona-ns/demo-vol1-claim   mirrored-externalsc                         27m
```
* `kubectl get pvc`:
```
NAME              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
demo-vol1-claim   Bound     pvc-f6198474-f2d6-11e8-8591-066430713c30   5G         RWO            mirrored-externalsc   27m
```
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):```Linux ip-10-0-1-155 4.4.0-1067-aws #77-Ubuntu SMP Mon Aug 27 13:22:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

* Install tools:
* Others:
Logs:
[fake_mirrored_pool_bak.txt](https://github.com/openebs/openebs/files/2628153/fake_mirrored_pool_bak.txt)
[fake_mirrored_pool.txt](https://github.com/openebs/openebs/files/2628154/fake_mirrored_pool.txt)

@sonasingh46
