### ISSUE TITLE
failed to find extents, error: invalid argument

### ISSUE THREAD

**Issue by segator** [openebs/openebs#2333]
storage class jiva on a zfs path  does not work

the replica container fails with **"failed to find extents, error: invalid argument"**

I deployed openebs
```bash
helm install --name openebs --namespace openebs stable/openebs
```
and
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-jiva-zfs
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: StoragePool
        value: "ebs-jiva"
      - name: ReplicaCount
        value: "2"
provisioner: openebs.io/provisioner-iscsi
---
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: ebs-jiva
  type: hostdir
spec:
  path: "/zfs-pool/ebs"
```
Yes I have  all nodes with /zfs-pool/ebs path, xattr are enabled
