### ISSUE TITLE
Need ability to tune the cStor target for sequential workloads. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#2361]
## Description
I ran some quick dbench tests comparing the sequential vs random read/write workloads. While the Random workloads perform better compared against the hostPath volumes, the sequential workloads show lower numbers. The slowness in case of sequential workloads are caused by the default setting in the cstor target to use 6 parallel IO threads.  When I reduce this to single threads, the sequential workloads perform better. 

The Dbench scripts used for running the tests are at:
https://github.com/kmova/openebs/tree/fio-perf-tests/k8s/demo/dbench

**Comment by kmova** [comment]
Refer:  
* https://github.com/openebs/openebs/issues/2413
* https://github.com/openebs/istgt/pull/234
* https://github.com/openebs/maya/pull/993


The QueueDepth and Luworkers can be configured via the StorageClass as follows:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-r1-seq
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "sparse-claim-auto"
      - name: ReplicaCount
        value: "1"
      #- name: TargetNodeSelector
      #  value: |-
      #      "kubernetes.io/hostname": "gke-kmova-helm-default-pool-a169cf59-kxfm"
      - name: Luworkers
        value: "1"
      - name: QueueDepth
        value: "32"
provisioner: openebs.io/provisioner-iscsi
---
```

The new values will be passed an ENV to the target pod. 

`kubectl get pods -n openebs -o yaml pvc-98375585-73a8-11e9-9805-42010
a80015c-target-6657df85f-hh8sj`

```
spec:
  containers:
  - env:
    - name: QueueDepth
      value: "32"
    - name: Luworkers
      value: "1"
    image: quay.io/openebs/cstor-istgt:v0.9.x-ci
```
