### ISSUE TITLE
[Pool Expansion]Adding disks on SPC should expand the existing cStor pool vertically.

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#2394]
## Description
If I attach disks on a node where a cStor pool is already created , and put this disk to disk list in SPC the cStor pool should get expanded.

**Comment by harshshekhar15** [comment]
I have a 3 node GKE cluster having k8s version v1.11.7 and OpenEBS version 0.8.1. I created 3 disks and attached one to each node of the cluster. Then I created a cStor pool using the following SPC yaml 
```
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool
spec:
  disks:
    diskList:
    - sparse-ddace12fb20a68788d3612c15a22364a 
    - sparse-fb05f8c96a6613cc49ec1db77191396b 
  name: cstor-disk-pool
  poolSpec:
    cacheFile: ""
    overProvisioning: false
    poolType: striped
  type: sparse 
```
A cStor striped pool got created. Then I created 3 more disks of same size, and attached one to each node. Then I performed the following steps to attach the disks to the pool :
- Execed into a cStor pool pod and ran the command `zpool add <pool_name> <disk_id>`
