### ISSUE TITLE
[Pool Movement]Attaching the same disk from a old node to a new node should move the volumes.

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#2396]
## Description
I have a cStor pool configured properly on one of the node and for some reason if this node goes bad , I should be able to put these disks on new functional nodes so that my volume also gets migrated successfully.

**Comment by atulabhi** [comment]
**Steps to move the pool to new node** 

Step 1. Attach the disk to the new node.
Step 2. Get the new node name.
Step 3. Edit the CSP and update with the new node name in `kubernetes.io/hostname`.
Step 4. Edit the the cstor deployment which was for that node and update the `nodeSelector` with new node name.

**Comment by kmova** [comment]
I used the following steps to migrate volume replica to a new pool. My pool was created using "auto" mode with maxPools set to 3. 

- Edited the SPC to increase the count to 4. 
- Waited for the new Pool to be created. `kubectl get csp`  showed the new pool. 
  ```
  kubectl get csp
  NAME                     AGE
  cstor-sparse-pool-c56i   16m
  cstor-sparse-pool-f5bn   3m
  cstor-sparse-pool-le1j   17m
  cstor-sparse-pool-p8hn   17m
  ```
- Run `kubectl get csp cstor-sparse-pool-f5bn -o yaml` on new pool and get the pool uuid and hostname: 
  ```
  kubernetes.io/hostname: gke-kmova-helm-default-pool-252c03d1-6g64
  uid: f50701b1-4b3c-11e9-8264-42010a80003a
  ```
- Identify the cvr (volume replica) that needs to move to the new pool.  `kubectl get cvr -n openebs`
  ```
  NAME                                                              AGE
  pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-le1j   15m
  pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-p8hn   15m
  ```
- Assume I want to move `pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-p8hn` from pool `cstor-sparse-pool-p8hn` to `cstor-sparse-pool-f5bn`. 
- Get the YAML file to a temporary location. `kubectl get cvr -n openebs pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-p8hn -o yaml > /tmp/pvc-902875d9-4b3b-11e9-8264-
42010a80003a-cstor-sparse-pool-p8hn.yaml`
- Edit the file to remove auto generated values and fill in the new pool's hostname, uid and name suffix. The new CStorVolumeReplica will look like this:
```
apiVersion: openebs.io/v1alpha1
kind: CStorVolumeReplica
metadata:
  annotations:
    cstorpool.openebs.io/hostname: gke-kmova-helm-default-pool-252c03d1-6g64
  finalizers:
  - cstorvolumereplica.openebs.io/finalizer
  labels:
    cstorpool.openebs.io/name: cstor-sparse-pool-f5bn
    cstorpool.openebs.io/uid: f50701b1-4b3c-11e9-8264-42010a80003a
    cstorvolume.openebs.io/name: pvc-902875d9-4b3b-11e9-8264-42010a80003a
    openebs.io/cas-template-name: cstor-volume-create-default-0.8.1
    openebs.io/persistent-volume: pvc-902875d9-4b3b-11e9-8264-42010a80003a
    openebs.io/version: 0.8.1
  name: pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-f5bn
  namespace: openebs
spec:
  capacity: 4G
  targetIP: 10.47.248.89
status:
  phase: Init
```
  Save the above YAML as `/tmp/pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-f5bn.yaml`
- Delete the old cvr `kubectl delete cvr -n openebs pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-p8hn`
- Create the new cvr `kubectl apply -f /tmp/pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-f5bn.yaml`
- Describe the new cvr to check the status changed to healthy. `kubectl describe cvr -n openebs pvc-902875d9-4b3b-11e9-8264-42010a80003a-cstor-sparse-pool-f5bn`
