### ISSUE TITLE
NDM is not getting deploy in SUSE CaaS Platform

### ISSUE THREAD

**Issue by inyee786** [openebs/openebs#2456]
## Description

-  NDM is not getting deployed in suse caas platform due to security context and 
-  NDM pod is not able to mount on the `var` path
```
  Normal   Pulled                 45s               kubelet, node2  Successfully pulled image "quay.io/openebs/node-disk-manager-amd64:v0.3.1"
  Warning  BackOff                16s               kubelet, node2  Back-off restarting failed container
  Normal   Created                4s (x4 over 45s)  kubelet, node2  Created container
  Warning  Failed                 4s (x4 over 45s)  kubelet, node2  Error: failed to start container "node-disk-manager": Error response from daemon: error while creating mount source path '/var/openebs/sparse': mkdir /var/openebs: read-only file system
```

## Expected Behavior

The NDM pod should be up and running

## Current Behavior

- NDM pod is not coming up

## Steps to Reproduce

Deploy OpenEBS in SUSE cass platform in microOS

## Your Environment

* `kubectl get node -owide`:
```
NAME      STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                 KERNEL-VERSION          CONTAINER-RUNTIME
node1     Ready     master    278d      v1.9.8    <none>        SUSE CaaS Platform 3.0   4.4.132-94.33-default   docker://17.9.1
node2     Ready     <none>    2d        v1.9.8    <none>        SUSE CaaS Platform 3.0   4.4.132-94.33-default   docker://17.9.1
node3     Ready     <none>    2d        v1.9.8    <none>        SUSE CaaS Platform 3.0   4.4.132-94.33-default   docker://17.9.1
node4     Ready     <none>    2d        v1.9.8    <none>        SUSE CaaS Platform 3.0   4.4.132-94.33-default   docker://17.9.1
```
* `kubectl get pods --all-namespaces`:
```
NAMESPACE     NAME                                         READY     STATUS    RESTARTS   AGE
kube-system   dex-7d59778fdb-c42br                         1/1       Running   0          2d
kube-system   dex-7d59778fdb-mnlnd                         1/1       Running   0          2d
kube-system   dex-7d59778fdb-s47c5                         1/1       Running   1          2d
kube-system   haproxy-node1                                1/1       Running   0          2d
kube-system   haproxy-node2                                1/1       Running   0          2d
kube-system   haproxy-node3                                1/1       Running   0          2d
kube-system   haproxy-node4                                1/1       Running   0          2d
kube-system   kube-dns-7488679ff9-5jgc5                    3/3       Running   0          2d
kube-system   kube-dns-7488679ff9-9qh24                    3/3       Running   0          2d
kube-system   kube-dns-7488679ff9-jlhh5                    3/3       Running   0          2d
kube-system   kube-flannel-kk26r                           1/1       Running   0          2d
kube-system   kube-flannel-ljtf5                           1/1       Running   0          2d
kube-system   kube-flannel-rb6hz                           1/1       Running   0          2d
kube-system   kube-flannel-rclwv                           1/1       Running   0          2d
kube-system   tiller-deploy-6bb4bf898f-tzz7m               1/1       Running   0          2d
openebs       maya-apiserver-6f66fb495d-v77rv              1/1       Running   0          4m
openebs       openebs-provisioner-558c597b86-n5jrc         1/1       Running   0          4m
openebs       openebs-snapshot-operator-79fdc5877b-sf2vm   2/2       Running   0          4m
```
* `kubectl get services`:
```
NAMESPACE     NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
default       kubernetes               ClusterIP   172.24.0.1       <none>        443/TCP          278d
kube-system   dex                      NodePort    172.24.79.65     <none>        5556:32000/TCP   2d
kube-system   kube-dns                 ClusterIP   172.24.0.2       <none>        53/UDP,53/TCP    2d
kube-system   tiller                   ClusterIP   172.24.227.139   <none>        44134/TCP        2d
openebs       maya-apiserver-service   ClusterIP   172.24.206.187   <none>        5656/TCP         5m
```

* `kubectl get sc`:
```
NAME                        PROVISIONER                                                AGE
openebs-cstor-sparse        openebs.io/provisioner-iscsi                               5m
openebs-jiva-default        openebs.io/provisioner-iscsi                               5m
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   5m
```
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
``` SUSE CaaS Platform 3.0```
* Kernel (from `uname -a`):
* Install tools:
* Others:

**Comment by inyee786** [comment]
# Solution 

# Run NDM Daemonset as a  PRIVILEGED DAEMONSET 
## method 1:
Add a role in an existing in `ClusterRole` yaml 

```
- apiGroups:
  - extensions
  resourceNames:
  - suse.caasp.psp.privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use  
```
## method 2:
create a separate `clusterrole`, `cluserrolebinding` and `serviceaccount`
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-maya-privileged
  namespace: openebs
---
# Define Role that allows operations on K8s pods/deployments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openebs-maya-privileged
rules:
- apiGroups: ["*"]
  resources: ["nodes", "nodes/proxy"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["namespaces", "services", "pods", "deployments", "events", "endpoints", "configmaps", "jobs"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["storageclasses", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["*"]
- apiGroups: ["volumesnapshot.external-storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotdatas"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: [ "get", "list", "create", "update", "delete"]
- apiGroups: ["*"]
  resources: [ "disks"]
  verbs: ["*" ]
- apiGroups: ["*"]
  resources: [ "storagepoolclaims", "storagepools"]
  verbs: ["*" ]
- apiGroups: ["*"]
  resources: [ "castemplates", "runtasks"]
  verbs: ["*" ]
- apiGroups: ["*"]
  resources: [ "cstorpools", "cstorvolumereplicas", "cstorvolumes"]
  verbs: ["*" ]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
- apiGroups:
  - extensions
  resourceNames:
  - suse.caasp.psp.privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebs-maya-privileged
  namespace: openebs
roleRef:
  kind: ClusterRole
  name: openebs-maya-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: openebs-maya-privileged
    namespace: openebs
---
```
use the service account in NDM Daemonset

ref : https://www.suse.com/documentation/suse-caasp-3/singlehtml/book_caasp_admin/book_caasp_admin.html#ex.admin.security.pod_policies.daemonset
