### ISSUE TITLE
change ReplicaCount in-flight

### ISSUE THREAD

**Issue by elishemer** [openebs/openebs#2488]
hey

I have a storage class using cstor cas-type with ReplicaCount of 1 by default on a one node cluster.
I would like to be able to increase the storage class ReplicaCount by one every time a new node is added to the cluster.
It workes perfectly fine if I re-create the stoageclass and the pvc from scratch - but then i lose all of my data.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-sparse-auto
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "sparse-claim-auto"
      - name: ReplicaCount
        value: "1"
     #- name: TargetResourceLimits
      #  value: |-
      #      memory: 1Gi
      #      cpu: 200m
      #- name: AuxResourceLimits
      #  value: |-
      #      memory: 0.5Gi
      #      cpu: 50m
provisioner: openebs.io/provisioner-iscsi
volumeBindingMode: Immediate
```

I have one PVC bound to this storage class 
```yaml
Name:          cstor-vol1-1r-claim
Namespace:     hexatier
StorageClass:  openebs-cstor-sparse-auto
Status:        Bound
Volume:        pvc-98495aea-564d-11e9-b06d-f29a675bd0f3
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10G
Access Modes:  RWO
VolumeMode:    Filesystem
Events:
  Type       Reason                 Age                    From                                                                                                    Message
  ----       ------                 ----                   ----                                                                                                    -------
  Normal     ExternalProvisioning   8m46s (x2 over 8m46s)  persistentvolume-controller                                                                             waiting for a volume to be created, either by external provisioner "openebs.io/provisioner-iscsi" or manually created by system administrator
  Normal     Provisioning           8m46s                  openebs.io/provisioner-iscsi_openebs-provisioner-55d85c546d-n655n_19d5fed8-5552-11e9-9549-92772ec41aa2  External provisioner is provisioning volume for claim "hexatier/cstor-vol1-1r-claim"
  Normal     ProvisioningSucceeded  8m45s                  openebs.io/provisioner-iscsi_openebs-provisioner-55d85c546d-n655n_19d5fed8-5552-11e9-9549-92772ec41aa2  Successfully provisioned volume pvc-98495aea-564d-11e9-b06d-f29a675bd0f3
```

The reclaimPolicy is set to delete, assuming that the retain policy is not officially supported yet?

what  options do i have?
1. retainPolicy of retain is doable in some way?
2. should i use snapshots?
3. should i resort to some manual process of backing up the data on the host machine?
4. feel free to add more options

thanks

PS - this is my SPC
```yaml
Name:         sparse-claim-auto
Namespace:    
Labels:       <none>
Annotations:  openebs.io/spc-lease: {"holder":"","leaderTransition":122}
API Version:  openebs.io/v1alpha1
Kind:         StoragePoolClaim
Metadata:
  Creation Timestamp:  2019-04-03T19:32:14Z
  Generation:          3
  Resource Version:    257310
  Self Link:           /apis/openebs.io/v1alpha1/storagepoolclaims/sparse-claim-auto
  UID:                 2edee0dc-5647-11e9-b06d-f29a675bd0f3
Spec:
  Capacity:  
  Disks:
    Disk List:    <nil>
  Format:         
  Max Pools:      5
  Min Pools:      1
  Mountpoint:     
  Name:           sparse-claim-auto
  Node Selector:  <nil>
  Path:           
  Pool Spec:
    Cache File:         /var/openebs/sparse/sparse-claim-auto.cache
    Over Provisioning:  false
    Pool Type:          striped
  Type:                 sparse
Status:
  Phase:  Online
Events:   <none>
```
