### ISSUE TITLE
Add a custom resource JivaVolume for managing jiva related resources

### ISSUE THREAD

**Issue by utkarshmani1997** [openebs/openebs#2523]
## Description

We are finding the need of custom resource JivaVolume for managing jiva resources for various CRUD operations.Here is the schema of JivaVolume:
```
kind: JivaVolume
metadata:
  namespace: # openebs system namespace
  name: pv-name # can be pv name or anything
  annotations:
  labels:
    openebs.io/match-name: # can be pv name if metadata.name != pv name
spec:
  capacity:
  casType:
  fsType:
  lun:
iscsi:
  iqn:
  targetPortal:
config: # common config applicable to service, target & replica
  envs:
  labels:
    openebs.io/match-name: # can be pv name if metadata.name != pv name
  annotations:
service:
  config: # service specific config; can override common config
  name: pv-name # can be pv name or anything 
  generateName: pv-name # can be pv name or anything
target:
  config: # target specific config; can override common config
  name: pv-name # can be pv name or anything;
  generateName: pv-name # can be pv name or anything;
replica:
  config: # replica specific config; can override common config
  name: pv-name # can be pv name or anything;
  generateName: pv-name # can be pv name or anything
status:
```
## Context

Having a CR for jiva will be helpful for various GET, PUT, POST, DELETE, PATCH operations on jiva resources.

Ref: https://github.com/AmitKumarDas/Decisions/blob/master/blogs/jiva_volume_as_custom_resource.md
cc: @AmitKumarDas
