### ISSUE TITLE
add label to persistent volume(s) created by openebs local-pv provisioner

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#2567]
### Why is this required
This helps to identify/bookmark Kubernetes PersistentVolume(s) created by openebs local-pv provisioner from volumes created via other provisioners.

### Possible Solution
The PersistentVolume can have following label to achieve above objective

```yaml
kind: PersistentVolume
metadata:
  name: openebs-local-vol
  labels:
    openebs.io/castype: local
```

### Mentors
- @kmova
