### ISSUE TITLE
Add HA support in openebs-k8s-provisioner

### ISSUE THREAD

**Issue by satyamz** [openebs/openebs#267]
`openebs-provisioner` POD should be available all the time and should never go down. We need High Availability support for `openebs-k8s-provisioner`.

**Comment by satyamz** [comment]
For high-availability, we want to make sure there are at least 2 replicas of the provisioner pod running on 2 separate nodes. That way if one node goes offline (taking 1 pod with it), provisioner is still accessible.
We can handle this case by adding `affinity` -> `podAntiAffinity`. Anti-affinity to make sure that two of the same provisioner pods are not scheduled on the same node. This is the one case I could think of, what else do we want in HA?

**Comment by satyamz** [comment]
Also, to test the changes simply we can use below `test-pvc.yaml`
```yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vut
spec:
  storageClassName: openebs-basic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
```

**Comment by satyamz** [comment]
I got the following output for `replicas: 2` of  `openebes-provisioner` in `openebs-operator.yaml` 
```
ubuntu@kubemaster-01:~/openebs/k8s$ kubectl get pods 
NAME                                                             READY     STATUS    RESTARTS   AGE
maya-apiserver-1089964587-t3c54                                  1/1       Running   0          37m
openebs-provisioner-1149663462-h1dn5                             1/1       Running   0          37m
openebs-provisioner-1149663462-rbwb9                             1/1       Running   0          37m
pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d-ctrl-2102192375-n4ndt   1/1       Running   0          14m
pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d-rep-1247715899-2pgg4    1/1       Running   0          14m
pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d-rep-1247715899-x7h32    1/1       Running   0          14m

ubuntu@kubemaster-01:~/openebs/k8s$ kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM         STORAGECLASS    REASON    AGE
pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d   5G         RWO           Delete          Bound     default/bar   openebs-basic             14m


ubuntu@kubemaster-01:~/openebs/k8s$ kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS    AGE
bar       Bound     pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d   5G         RWO           openebs-basic   14m


ubuntu@kubemaster-01:~/openebs/k8s$ kubectl get rs
NAME                                                       DESIRED   CURRENT   READY     AGE
maya-apiserver-1089964587                                  1         1         1         38m
openebs-provisioner-1149663462                             2         2         2         38m
pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d-ctrl-2102192375   1         1         1         14m
pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d-rep-1247715899    2         2         2         14m

ubuntu@kubemaster-01:~/openebs/k8s$ kubectl get svc
NAME                                                CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
kubernetes                                          10.96.0.1        <none>        443/TCP             2h
maya-apiserver-service                              10.111.104.8     <none>        5656/TCP            39m
pvc-119b3fdf-a9b0-11e7-8d34-021c6f7dbe9d-ctrl-svc   10.100.249.161   <none>        3260/TCP,9501/TCP   15m


```

**Comment by kmova** [comment]
@satyamz -- this is good. can we find out what happens.. when multiple PVCs are created. probably you can use the maya volume create (command in loop) and while the volumes are getting created, kill one of the replica or both the replicas..

**Comment by satyamz** [comment]
@kmova sure! I will try this out. Today, I experienced one more thing. In that, `openebs-provisioner` replicas were scheduled on `kubeminion-02`, then I killed  `kubeminion-02` node bby `vagrant halt  kubeminion-02` In this case, other replicas of `openebs-provisioner` tried to come up but failed eventually, 
This is the example output of this: 
```
ubuntu@kubemaster-01:~$ kubectl describe pods openebs-provisioner-1149663462-j05bx
Name:		openebs-provisioner-1149663462-j05bx
Namespace:	default
Node:		/
Labels:		name=openebs-provisioner
		pod-template-hash=1149663462
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"openebs-provisioner-1149663462","uid":"36b6a765-a9c3-11e7-beb8-0...
Status:		Pending
IP:		
Controllers:	ReplicaSet/openebs-provisioner-1149663462
Containers:
  openebs-provisioner:
    Image:	openebs/openebs-k8s-provisioner:0.4.0
    Port:	
    Environment:
      NODE_NAME:	 (v1:spec.nodeName)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from openebs-maya-operator-token-tllf7 (ro)
Conditions:
  Type		Status
  PodScheduled 	False 
Volumes:
  openebs-maya-operator-token-tllf7:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	openebs-maya-operator-token-tllf7
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  6m		10s		28	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: PodToleratesNodeTaints (1).

```

I found the work around for this problem too. We need to set `affinity` for `openebs-provisioner` deployment so that replicas will be alive even if any node goes down. Let me know if I'm heading towards wrong direction or something.

**Comment by satyamz** [comment]
To achieve the **High Availability** for `openebs-provisioner` 
We need to label nodes to assign the pods on those. 

To do that execute: 
```
kubectl label nodes kubeminion-01  node=minion01  # For node kubeminion-01
kubectl label nodes kubeminion-02  node=minion02   # For node kubeminion-02
```
Once, we labeled the nodes we can specify these labels in the  `openebs-provisioner` spec in `openebs-operator.yaml`

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openebs-provisioner
  namespace: default
spec:
  replicas: 8
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              matchExpressions:
                key: node
                operator: Equal
                values: ["minion01","minion02" ]
  template:
    metadata:
      labels:
        name: openebs-provisioner
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: openebs-provisioner
        imagePullPolicy: Always
        image: openebs/openebs-k8s-provisioner:0.4.0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

```
After this, kubernetes scheduler will take care of assigning pods to the specific nodes and it will make sure that pods are always available on specified nodes.
