### ISSUE TITLE
Ability to provide PV as a list to the m-upgrade job with "--pv-name" param

### ISSUE THREAD

**Issue by zzzuzik** [openebs/openebs#2701]
The current upgrade flow requires creation of individual jobs for all PVs:
https://github.com/openebs/openebs/tree/master/k8s/upgrades/1.0.0-1.1.0
It would save considerable amount of time if a list of PVs (from output of `kubectl get pv`) could be provided to the `--pv-name` param

**Comment by AmitKumarDas** [comment]
@zzzuzik This will be taken up in upcoming releases.
cc @shubham14bajpai

**Comment by zzzuzik** [comment]
@AmitKumarDas thank you

**Comment by zzzuzik** [comment]
@AmitKumarDas @shubham14bajpai was it implemented in 1.3?

**Comment by zzzuzik** [comment]
Unstale

**Comment by zzzuzik** [comment]
The bot is very picky on me :(

**Comment by AmitKumarDas** [comment]
@shubham14bajpai @sagarkrsd can you please comment if this has been solved? I guess openebs upgrades have become a one click process.

**Comment by sagarkrsd** [comment]
@zzzuzik How about using [OpenEBS Director](https://account.mayadata.io/login) for this use-case. OpenEBS upgrade is now a single-click process using OpenEBS Director.
Please take a look at this blog https://blog.mayadata.io/openebs/single-click-openebs-upgrade and provide your valuable feedback.

**Comment by zzzuzik** [comment]
@sagarkrsd sounds great. Could you please point me to the On-Prem installation info.

**Comment by sagarkrsd** [comment]
Here you go @zzzuzik , instructions for Director On Prem installation
https://help.mayadata.io/hc/en-us/articles/360033029692-Getting-started-with-Director-OnPrem

**Comment by kmova** [comment]
@sagarkrsd @AmitKumarDas  -- would it be possible to execute the multiple upgrade job without having to install the full director.

**Comment by zzzuzik** [comment]
@kmova +1
I failed to get Director running On-Prem, there is a good list of dependencies that are deployed and the are don't work right out the box

**Comment by avishnu** [comment]
@zzzuzik Hope you are able to get things working as per your expectations. Regarding Director, I'd like to mention few points:

1. Director comes in 2 flavors today - an Online SaaS and an On-prem flavor.
2. In DirectorOnline SaaS, you get almost all features that you are looking for, like monitoring OpenEBS volumes, upgrading OpenEBS pools and volumes, installing OpenEBS itself on a fresh K8s cluster (and a lot others) for free. You just need to follow the steps in https://director.mayadata.io and connect your K8s clusters. For most of your needs, this should suffice.
3. If you or your organization has restrictions in sending data outside your firewall, you can set-up the On-prem flavor of Director. I understand that you failed to get this running. I and my team will be glad to help you out if you give us the opportunity.
Thanks in advance.

**Comment by kmova** [comment]
The upgrade job spec allows for specifying a variable number of volume names as the last parameter as follows:
```
    spec:
      # VERIFY the value of serviceAccountName is pointing to service account
      # created within openebs namespace. Use the non-default account.
      # by running `kubectl get sa -n <openebs-namespace>`
      serviceAccountName: openebs-maya-operator
      containers:
      - name:  upgrade
        args:
        - "jiva-volume"
        # --from-version is the current version of the volume
        - "--from-version=1.6.0"
        # --to-version is the version desired upgrade version
        - "--to-version=1.9.0"
        #List of valid Jiva Peristent Volume names. 
        - "pvc-713e3bb6-afd2-11e9-8e79-42010a800065"
        - "pvc-02320288-22c8-44d4-b5a1-fc37acf2c597"
 ``` 

The upgrade job will sequentially execute the upgrade for each of the volumes specified in the spec.
