### ISSUE TITLE
BDD test for verifying defaulting of pool type in CSPC

### ISSUE THREAD

**Issue by sonasingh46** [openebs/openebs#2786]
## Description
While creating a CSPC, we can specify the raid configuration for the cStor pool that we want to create. 
A single cStor pool can be a combination of one or more raid groups and each raid group has a field `type` that specifies what kind of raid configuration it should be.
Additionally, there is a way to put `defaultRaidGroupType` in CSPC config so that we do not need to repeatedly mention `type` at raid groups which can possibly have the same type.
A BDD test can be written to verify this.
See the following section to get more context.

## Context
```yaml
apiVersion: openebs.io/v1alpha1
kind: CStorPoolCluster
metadata:
  name: cspc-stripe
  namespace: openebs
spec:
  pools:
  - nodeSelector:
      kubernetes.io/hostname: "gke-cstor-demo-default-pool-3385ab41-hrmr"
    raidGroups:
    - type: "stripe"
      isWriteCache: false
      isSpare: false
      isReadCache: false
      blockDevices:
      - blockDeviceName: "blockdevice-474d20376a541a8fb372d44f5bc361ea"
    poolConfig:
      cacheFile: ""
      defaultRaidGroupType: "stripe"
      overProvisioning: false
      compression: "off"
```
As you can see in the spec -- if  `defaultRaidGroupType` is specified then `type: "stripe"` at `spec.pools[0].raidGroups[0].type` can be left empty and the pool type will be taken as `stripe`.

The following can be verified via BDD tests: 
1. Both fields can not be left empty simultaneously.
2. If both fields are specified then one at the `spec.pools[0].raidGroups[0].type` level is given priority. 
3.  If  `defaultRaidGroupType` is specified and `spec.pools[0].raidGroups[0].type` is left empty and the pool type will be taken as what is specified at `defaultRaidGroupType` .

## References
See the following link for sample BDD tests:
https://github.com/openebs/maya/tree/master/tests/cstor/cspc/positive/provisioning

See the following design document to learn more: 
https://github.com/openebs/openebs/blob/master/contribute/design/1.x/cstor-operator/doc.md
