### ISSUE TITLE
wrong FSType when create pvc base on snapshot 

### ISSUE THREAD

**Issue by EvanPrivate** [openebs/openebs#2809]
## Description

I create a snapshot at a pvc(xfs format) ,like this
```
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-demo-vol1-nginx-0
  namespace: default
spec:
  persistentVolumeClaimName: demo-vol1-nginx-0

```
and create a pv from the snapshot
```

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cstor-snapshot-test-pvc
  namespace: default
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-demo-vol1-nginx-0
spec:
  storageClassName: openebs-snapshot-promoter
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
```

describe snapshot's pvc 

```
Name:          cstor-snapshot-test-pvc
Namespace:     default
StorageClass:  openebs-snapshot-promoter
Status:        Bound
Volume:        pvc-5e246226-6c5f-477a-b23c-115d781e160e
Labels:        <none>
Annotations:   cas.openebs.io/config:
                 - name: FSType
                   value: "xfs"
               kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"cas.openebs.io/config":"- name: FSType\n  value: \"xfs\"\n",...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               snapshot.alpha.kubernetes.io/snapshot: snapshot-demo-vol1-nginx-0
               volume.beta.kubernetes.io/storage-provisioner: volumesnapshot.external-storage.k8s.io/snapshot-promoter
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    <none>
Events:        <none>
```
describe snapshot's pv
```
Name:            pvc-5e246226-6c5f-477a-b23c-115d781e160e
Labels:          openebs.io/cas-type=cstor
                 openebs.io/storageclass=openebs-cstor-disk
Annotations:     pv.kubernetes.io/provisioned-by: volumesnapshot.external-storage.k8s.io/snapshot-promoter
                 snapshotProvisionerIdentity: volumesnapshot.external-storage.k8s.io/snapshot-promoter
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    openebs-snapshot-promoter
Status:          Bound
Claim:           default/cstor-snapshot-test-pvc
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         
Source:
    Type:               ISCSI (an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod)
    TargetPortal:       10.254.120.171:3260
    IQN:                iqn.2016-09.com.openebs.cstor:pvc-5e246226-6c5f-477a-b23c-115d781e160e
    Lun:                0
    ISCSIInterface      default
    FSType:             ext4
    ReadOnly:           false
    Portals:            []
    DiscoveryCHAPAuth:  false
    SessionCHAPAuth:    false
    SecretRef:          nil
    InitiatorName:      <none>
Events:                 <none>
```

describe source pvc

```
Name:          demo-vol1-nginx-0
Namespace:     default
StorageClass:  openebs-cstor-disk
Status:        Bound
Volume:        pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3
Labels:        app=nginx
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    nginx-0
Events:        <none>

```

describe source pv
```
Name:            pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3
Labels:          openebs.io/cas-type=cstor
                 openebs.io/storageclass=openebs-cstor-disk
Annotations:     openEBSProvisionerIdentity: rancher-111
                 openebs.io/cas-type: cstor
                 pv.kubernetes.io/provisioned-by: openebs.io/provisioner-iscsi
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    openebs-cstor-disk
Status:          Bound
Claim:           default/demo-vol1-nginx-0
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         
Source:
    Type:               ISCSI (an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod)
    TargetPortal:       10.254.22.134:3260
    IQN:                iqn.2016-09.com.openebs.cstor:pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3
    Lun:                0
    ISCSIInterface      default
    FSType:             xfs
    ReadOnly:           false
    Portals:            []
    DiscoveryCHAPAuth:  false
    SessionCHAPAuth:    false
    SecretRef:          nil
    InitiatorName:      <none>
Events:                 <none>

```

I try add this config to openebs-snapshot-promoter storageclass but not work
```
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: FSType
        value: "xfs"

```

## Expected Behavior

the pv should be xfs ,same as the source pv (xfs)

## Current Behavior

it is ext4

## Steps to Reproduce

install
`kubectl apply -f https://openebs.github.io/charts/openebs-operator-1.3.0.yaml
`

kubectl get pods -n openebs 
```
NAME                                                              READY   STATUS    RESTARTS   AGE
cstor-disk-pool-19zn-5b999dbf6-7f72k                              3/3     Running   0          20h
cstor-disk-pool-x7ip-5b668b4b47-hp7wd                             3/3     Running   0          20h
maya-apiserver-7bf94588c-d5rcg                                    1/1     Running   0          20h
openebs-admission-server-7bc49854bb-8mzls                         1/1     Running   2          45h
openebs-localpv-provisioner-8657cdcd6f-fxqbs                      1/1     Running   4          45h
openebs-ndm-operator-74b4fb6fcd-krzrx                             1/1     Running   3          45h
openebs-ndm-rsz7m                                                 1/1     Running   1          45h
openebs-ndm-z4mmd                                                 1/1     Running   2          45h
openebs-provisioner-7c47c68bcb-qggmq                              1/1     Running   0          17h
openebs-snapshot-operator-78fb65cf5f-sq7pm                        2/2     Running   0          17h
pvc-47190b30-d8cf-43da-b5c3-8923d7b7e0cf-target-84ff8f7c47hvc9t   3/3     Running   2          20h
pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3-target-5cd8f957cdx7ngz   3/3     Running   2          20h
pvc-5e246226-6c5f-477a-b23c-115d781e160e-target-5b6bb455cbxw5ht   3/3     Running   2          17h
```

create StoragePoolClaim and StorageClass
```
cat >cstor.yaml<<EOF
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 1Gi
      - name: PoolResourceLimits
        value: |-
            memory: 2Gi
spec:
  name: cstor-disk-pool
  type: disk
  poolSpec:
    poolType: mirrored
  blockDevices:
    blockDeviceList:
    - blockdevice-25185bf3919901ea4a20acc6670dd348
    - blockdevice-2cf3f20616b9e90375eff7273ba114b3
    - blockdevice-6f3708725f38ba5408847c6c21ef0148
    - blockdevice-e4d60378d5ddbc0cd26c937cc6438fe7
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-disk
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk-pool"
      - name: FSType
        value: xfs
      - name: ReplicaCount
        value: "2"
      - name: VolumeMonitor
        enabled: "true"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
EOF
kubectl apply -f cstor.yaml

```

create the StatefulSet

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  serviceName: nginx
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.9
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: /mnt
            name: demo-vol1
  volumeClaimTemplates:
  - metadata:
      name: demo-vol1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: openebs-cstor-disk
      resources:
        requests:
          storage: 2Gi
```

kubectl get pvc

```
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
demo-vol1-nginx-0         Bound    pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3   2Gi        RWO            openebs-cstor-disk          20h
demo-vol1-nginx-1         Bound    pvc-47190b30-d8cf-43da-b5c3-8923d7b7e0cf   2Gi        RWO            openebs-cstor-disk          20h

```

kubectl get pv
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                             STORAGECLASS                REASON   AGE
pvc-47190b30-d8cf-43da-b5c3-8923d7b7e0cf   2Gi        RWO            Delete           Bound    default/demo-vol1-nginx-1         openebs-cstor-disk                   20h
pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3   2Gi        RWO            Delete           Bound    default/demo-vol1-nginx-0         openebs-cstor-disk                   20h

```

create the snapshot 
```
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-demo-vol1-nginx-0
  namespace: default
spec:
  persistentVolumeClaimName: demo-vol1-nginx-0
```

kubectl describe volumesnapshot
```
Name:         snapshot-demo-vol1-nginx-0
Namespace:    default
Labels:       SnapshotMetadata-PVName=pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3
              SnapshotMetadata-Timestamp=1571817880751765687
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"volumesnapshot.external-storage.k8s.io/v1","kind":"VolumeSnapshot","metadata":{"annotations":{},"name":"snapshot-demo-vol1-...
API Version:  volumesnapshot.external-storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2019-10-23T08:04:07Z
  Generation:          3
  Resource Version:    323619
  Self Link:           /apis/volumesnapshot.external-storage.k8s.io/v1/namespaces/default/volumesnapshots/snapshot-demo-vol1-nginx-0
  UID:                 85273eb2-7f95-4c56-bc7a-51d0957c6598
Spec:
  Persistent Volume Claim Name:  demo-vol1-nginx-0
  Snapshot Data Name:            k8s-volume-snapshot-c4782bef-f56b-11e9-9745-6adeb776917b
Status:
  Conditions:
    Last Transition Time:  2019-10-23T08:04:41Z
    Message:               Snapshot created successfully
    Reason:                
    Status:                True
    Type:                  Ready
  Creation Timestamp:      <nil>
Events:                    <none>

```

kubectl describe volumesnapshotdata
```
Name:         k8s-volume-snapshot-c4782bef-f56b-11e9-9745-6adeb776917b
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  volumesnapshot.external-storage.k8s.io/v1
Kind:         VolumeSnapshotData
Metadata:
  Creation Timestamp:  2019-10-23T08:04:41Z
  Generation:          1
  Resource Version:    323618
  Self Link:           /apis/volumesnapshot.external-storage.k8s.io/v1/volumesnapshotdatas/k8s-volume-snapshot-c4782bef-f56b-11e9-9745-6adeb776917b
  UID:                 4b002d1d-2dc3-402c-9b22-0d5cc0b2c45e
Spec:
  Openebs Volume:
    Capacity:     2Gi
    Snapshot Id:  pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3_snapshot-demo-vol1-nginx-0_1571817880761357602
  Persistent Volume Ref:
    Kind:  PersistentVolume
    Name:  pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3
  Volume Snapshot Ref:
    Kind:  VolumeSnapshot
    Name:  default/snapshot-demo-vol1-nginx-0-85273eb2-7f95-4c56-bc7a-51d0957c6598
Status:
  Conditions:
    Last Transition Time:  2019-10-23T08:04:41Z
    Message:               Snapshot created successfully
    Reason:                
    Status:                True
    Type:                  Ready
  Creation Timestamp:      <nil>
Events:                    <none>
```

create the snapshot pvc
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cstor-snapshot-test-pvc
  namespace: default
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-demo-vol1-nginx-0
spec:
  storageClassName: openebs-snapshot-promoter
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
```

describe source pv
```
Name:            pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3
Labels:          openebs.io/cas-type=cstor
                 openebs.io/storageclass=openebs-cstor-disk
Annotations:     openEBSProvisionerIdentity: rancher-111
                 openebs.io/cas-type: cstor
                 pv.kubernetes.io/provisioned-by: openebs.io/provisioner-iscsi
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    openebs-cstor-disk
Status:          Bound
Claim:           default/demo-vol1-nginx-0
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         
Source:
    Type:               ISCSI (an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod)
    TargetPortal:       10.254.22.134:3260
    IQN:                iqn.2016-09.com.openebs.cstor:pvc-5b962f83-eeca-47a4-b7cd-3e1a965fbab3
    Lun:                0
    ISCSIInterface      default
    FSType:             xfs
    ReadOnly:           false
    Portals:            []
    DiscoveryCHAPAuth:  false
    SessionCHAPAuth:    false
    SecretRef:          nil
    InitiatorName:      <none>
Events:                 <none>
```

describe snapshot pv
```
Name:            pvc-5e246226-6c5f-477a-b23c-115d781e160e
Labels:          openebs.io/cas-type=cstor
                 openebs.io/storageclass=openebs-cstor-disk
Annotations:     pv.kubernetes.io/provisioned-by: volumesnapshot.external-storage.k8s.io/snapshot-promoter
                 snapshotProvisionerIdentity: volumesnapshot.external-storage.k8s.io/snapshot-promoter
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    openebs-snapshot-promoter
Status:          Bound
Claim:           default/cstor-snapshot-test-pvc
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:         
Source:
    Type:               ISCSI (an ISCSI Disk resource that is attached to a kubelet's host machine and then exposed to the pod)
    TargetPortal:       10.254.120.171:3260
    IQN:                iqn.2016-09.com.openebs.cstor:pvc-5e246226-6c5f-477a-b23c-115d781e160e
    Lun:                0
    ISCSIInterface      default
    FSType:             ext4
    ReadOnly:           false
    Portals:            []
    DiscoveryCHAPAuth:  false
    SessionCHAPAuth:    false
    SecretRef:          nil
    InitiatorName:      <none>
Events:                 <none>

```
