### ISSUE TITLE
Enforcing storage requests fro localpv engine feature milestone

### ISSUE THREAD

**Issue by bbkgh** [openebs/openebs#2871]
Hi,
I found (in docs) that enforcing storage capacity for localpv has been planned to be done in future but i can't any trace of it in milestones. Is this feature planned to be done in near future?
Thanks

**Comment by kmova** [comment]
It is being tracked under a card. https://github.com/openebs/openebs/projects/6.  Thanks for raising this issue, will use this issue to track. For the hostpath and device Local PV, a prototype is being developed for 1.6 that is going to use a liveness check on the pod to enforce the capacity. The plan to get a mutation admission hook, that will setup the liveness check. 

Btw, would using ZFS Local PV an option for your usecase? https://github.com/openebs/zfs-localpv

**Comment by ranjithwingrider** [comment]
I have added a liveness probe to my application YAML to fail the pod when it reaches the limit.  Following are the details and step to validate the test case...
Test application is `busybox` with 2G capacity and taken 90% of the capacity as the limit.

```
       livenessProbe:
         exec:
           command:
           - "/bin/sh"
           - "-c"
           - test ! "$(du -sk /var/lib/mysql | awk '{print int(($1*100)/2097152)}')" -gt 90
``` 
Example YAML:
```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: busybox
 labels:
   app: busybox
spec:
 replicas: 1
 strategy:
   type: RollingUpdate
 selector:
   matchLabels:
     app: busybox
 template:
   metadata:
     labels:
       app: busybox
   spec:
     containers:
     - resources:
          limits:
           cpu: 0.5
       name: busybox
       image: busybox
       command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
       imagePullPolicy: IfNotPresent
       ports:
        - containerPort: 3306
          name: busybox
       volumeMounts:
       - mountPath: /var/lib/mysql
         name: demo-vol1
       livenessProbe:
         exec:
           command:
           - "/bin/sh"
           - "-c"
           - test ! "$(du -sk /var/lib/mysql | awk '{print int(($1*100)/2097152)}')" -gt 90
         initialDelaySeconds: 5
         periodSeconds: 5
     volumes:
     - name: demo-vol1
       persistentVolumeClaim:
        claimName: demo-vol1-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: demo-vol1-claim
spec:
 storageClassName: openebs-hostpath-custom
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 2G
---
apiVersion: v1
kind: Service
metadata:
 name: busybox-mysql
 labels:
   name: busybox-mysql
spec:
 ports:
   - port: 3306
     targetPort: 3306
 selector:
     name: busybox
```
Custom StorageClass for LocalPV
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath-custom
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: BasePath
        value: "/home/ranjith_raveendran/ranjith-localpv"
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete                   
```
Disk mout status on Node:
```
root@gke-ranjith-localpv-default-pool-5f0ec958-lgd0:~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0   40G  0 disk 
├─sda1    8:1    0 39.9G  0 part /
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sdb       8:16   0   50G  0 disk /home/ranjith_raveendran/ranjith-localpv
```
Run following command inside the application container (/var/lib/mysql/)
```
dd if=/dev/urandom of=test.out bs=1M count=1920
```

**Comment by kmova** [comment]
Thanks @ranjithwingrider, Can you also provide an example of setting up a busybox side car with the liveness check.

**Comment by ranjithwingrider** [comment]
Please find the updated application YAMl spec wiith sidecar implementation...

```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: busybox
 labels:
   app: busybox
spec:
 replicas: 1
 strategy:
   type: RollingUpdate
 selector:
   matchLabels:
     app: busybox
 template:
   metadata:
     labels:
       app: busybox
   spec:
     containers:
     - resources:
          limits:
           cpu: 0.5
       name: busybox
       image: busybox
       command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
       imagePullPolicy: IfNotPresent
       ports:
        - containerPort: 3306
          name: busybox
       volumeMounts:
       - mountPath: /var/lib/mysql
         name: demo-vol1
     - name: sidecar-container
       image: alpine
       imagePullPolicy: IfNotPresent
       command: ['sh', '-c', 'echo Side carContainer is Running ; sleep 3600']
       volumeMounts:
       - mountPath: /var/lib/mysql
         name: demo-vol1
       livenessProbe:
         exec:
           command:
           - "/bin/sh"
           - "-c"
           - test ! "$(du -sk /var/lib/mysql | awk '{print int(($1*100)/2097152)}')" -gt 90
         failureThreshold: 3
         initialDelaySeconds: 2
         periodSeconds: 5
     volumes:
     - name: demo-vol1
       persistentVolumeClaim:
        claimName: demo-vol1-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: demo-vol1-claim
spec:
 storageClassName: openebs-hostpath-custom
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 2G
---
apiVersion: v1
kind: Service
metadata:
 name: busybox-mysql
 labels:
   name: busybox-mysql
spec:
 ports:
   - port: 3306
     targetPort: 3306
 selector:
     name: busybox
```

**Comment by ranjithwingrider** [comment]
A snippet of side car implementation for Local PV size restriction for example busybox
```
     - name: sidecar-container
       image: alpine
       imagePullPolicy: IfNotPresent
       command: ['sh', '-c', 'echo Side carContainer is Running ; sleep 3600']
       volumeMounts:
       - mountPath: /var/lib/mysql
         name: demo-vol1
       livenessProbe:
         exec:
           command:
           - "/bin/sh"
           - "-c"
           - test ! "$(du -sk /var/lib/mysql | awk '{print int(($1*100)/2097152)}')" -gt 90
         failureThreshold: 3
         initialDelaySeconds: 2
         periodSeconds: 5
```
