### ISSUE TITLE
add label selector on HostPath

### ISSUE THREAD

**Issue by obeyler** [openebs/openebs#2875]
## Description
Node names in cloud environments are not always predictable or stable. 
so on it should not be used as nodeselector in HostPath (LocalPv) 

Add the opportunity  to specify on the host path storage class a config parameter to say that the node selector is not based on the node name but base on one or more specific label. 
by example : nodeSelectorBaseOnLabel="boshId","AZ"

in this case in PV will have the a nodeSelector like classical localHost see https://kubernetes.io/docs/concepts/storage/volumes/#local

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
...
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: boshId
          operator: In
          values:
          - 34xxc-jkjkjk
      - matchExpressions:
        - key: AZ
          operator: In
          values:
          - Z1

```
## Context
When I use HostPath a LocalPV as storageclass, I see that the PVC requiere that the PV are located on a specific node by using a node selector. It's normal that the PV is attached to the Node. Currently the node selector is based on the node name. 
On openstack by example the node name is define by the iaas. The node name is the vm id  and can not be override by arg hostname-override see https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#node-name-4
On Other iaas the behavior can be different see https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#node-name-2

**Comment by obeyler** [comment]
may you can be inspired by what have been done by @kmova in this https://github.com/openebs/maya/commit/65a1b8efd5bf16e73717eab90352a70f962b5eb9
but with more flexibility about the choice of label

**Comment by obeyler** [comment]
I ask the opportunity to put more than one label because when we use more than one AZ the bosh Id can be the same on different AZ  (if you are really really not lucky :-) ).

**Comment by obeyler** [comment]
May the same pb will occured on project zfs-localpv

**Comment by kmova** [comment]
Hi @rajibmitra thanks for taking this up. You can reach out, discuss and seek help with other developers under the slack.openebs.io #contributors channel.

**Comment by kmova** [comment]
The feature request can be supported by refactoring the Local Provisioner code as follows: 
* Remove the assumption that there is only one nodeSelector Label (`kubernetes.io/hostname`) on the PV. The change needs to happen in the helper job pods and PV spec. 
* Support an annotation called `UniqueNodeSelectionLabels` which can be a comma-separated list of node labels. If this parameter is not specified, assume the default value of `kubernetes.io/hostname`.
* While this issue has been raised on the hostpath, it will be better to extend the support to other provisioners as well like Local PV (device), Local PV (zfs), cStor and so forth.

**Comment by akhilerm** [comment]
@kmova  Are there any updates on this issue?

**Comment by kmova** [comment]
With 2.4.0, OpenEBS Local Hostpath storage class can specify a custom node affinity label like (openebs.io/custom-node-id) as follows:

```
kind: StorageClass
metadata:
  name: openebs-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: NodeAffinityLabel
        value: "openebs.io/custom-node-id"
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```
