### ISSUE TITLE
Unable to provision a volume with replicaCount as 0 in storageclass

### ISSUE THREAD

**Issue by mittachaitu** [openebs/openebs#2974]
## Description

Provisioned a cStor volume by specifying replica count as **0** in storage class configurations PVC created successfully and it remains pending state.

## Expected Behavior

PVC creation should error out when trying to provision with the wrong configuration.

## Current Behavior

PVC created successfully without any errors but failed to get PV(volume).

## Possible Solution

Throwing a proper error message in front of the user when the user applied with wrong configurations.

## Steps to Reproduce

- Apply below storage class:
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: single-sc
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-sparse-pool"
      - name: ReplicaCount
        value: "0"
  labels:
    sc-name: single-sc
provisioner: openebs.io/provisioner-iscsi
allowVolumeExpansion: true
```
- Apply PVC yaml
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
  labels:
    name: demo-vol1-claim
spec:
  storageClassName: single-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
```
- Get the PVC to verify bound status
```yaml
kubectl get pvc
NAME              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
demo-vol1-claim   Pending                                      single-sc      9m53s
```
- Describe of PVC throwing some long error:
[pvc_describe.txt](https://github.com/openebs/openebs/files/4367909/pvc_describe.txt)

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`: 
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:
