### ISSUE TITLE
cstor-pool container unable to start due to libjson-c.so.2

### ISSUE THREAD

**Issue by xUnholy** [openebs/openebs#3037]
# Description

I got some strange errors about the libjson library. Apologies if this is in the wrong repository.

❯ k logs cstor-sparse-pool-w39i-65b4d88bbf-f4mzd cstor-pool
Disabling dumping core
sleeping for 2 sec
/usr/local/bin/zrepl: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory

**Environment:**
- OpenEBS version: 1.9.0 (Also tried using 1.10.x.RC2)
- Kubernetes version: 1.18.x
- OS: Ubuntu 20.04 Focal
- Hardware: Raspberry Pi 4B

**Comment by kmova** [comment]
Hi @xUnholy -- this is the right repository. Thanks for reporting this issue. I don't think we tried to test with Ubuntu 20.04 out yet. 

@mynktl - may need some further information to debug this issue.

**Comment by xUnholy** [comment]
@mynktl all my other pods are starting as per normal.

I'm deploying with the helm approach, below is the values I'm using.

```
rbac:
  pspEnabled: true
ndm:
  image: 'openebs/node-disk-manager-arm64'
  sparse:
    count: '1'
ndmOperator:
  image: 'openebs/node-disk-operator-arm64'
webhook:
  image: 'openebs/admission-server-arm64'
apiserver:
  image: 'openebs/m-apiserver-arm64'
  sparse:
    enabled: true
localprovisioner:
  image: 'openebs/provisioner-localpv-arm64'
snapshotOperator:
  controller:
    image: 'openebs/snapshot-controller-arm64'
  provisioner:
    image: 'openebs/snapshot-provisioner-arm64'
provisioner:
  image: 'openebs/openebs-k8s-provisioner-arm64'
helper:
  image: 'openebs/linux-utils-arm64'
cstor:
  pool:
    image: 'openebs/cstor-pool-arm64'
  poolMgmt:
    image: 'openebs/cstor-pool-mgmt-arm64'
  target:
    image: 'openebs/cstor-istgt-arm64'
  volumeMgmt:
    image: 'openebs/cstor-volume-mgmt-arm64'
policies:
  monitoring:
    image: 'openebs/m-exporter-arm64'
```

I'm running on a fresh Ubuntu 20.04 Focal OS, I followed the pre-reqs and confirmed iscsid is working fine.

```
● iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/lib/systemd/system/iscsid.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-05-12 14:22:59 AEST; 2 days ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
    Process: 736298 ExecStartPre=/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
    Process: 736303 ExecStart=/sbin/iscsid (code=exited, status=0/SUCCESS)
   Main PID: 736305 (iscsid)
      Tasks: 2 (limit: 4434)
     Memory: 3.2M
     CGroup: /system.slice/iscsid.service
             ├─736304 /sbin/iscsid
             └─736305 /sbin/iscsid
```

Upon seeing the error I also `sudo apt install -y libjson-c-dev` but to no avail. I'm creating the StorPool WITHOUT specifying diskList and it appears to be fine.
