### ISSUE TITLE
Latest chart fails to install CRD

### ISSUE THREAD

**Issue by surajssd** [openebs/openebs#3052]
Latest chart fails to install CRD

## Description

I installed openebs using following commands:

```
kubectl create ns openebs
kubectl config set-context $(kubectl config current-context) --namespace openebs
helm install openebs stable/openebs --version 1.10.0 --set crd.enableInstall=false --set rbac.pspEnabled=true
```

And here are two pods in `CrashLoopBackOff`:

```console
$ kubectl get pods
NAME                                           READY   STATUS             RESTARTS   AGE
openebs-admission-server-f6698748f-rwbsv       1/1     Running            0          45s
openebs-apiserver-5dc94b486b-mb8sq             0/1     CrashLoopBackOff   2          45s
openebs-localpv-provisioner-7bc6958f9f-nj6wv   1/1     Running            0          45s
openebs-ndm-operator-76f6b99bfb-t9gbw          0/1     CrashLoopBackOff   2          45s
openebs-ndm-zb2p4                              1/1     Running            0          45s
openebs-provisioner-8668f86cc4-4vjlz           1/1     Running            0          45s
openebs-snapshot-operator-7b7ddd59f7-x8tq8     2/2     Running            0          45s
```

And logs from these pods:

```console
$ kubectl logs openebs-apiserver-5dc94b486b-mb8sq
+ MAYA_API_SERVER_NETWORK=eth0
+ ip -4 addr show scope global dev eth0
+ grep inet
+ awk '{print $2}'
+ cut -d / -f 1
+ CONTAINER_IP_ADDR=10.2.153.5
+ exec /usr/local/bin/maya-apiserver start '--bind=10.2.153.5'
I0602 10:00:38.030747       1 start.go:148] Initializing maya-apiserver...
preflight checks failed: precheck for bdc failed: the server could not find the requested resource (get blockdeviceclaims.openebs.io)
```

```json
$ kubectl logs openebs-ndm-operator-76f6b99bfb-t9gbw
{"level":"info","ts":1591092036.0218973,"logger":"ndm-operator","msg":"Go Version: go1.12.7"}
{"level":"info","ts":1591092036.0219724,"logger":"ndm-operator","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1591092036.0219789,"logger":"ndm-operator","msg":"operator-sdk Version: v0.5.0"}
{"level":"info","ts":1591092036.021992,"logger":"ndm-operator","msg":"Version Tag: v0.5.0"}
{"level":"info","ts":1591092036.022043,"logger":"ndm-operator","msg":"Git Commit: 63ca87a283e5feea87821c4f96c8b38c038343e3"}
{"level":"info","ts":1591092036.022491,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1591092036.107523,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1591092036.1075656,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1591092036.1624284,"logger":"ndm-operator","msg":"Registering Components"}
{"level":"info","ts":1591092036.2162755,"logger":"ndm-operator","msg":"Check if CR has to be upgraded, and perform upgrade"}
{"level":"error","ts":1591092036.2163873,"logger":"ndm-operator","msg":"Upgrade failed","error":"upgrade failed. Error : no matches for kind \"BlockDeviceClaim\" in version \"openebs.io/v1alpha1\"","stacktrace":"github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/cmd/manager/main.go:140\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/proc.go:200"}
```

The chart just exposes the flag to disable CRD installation by operator. But it does not provide any CRD configs in the chart itself. OTOH the operator still has permissions to manipulate `customresourcedefinitions`:

```yaml
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: [ "get", "list", "create", "update", "delete", "patch"]
```

## Expected Behavior

Operator should not have any permission to manipulate CRD resource at the cluster level. And when I mention `--set crd.enableInstall=false` that means I am expecting that the helm chart will install CRD instead of the operator.

This flag leaves the user to figure out how to install CRDs. Without having any positive impact security wise.

## Current Behavior

It is mentioned in description.

## Possible Solution

It should be the default behaviour of the chart to install CRD (provided by in the `crds` dir), give no permissions of `customresourcedefinitions` to operator's service account. And disable CRD installation by operator as a default.

## Steps to Reproduce

It is mentioned in description.

**Comment by kmova** [comment]
Thanks @surajssd for bringing out these.  We are also in the process of migrating the helm from:
- https://github.com/helm/charts/tree/master/stable/openebs ( to ) 
- https://github.com/openebs/charts/tree/master/charts/openebs

Will take this up for 1.11

**Comment by georgettica** [comment]
is there something I can help with on this issue? seems like it's in the works but I don't see a PR related to that

**Comment by AndiDog** [comment]
I have the same issue: want to use only the dynamic Local PV provisioner of OpenEBS, and since it's another component (ndm / maya API server) installing the CRDs dynamically, the chart installation doesn't become healthy. Therefore, I have to install the full chart with all components enabled, which wastes resources with pods I don't use. Totally agree on the solution to install the CRDs from the chart templates, and not by an operator which gets full write access to those objects.

**Comment by AndiDog** [comment]
I thought there was a workaround: install CRDs first with `kubectl apply -f "https://raw.githubusercontent.com/openebs/api/master/config/crds/all-crds.yaml"` and then `helm install --set "crd.enableInstall=false" [...]`. But that doesn't work since the file `all-crds.yaml` in fact does not include _all_ CRDs ([Makefile only generated cstor CRDs](https://github.com/openebs/api/blob/9488ac7a34840a3c2fb88ecc9a7c7bb066ad38ef/Makefile#L33)).

Also, `defaultStorageConfig.enabled=true` only works in combination with running the API server because the StorageClass objects are also created through software. I'd expect from a Helm chart to deploy as many static objects as possible through the template files. This would solve my use case of wanting to only use the local provisioner.

**Comment by prateekpandey14** [comment]
@AndiDog we are yet to refactor and add openebs CRDs as templates in [openebs helm-charts](https://github.com/openebs/charts/tree/master/charts/openebs). 

>I thought there was a workaround: install CRDs first with kubectl apply -f "https://raw.githubusercontent.com/openebs/api/master/config/crds/all-crds.yaml" and then helm install --set "crd.enableInstall=false" [...]. But that doesn't work since the file all-crds.yaml in fact does not include all CRDs (Makefile only generated cstor CRDs).

The `all-crds.yamls` contains new CRDs APIs, not part of official openebs charts yet, and they are going to be part of new charts as mentioned below listed PRs.

Here are couple of PRs under review to add CStor and NDM helm charts to add CRDs as templates
- https://github.com/openebs/cstor-operators/pull/180
- https://github.com/openebs/node-disk-manager/pull/488

**Comment by AndiDog** [comment]
@prateekpandey14 Then https://github.com/openebs/api/pull/73 may be invalid and you might want to close it. Can you tell me if my wish of running only `localprovisioner.enabled=true`, but everything else disabled, would work? Or is the API server required? The API server can be disabled in the Helm chart, so I guessed it's not essential.

**Comment by prateekpandey14** [comment]
@AndiDog yes, in case of only localPV you can skip the installation of maya API server. The minimal yaml only for localpv is [here](https://github.com/openebs/charts/blob/gh-pages/2.2.0/openebs-operator-lite-2.2.0.yaml) for better understanding

**Comment by AndiDog** [comment]
> @AndiDog yes, in case of only localPV you can skip the installation of maya API server. The minimal yaml only for localpv is [here](https://github.com/openebs/charts/blob/gh-pages/2.2.0/openebs-operator-lite-2.2.0.yaml) for better understanding

That should be documented in the Helm chart, i.e. which `<xyz>.enabled=true` setting is needed for LocalPV-only installation. But then I can't make use of that minimal installation because the default StorageClass `openebs-hostpath` (and others) are created only if you run with `provisioner.enabled=true` (it seems), which in turn requires `apiserver.enabled=true`. You see where this is going: the installation options should be clearly described. And it would be much simpler, and more secure, if the CRDs could be installed from the chart itself, as well as having the option to install default CRs such as the storage classes.

---

For reference, here's a snippet to get that minimal setup done _right now_ with chart 2.2.0:

```
kubectl create ns openebs

helm upgrade --install --set 'apiserver.enabled=false,localprovisioner.enabled=true,provisioner.enabled=false,snapshotOperator.enabled=false,ndm.enabled=false,ndmOperator.enabled=false,policies.monitoring.enabled=false,analytics.enabled=false,webhook.enabled=true' -n openebs openebs openebs/openebs

cat >/tmp/openebs-hostpath.yaml <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: /var/openebs/local
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
EOF

kubectl apply -f /tmp/openebs-hostpath.yaml

cat >/tmp/openebs-hostpath-pvc-and-pod.yaml <<EOF
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-hostpath-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-local-hostpath-pod
spec:
  volumes:
  - name: local-storage
    persistentVolumeClaim:
      claimName: local-hostpath-pvc
  containers:
  - name: hello-container
    image: busybox
    command:
       - sh
       - -c
       - 'while true; do echo "`date` [`hostname`] Hello from OpenEBS Local PV." >> /mnt/store/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
    volumeMounts:
    - mountPath: /mnt/store
      name: local-storage
EOF

kubectl apply -f /tmp/openebs-hostpath-pvc-and-pod.yaml

kubectl exec -it hello-local-hostpath-pod -- cat /mnt/store/greet.txt
```

Would be great if the chart allowed this without manual work.
