### ISSUE TITLE
Unable to create cspc resource in openebs 2.0.0

### ISSUE THREAD

**Issue by wataruian** [openebs/openebs#3110]
Hi, I was following this blog (which is openebs 1.6) https://blog.mayadata.io/openebs/cstor-pool-operations-via-cspc-in-openebs and I was able to do the examples without issues. But I want to implement it on version 2.0

Following the same method from the blog, I installed openebs 2.0 by:
`kubectl apply -f https://raw.githubusercontent.com/openebs/charts/gh-pages/2.0.0/openebs-operator.yaml`
`kubectl apply -f https://raw.githubusercontent.com/openebs/charts/gh-pages/2.0.0/cstor-operator.yaml`

I composed my CSPC resource yaml with blockdevices for each nodes and executed:
`kubectl apply -f cspc.yaml`

The yaml looks like below:
```
apiVersion: openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cspc-stripe
  namespace: openebs
spec:
  pools:
  - nodeSelector:
      kubernetes.io/hostname: "gke-integration-cluster-default-pool-44e921ba-5dck"
    poolConfig:
      cacheFile: ""
      defaultRaidGroupType: "stripe"
      overProvisioning: false
      compression: "off"
    raidGroups:
    - type: "stripe"
      isWriteCache: false
      isSpare: false
      isReadCache: false
      blockDevices:
      - blockDeviceName: blockdevice-dd83ff11760c39aecfec746b9124dd8a
      - blockDeviceName: blockdevice-fea66dcefba183e7072581bd2aacf641
  - nodeSelector:
      kubernetes.io/hostname: "gke-integration-cluster-default-pool-44e921ba-j190"
    poolConfig:
      cacheFile: ""
      defaultRaidGroupType: "stripe"
      overProvisioning: false
      compression: "off"
    raidGroups:
    - type: "stripe"
      isWriteCache: false
      isSpare: false
      isReadCache: false
      blockDevices:
      - blockDeviceName: blockdevice-61e6dee9eb03ed0e9156b2b766bbad41
      - blockDeviceName: blockdevice-9b2b21c5c17f23eb793554ecc439ebc0
  - nodeSelector:
      kubernetes.io/hostname: "gke-integration-cluster-default-pool-44e921ba-md59"
    poolConfig:
      cacheFile: ""
      defaultRaidGroupType: "stripe"
      overProvisioning: false
      compression: "off"
    raidGroups:
    - type: "stripe"
      isWriteCache: false
      isSpare: false
      isReadCache: false
      blockDevices:
      - blockDeviceName: blockdevice-a326829e0566ef6266b23a8d7c846dcb
      - blockDeviceName: blockdevice-ab049e0a28cdd76bff64a9bf8c8f8fb3
```

After executing, I am getting the error below:
`error: unable to recognize "STDIN": no matches for kind "CStorPoolCluster" in version "openebs.io/v1"`

Am I doing something wrong? 

Thanks.
