### ISSUE TITLE
Use Existing storage class as backend (cloud provider disks)

### ISSUE THREAD

**Issue by markthebault** [openebs/openebs#3115]
## Description

I recently took a look on OpenEBS, I think it is very good! I would like to be able to create a StoratePool for Jiva based on cloud provider disks and not having to mount the disks directly to the VMs or to use a host path.

Why? Because first is it not always easy to mount the disks to managed cloud k8s clusters. second, I don't want to have to create VMs with Big disks that might not be used efficiently when mounters directly to the VM.

## Context
Having to mount disks to the VMs is not that handful when the cluster are ephemeral or when we have lot of clusters. therefore it would be nice that we could the the same as the NFS provisioner that back all the storage into a specified Storage class.
like so:
```yaml
#NFS provisionner helm values
      - storageClass:
          name: default
          defaultClass: true
      - persistence:
          enabled: true
          storageClass: managed-premium
          size: 1Ti
```

## Possible Solution
This would look like:
```yaml
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
    name: azure-disks-bakend
    type: storage-class
spec:
    config:
       storageClass: managed-premium #some storage class that cloud provider define when you create a k8s cluster
```

PS: I apologize if this already available, I just haven't found it in the doc
