### ISSUE TITLE
Add ability to override nodeAffinity for Jiva replicas

### ISSUE THREAD

**Issue by ssytnikov18** [openebs/openebs#3226]
## Description
The latest openebs adds `nodeAffinity` section to the Jiva replica deployments.
By default it uses `key: kubernetes.io/hostname`.
It should be configurable in StorageClass Jiva.

## Context
Here is the example how it looks like:

```yaml
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-10-80-0-135.ec2.internal
```
If the node `ip-10-80-0-135.ec2.internal` removes from the cluster the pod won't be rescheduled to another node until I fix deployment manually.

`nodeAffinity` section should configurable to let the people configure there some Node labels or even disable it if it's not needed.

## Possible Solution
It could be done in the same way as `Replica NodeSelector Policy` https://docs.openebs.io/docs/next/jivaguide.html#Replica-NodeSelector-Policy
