### ISSUE TITLE
hostpath provisioner makes PVC pending if volumeName is specified

### ISSUE THREAD

**Issue by pavankumarkatakam** [openebs/openebs#3280]
## Description
Im using the openebs and customer storage class is used as below yaml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /mnt/storage
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```
using this storageclass, pvc are stuck at pending and there is no logs at all if volumeName is mentioned. as below yaml

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  volumeName: perconatest
```

if remove the volumeName, it status is bound but generating the unpredictable uid for that name, i need to specify the custom volume name so that i can rebind to that particular folder only.
## Expected Behavior
PVCs must be bounded even though custom volume name is mentioned.

## Current Behavior
PVCs not bounding if custom volume name is mentioned
