### ISSUE TITLE
[minikube] Provide support for using OpenEBS with mini-kube. 

### ISSUE THREAD

**Issue by kmova** [openebs/openebs#332]
The current vagrant deployment launches 3 VMs for trying out OpenEBS. This will require that a developer has a laptop which has 8GB RAM and 8 cores at the least. And with these 3 VMs running, there may not be any resources left to run/compile the code on the laptop. 

For developer consumption, running ut or experimenting, there is a need to bring up openebs on mini-kube.

**Comment by utkarshmani1997** [comment]
@kmova i tried deploying OpenEBS on mini-kube and only master and one node come up other node remains down. mini-kube is not for multi node cluster.

**Comment by kmova** [comment]
Working on an vagrant script, that can bring up a linux VM. Install mini-kube with --vm-driver=none option. With having 1 core of 512MB ram I got the following error:
: fork/exec /bin/bash: cannot allocate memory

Trying with 4GB, 4 cpu.

**Comment by kmova** [comment]
Got the minikube running within a Ubuntu virtual box using Vagrantfile (https://github.com/kmova/bootstrap/tree/master/minikube):

```
vagrant@minikube-dev:~$ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 127.0.0.1
vagrant@minikube-dev:~$ 
```

```
vagrant@minikube-dev:~$ kubectl get nodes
NAME           STATUS    AGE       VERSION
minikube-dev   Ready     8m        v1.7.5
vagrant@minikube-dev:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                              READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikube-dev   1/1       Running   1          8m
kube-system   kube-dns-910330662-4q4bm          3/3       Running   3          8m
kube-system   kubernetes-dashboard-txn8f        1/1       Running   1          8m
vagrant@minikube-dev:~$ 
```

**Comment by kmova** [comment]
openebs-operator.yaml and openebs-storageclasses.yaml successfully executed in the minikube. 

```
vagrant@minikube-dev:~$ kubectl apply -f openebs-operator.yaml 
serviceaccount "openebs-maya-operator" created
clusterrole "openebs-maya-operator" created
clusterrolebinding "openebs-maya-operator" created
deployment "maya-apiserver" created
service "maya-apiserver-service" created
deployment "openebs-provisioner" created
```
```
vagrant@minikube-dev:~$ kubectl apply -f openebs-storageclasses.yaml 
storageclass "openebs-basic" created
storageclass "openebs-percona" created
storageclass "openebs-jupyter" created
vagrant@minikube-dev:~$ 
```

```
vagrant@minikube-dev:~$ kubectl get pods
NAME                                   READY     STATUS    RESTARTS   AGE
maya-apiserver-546443015-m16b5         1/1       Running   0          1m
openebs-provisioner-3862123968-xd2xs   1/1       Running   0          1m
vagrant@minikube-dev:~$ 
```

**Comment by kmova** [comment]
Running the percona-demo: 
(https://github.com/openebs/openebs/blob/master/k8s/demo/percona/demo-percona-mysql-pvc.yaml)

```
vagrant@minikube-dev:~$ kubectl apply -f demo-percona-mysql-pvc.yaml 
pod "percona" created
persistentvolumeclaim "demo-vol1-claim" created
```
```
vagrant@minikube-dev:~$ kubectl get pvc
NAME              STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS      AGE
demo-vol1-claim   Bound     pvc-e9e53661-9eba-11e7-be70-080027b55b5e   5G         RWO           openebs-percona   6s
```
```
vagrant@minikube-dev:~$ kubectl get pv 
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                     STORAGECLASS      REASON    AGE
pvc-e9e53661-9eba-11e7-be70-080027b55b5e   5G         RWO           Delete          Bound     default/demo-vol1-claim   openebs-percona             10s
```

```
vagrant@minikube-dev:~$ kubectl get pods
NAME                                                             READY     STATUS              RESTARTS   AGE
maya-apiserver-546443015-m16b5                                   1/1       Running             0          5m
openebs-provisioner-3862123968-xd2xs                             1/1       Running             0          5m
percona                                                          0/1       ContainerCreating   0          17s
pvc-e9e53661-9eba-11e7-be70-080027b55b5e-ctrl-2800514440-w9qt5   0/1       ContainerCreating   0          17s
pvc-e9e53661-9eba-11e7-be70-080027b55b5e-rep-1900829533-08knx    0/1       ContainerCreating   0          17s
pvc-e9e53661-9eba-11e7-be70-080027b55b5e-rep-1900829533-t94j4    0/1       Pending             0          17s
vagrant@minikube-dev:~$ 
```

**Comment by kmova** [comment]
Percona started to run, with one openebs replica. 

```
vagrant@minikube-dev:~$ kubectl get pods
NAME                                                             READY     STATUS    RESTARTS   AGE
maya-apiserver-546443015-m16b5                                   1/1       Running   0          9m
openebs-provisioner-3862123968-xd2xs                             1/1       Running   0          9m
percona                                                          1/1       Running   0          4m
pvc-e9e53661-9eba-11e7-be70-080027b55b5e-ctrl-2800514440-w9qt5   1/1       Running   0          4m
pvc-e9e53661-9eba-11e7-be70-080027b55b5e-rep-1900829533-08knx    1/1       Running   0          4m
pvc-e9e53661-9eba-11e7-be70-080027b55b5e-rep-1900829533-t94j4    0/1       Pending   0          4m
vagrant@minikube-dev:~$ 
```

**Comment by AmitKumarDas** [comment]
Following spec will create OpenEBS volume with a single replica

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-jiva-vsm
  labels:
    volumeprovisioner.mapi.openebs.io/replica-count: 1
```

**Comment by prateekpandey14** [comment]
It will be good to have control over replica-count form mayactl too, it will be good for dev/testing purposes ?

**Comment by kmova** [comment]
Attempting to use the ENV variable for maya-apiserver that defines the default replica count. 

Modified the maya-apiserver spec to the following:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maya-apiserver
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maya-apiserver
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: maya-apiserver
        imagePullPolicy: Always
        image: openebs/m-apiserver:0.3-RC4
        ports:
        - containerPort: 5656
        env:
        - name: DEFAULT_REPLICA_COUNT
          value: "1"
```

With this, when provisioning a new volume, I am getting the following errors in the maya-apiserver log, which results in 500 error for openebs-provisioner. 

```
ERROR: logging before flag.Parse: I0927 09:00:39.029964      12 util.go:1009] Will use env var 'DEFAULT_REPLICA_IMAGE: '
ERROR: logging before flag.Parse: I0927 09:00:39.029978      12 util.go:1009] Will use env var 'DEFAULT_REPLICA_COUNT: 1'
ERROR: logging before flag.Parse: I0927 09:00:39.030003      12 util.go:1009] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
ERROR: logging before flag.Parse: I0927 09:00:39.030018      12 util.go:1009] Will use env var 'DEFAULT_ORCHESTRATOR_NS: '
ERROR: logging before flag.Parse: I0927 09:00:39.031198      12 util.go:1009] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
ERROR: logging before flag.Parse: I0927 09:00:39.031232      12 util.go:1009] Will use env var 'DEFAULT_ORCHESTRATOR_NS: '
ERROR: logging before flag.Parse: I0927 09:00:39.032922      12 util.go:1009] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
ERROR: logging before flag.Parse: I0927 09:00:39.032958      12 util.go:1009] Will use env var 'DEFAULT_ORCHESTRATOR_NS: '
   2017/09/27 09:00:39.395989 [ERR] http: Request POST /latest/volumes/, error: VSM 'pvc-42346667-a362-11e7-a0f8-080027b55b5e' replica count '1' does not match persistent path count '2'
```
sos @AmitKumarDas

**Comment by AmitKumarDas** [comment]
This seems to be bug with m-apiserver 0.3-RC4.
This should go away with latest image. Can you try the latest image of m-apiserver

**Comment by kmova** [comment]
Thanks @AmitKumarDas. It worked with latest image tagged *ci*

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maya-apiserver
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maya-apiserver
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: maya-apiserver
        imagePullPolicy: Always
        image: openebs/m-apiserver:ci
        ports:
        - containerPort: 5656
        env:
        - name: DEFAULT_REPLICA_COUNT
          value: "1"
```
After running the percona app using the demo yaml file (openebs/k8s/demo/)

```
vagrant@minikube-dev:~$ kubectl get pods
NAME                                                            READY     STATUS    RESTARTS   AGE
maya-apiserver-457998317-0n6j1                                  1/1       Running   0          16m
openebs-provisioner-3862123968-r1zwk                            1/1       Running   0          16m
percona                                                         1/1       Running   0          2m
pvc-6db036b3-a368-11e7-a0f8-080027b55b5e-ctrl-361109286-sw31j   1/1       Running   0          2m
pvc-6db036b3-a368-11e7-a0f8-080027b55b5e-rep-1771209453-dftqs   1/1       Running   0          2m
```
