### ISSUE TITLE
block device Inactives if partitions on the same OS disk

### ISSUE THREAD

**Issue by survivant** [openebs/openebs#3321]
OpenEBS 2.4.0

````
root@test-pcl114:~# kubectl get bd -n openebs -o wide
NAME                                           NODENAME      PATH                                   FSTYPE   SIZE           CLAIMSTATE   STATUS     AGE
blockdevice-791dd8e61c1596f6bf30e1764ddd003d   test-pcl114   /dev/sda3                                       536870912000   Claimed      Inactive   48d
blockdevice-82a07bfde481c811ee72942eca618568   test-pcl114   /dev/sda1                                       536870912000   Claimed      Inactive   48d
blockdevice-e4a27178865240e753cecb173c9c37c2   test-pcl114   /dev/sda2                                       536870912000   Claimed      Inactive   48d
sparse-0352c127ae5e3c70a24bd9a476a31359        test-pcl114   /var/openebs/sparse/3-ndm-sparse.img            10737418240    Claimed      Active     48d
sparse-23516928ac3e7cb19467d0f16bd5cdab        test-pcl114   /var/openebs/sparse/0-ndm-sparse.img            10737418240    Claimed      Active     48d
sparse-47e863a85f21894a9d9273d0e5f8eba5        test-pcl114   /var/openebs/sparse/4-ndm-sparse.img            10737418240    Claimed      Active     48d
sparse-60ee74411d36b121efa4b4abb7880903        test-pcl114   /var/openebs/sparse/2-ndm-sparse.img            10737418240    Unclaimed    Active     48d
sparse-d86d9885ec37abe95ef316ac3d555c17        test-pcl114   /var/openebs/sparse/1-ndm-sparse.img            10737418240    Unclaimed    Active     48d
root@test-pcl114:~#
````

````
root@test-pcl114:~# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0  1.8T  0 disk
├─sda1   8:1    0  500G  0 part
├─sda2   8:2    0  500G  0 part
├─sda3   8:3    0  500G  0 part
└─sda4   8:4    0  363G  0 part /kubernetes
sdb      8:16   0 55.9G  0 disk
├─sdb1   8:17   0  512M  0 part /boot/efi
└─sdb2   8:18   0 55.4G  0 part /
sdc      8:32   0    8G  0 disk /kubernetes/kubelet/pods/9914f838-b3a3-41c9-bc7f-e32d271065d3/volumes/kubernetes.io~csi/pvc-dbe7dfc2-679b-4578-9d10-b7856d692768/mount
sdd      8:48   0    8G  0 disk /kubernetes/kubelet/pods/faf7e4d1-52b0-4255-8897-684795d36250/volumes/kubernetes.io~csi/pvc-dd7ab2df-6809-41e7-b467-6b77e21cd538/mount
sdf      8:80   0    5G  0 disk /kubernetes/kubelet/pods/54a080da-e28f-4740-8794-4801ae8757a9/volumes/kubernetes.io~csi/pvc-0f52f72a-0ffd-425d-9957-f4556a8376a6/mount
root@test-pcl114:~#
````

here my configmap
````
root@test-pcl114:~# kubectl get cm -n openebs openebs-ndm-config -o yaml
apiVersion: v1
data:
  node-disk-manager.config: |
    probeconfigs:
      - key: udev-probe
        name: udev probe
        state: true
      - key: seachest-probe
        name: seachest probe
        state: false
      - key: smart-probe
        name: smart probe
        state: true
    filterconfigs:
      - key: os-disk-exclude-filter
        name: os disk exclude filter
        state: true
        exclude: "/,/boot"
      - key: vendor-filter
        name: vendor filter
        state: true
        include: ""
        exclude: "CLOUDBYT,OpenEBS"
      - key: path-filter
        name: path filter
        state: true
        include: "/dev/sda1,/dev/sda2,/dev/sda3"
        exclude: "/dev/loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd,/dev/sda4"
kind: ConfigMap
````

possible explaination

If a disk is excluded by a filter,  and if any of its partitions are included, the code hits an error.
i.e for eg: /dev/sda  is filtered by path filter, and `/dev/sda1` need to be used, it causes an error in creating blockdevices.
This bug gets fixed by a feature in  the coming release (enabled via feature flag UseOSDisk ),
