### ISSUE TITLE
Can't create pvc due to webhook failure (invalid cert, unknown authority)

### ISSUE THREAD

**Issue by alekc** [openebs/openebs#3329]
## Description
After the fresh install of openebs I am unable to create a new pvc due to a failure in webhook communication. 

```
Internal error occurred: failed calling webhook "admission-webhook.openebs.io": Post "https://admission-server-svc.openebs.svc:443/validate?timeout=5s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "admission-server-svc-ca"
```

## Attempted solutions
Following the docs https://docs.openebs.io/docs/next/t-volume-provisioning.html (`Unable to create persistentVolumeClaim due to certificate verification error`) I've delete the `admission-server` pod to force it to use the new cert, with no luck 

Also, I've tried to delete all secrets from the openebs namespace, waited until these secrets are regenerated, and recycled pods again just to be sure. 

This ticket is possibly related: https://github.com/openebs/openebs/issues/2772, but since the possible solution is not clear from it, I opened this one. 

## Steps to Reproduce
Install openebs through the helm chart with default values. 
```
source:
  repoURL: 'https://openebs.github.io/charts'
  targetRevision: 2.5.*
  chart: openebs
```

SC
```
kubectl get sc jiva-gpd -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "3"
      - name: StoragePool
        value: gpdpool
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"cas.openebs.io/config":"- name: ReplicaCount\n  value: \"3\"\n- name: StoragePool\n  value: gpdpool\n","openebs.io/cas-type":"jiva"},"labels":{"argocd.argoproj.io/instance":"runtime"},"name":"jiva-gpd"},"provisioner":"openebs.io/provisioner-iscsi"}
    openebs.io/cas-type: jiva
  creationTimestamp: "2021-01-19T21:35:50Z"
  labels:
    argocd.argoproj.io/instance: runtime
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cas.openebs.io/config: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:openebs.io/cas-type: {}
        f:labels:
          .: {}
          f:argocd.argoproj.io/instance: {}
      f:provisioner: {}
      f:reclaimPolicy: {}
      f:volumeBindingMode: {}
    manager: argocd-application-controller
    operation: Update
    time: "2021-01-19T21:35:50Z"
  name: jiva-gpd
  resourceVersion: "31517034"
  uid: 7aadfb91-67fe-41a6-8bd7-5b4e44a119f7
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Pool
```
kubectl get storagepool gpdpool -o yaml
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openebs.io/v1alpha1","kind":"StoragePool","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"runtime"},"name":"gpdpool"},"spec":{"path":"/jiva/"}}
  creationTimestamp: "2021-01-19T21:21:17Z"
  generation: 1
  labels:
    argocd.argoproj.io/instance: runtime
  managedFields:
  - apiVersion: openebs.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:argocd.argoproj.io/instance: {}
      f:spec:
        .: {}
        f:path: {}
    manager: argocd-application-controller
    operation: Update
    time: "2021-01-19T21:21:17Z"
  name: gpdpool
  resourceVersion: "31517043"
  uid: c236ce29-2a19-4f86-bc7d-68fb9a8d6bab
spec:
  path: /jiva/
```

Pvc
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: jiva-gpd
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: portainer
    app.kubernetes.io/version: 2.0.1
    argocd.argoproj.io/instance: portainer
    helm.sh/chart: portainer-1.0.8
    io.portainer.kubernetes.application.stack: portainer
  name: portainer
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
## Your Environment

```
kubectl get nodes
NAME            STATUS   ROLES                  AGE   VERSION
cooler-master   Ready    control-plane,master   79d   v1.20.2
nas             Ready    control-plane,master   79d   v1.20.2
xps-server      Ready    control-plane,master   79d   v1.20.2
```

```
 kubectl get sc
NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
jiva-gpd                    openebs.io/provisioner-iscsi                               Delete          Immediate              false                  17h
local-path (default)        cluster.local/local-path-provisioner                       Delete          WaitForFirstConsumer   false                  11d
mediabox-local-storage-2t   kubernetes.io/no-provisioner                               Delete          Immediate              false                  75d
mediabox-local-storage-4t   kubernetes.io/no-provisioner                               Delete          Immediate              false                  75d
openebs-device              openebs.io/local                                           Delete          WaitForFirstConsumer   false                  47h
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  47h
openebs-jiva-default        openebs.io/provisioner-iscsi                               Delete          Immediate              false                  47h
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  47h
```

```
❯ kubectl get secrets
NAME                      TYPE                                  DATA   AGE
admission-server-secret   Opaque                                3      10m
default-token-ztpwh       kubernetes.io/service-account-token   3      55m
openebs-token-nqs6g       kubernetes.io/service-account-token   3      55m
```

```
kubectl get pods
NAME                                           READY   STATUS    RESTARTS   AGE
openebs-admission-server-8d95556bc-mk8jj       1/1     Running   0          7m50s
openebs-apiserver-76d8466fcc-6f8kb             1/1     Running   0          9m14s
openebs-localpv-provisioner-548b5b9857-drkvv   1/1     Running   0          9m14s
openebs-ndm-8jsvd                              1/1     Running   0          8m40s
openebs-ndm-bhflw                              1/1     Running   0          9m8s
openebs-ndm-bl7nq                              1/1     Running   0          8m7s
openebs-ndm-operator-5599755cd4-2zhvb          1/1     Running   0          9m13s
openebs-provisioner-74dbb9dfdc-fx4gd           1/1     Running   0          9m13s
openebs-snapshot-operator-69567d5975-hdrtl     2/2     Running   0          9m13s
```

```
kubectl logs openebs-admission-server-8d95556bc-mk8jj
I0120 15:19:17.096553       1 main.go:111] Webhook server started
2021/01/20 15:19:33 http: TLS handshake error from 192.168.0.29:42036: remote error: tls: bad certificate
```

**Comment by alekc** [comment]
Finally solved by deleting webhook, followed by secrets, and recycling pods. 

```
kubectl get ValidatingWebhookConfiguration openebs-validation-webhook-cfg
NAME                             WEBHOOKS   AGE
openebs-validation-webhook-cfg   1          104m
```

**Comment by Nurza** [comment]
> Finally solved by deleting webhook, followed by secrets, and recycling pods.
> 
> ```
> kubectl get ValidatingWebhookConfiguration openebs-validation-webhook-cfg
> NAME                             WEBHOOKS   AGE
> openebs-validation-webhook-cfg   1          104m
> ```

To be more precise:

```shell
kubectl delete secret admission-server-secret
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io openebs-validation-webhook-cfg
kubectl rollout restart deployment openebs-admission-server
```

did the trick, thank you

**Comment by voarsh2** [comment]
Thanks. Bye bye OpenEBS.

**Comment by kmova** [comment]
@voarsh2 - do you have feedback that you can provide. The above comment isn't helpful to improve the product.

**Comment by woloss** [comment]
`k delete cspc cspc-stripe -n openebs`
Gives me
`Error from server (InternalError): Internal error occurred: failed calling webhook "admission-webhook.cstor.openebs.io": Post "https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "openebs-cstor-admission-server-ca")`

Tried to do rollout restart (those lines above), didn't work out.
Also, can't use this ["clean" script](https://github.com/openebs/openebs-docs/issues/900#issuecomment-734434851). Works fine with other errors, but not with x509 certificate one.

**Comment by npu21** [comment]
Even if did the trick above，could still get other issue like this：
![image](https://user-images.githubusercontent.com/11768607/168715247-40d96a29-3243-4f97-b70e-f91b9e70a726.png)
Could anyone give a root cause ?

**Comment by l-ra** [comment]
I observed the same problem a year after OpenEBS installation.  I used helm to install OpenEBS 2.12.x. I described the solution here https://gist.github.com/l-ra/2ea09a3e3e11d67772f4506cdf31c6a2 .

In short - the admission webhook secrets containing TLS server certificates are regenerated when the admission server starts and the secret does  not exist. But the newly generated certificate is generated using fresh CA certificate. But the CA certificate is referenced in the validation web hook configuration as a CAbundle. After certificate regeneration the validation webhook client configuration need to be updated to use new CA certificate.

**Comment by sachinshakya507** [comment]
I got an issue saying
failed calling webhook "admission-webhook.cstor.openebs.io": failed to call webhook: Post "https://openebs-cstor-admission-server.openebs.svc:443/validate?timeout=5s": x509: certificate has expired or is not yet valid
what i did to resolve 
kubectl delete ValidatingWebhookConfiguration openebs-cstor-validation-webhook

**Comment by ianroberts** [comment]
In case it helps anyone else who hits this problem, I have worked around it in my cluster by creating a once-a-week CronJob that performs the three steps outlined above (delete webhook configuration, delete secret, restart webhook server) if the certificate will expire in the next 14 days:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kick-admission-webhook
  namespace: openebs
  labels:
    k8s-apps: kick-admission-webhook
spec:
  # Once a week on Sunday early hours
  schedule: "14 3 * * 0"
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-apps: kick-admission-webhook
        spec:
          serviceAccountName: openebs-cstor-operator
          restartPolicy: Never
          containers:
          - name: cleanup
            # Update this image tag to match Kubernetes version
            image: "bitnami/kubectl:1.27"
            imagePullPolicy: "IfNotPresent"
            command: ["bash"]
            args:
            - "-c"
            - |
              if ( kubectl get secret openebs-cstor-admission-secret -o 'go-template={{ index .data "app.crt" | base64decode }}' | openssl x509 -checkend 1209600 ) ; then
                echo "Certificate is still valid"
              else
                echo "Certificate expires in the next 14 days, recycling webhook:"
                echo "Deleting webhook configuration"
                kubectl delete validatingwebhookconfiguration openebs-cstor-validation-webhook
                echo "Deleting secret"
                kubectl delete secret openebs-cstor-admission-secret
                echo "Restarting admission controller deployment"
                kubectl rollout restart deployment openebs-cstor-admission-server
              fi
```
