### ISSUE TITLE
Support two access modes ReadWriteOnce and ReadOnlyMany in PVC

### ISSUE THREAD

**Issue by laimison** [openebs/openebs#3335]
Hi,

Usually cStor PVC has ReadWriteOnce. Could it have ReadOnlyMany too?
I'm able to create PVC with ReadWriteOnce and after the fact patch PV with ReadOnlyMany so then it has two modes. Is it an issue or some limitation that I can't request in PVC using code below?

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-pvc-rh-t
  namespace: rh-t
spec:
  storageClassName: openebs-sc-spc
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
```

By patching, I meant:

```
    echo "Add ReadOnlyMany"
    kubectl get pv | grep cstor-pvc-rh-t | while read -r line; do pvc=`echo $line | awk -F ' ' '{print $1}'`; kubectl patch pv $pvc -p '{"spec":{"accessModes": ["ReadWriteOnce", "ReadOnlyMany"]}}'; done

```

So it works, but not directly in PVC.

OpenEBS 2.3.0

Many thanks
