### ISSUE TITLE
PVC with long name not getting initialized

### ISSUE THREAD

**Issue by maagy** [openebs/openebs#3343]
## Description

PVC with long name does not get provisioned. When I create pvc with name _short-name-pvc-0_, everything is OK - cstor creates volume, replicas and I can use it in workload. But name _prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0_ seems to be a problem. PVC is in _bound_ state, but openebs doesn't create cstorvolume at all.

## Expected Behavior

I would expect that 58 characters long name is not a problem and pvc will be provisioned.

## Current Behavior

No cstorvolume created at all.

## Steps to Reproduce

This works fine:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: short-name-pvc-0
  namespace: cattle-monitoring-system
spec:
  storageClassName: cstor-csi-stripe
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
```

This is a problem:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0
  namespace: cattle-monitoring-system
spec:
  storageClassName: cstor-csi-stripe
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
```

## Screenshots

![image](https://user-images.githubusercontent.com/28754993/108042457-1788ef00-7040-11eb-9a8d-9d0729275490.png)

## Your Environment

I'm using rancher deployed cluster, cstor operator. Cstor pool:
```
kubectl get cspc -n openebs
NAME          HEALTHYINSTANCES   PROVISIONEDINSTANCES   DESIREDINSTANCES   AGE
cspc-stripe   4                  4                      4                  84m
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
