### ISSUE TITLE
Dynamically Provisioned PV and PVC , Scale Down-Deleted PVC's ,Scale Up -Retain the same PV's for newly Dynamically created  PVC's

### ISSUE THREAD

**Issue by rgangoni** [openebs/openebs#3372]
In my Project we are using the storage file
```
vim  sc.yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local/"
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
```
Thsi is my yaml file for dynamically provisioning PV and PVC using OpenEBS

```
vim clickhouse-server.yaml

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "repl-05"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse:20.7
  configuration:
    zookeeper:
      nodes:
      - host: zookeeper.zoo1ns
    clusters:
      - name: replicated
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    volumeClaimTemplates:
      - name: my-volume
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
    podTemplates:
      - name: clickhouse:20.7
        spec:
          containers:
            - name: clickhouse-pod
              image: yandex/clickhouse-server:20.7
              volumeMounts:
               - name: my-volume
  ```

Here is my PV and PVC  got bound .
```
ubuntu@ip-172-31-11-43:~/statefullset$ sudo kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                         STORAGECLASS       REASON   AGE
pvc-31960d13-3b44-40dd-9c2d-c44a96626940   500Mi      RWO            Retain           Bound    test/my-volume-chi-repl-05-replicated-0-0-0   openebs-hostpath            6m54s
pvc-9fd35ccc-cfdc-4fc8-93e5-eaa3973efaa2   500Mi      RWO            Retain           Bound    test/my-volume-chi-repl-05-replicated-0-1-0   openebs-hostpath            6m46s
pvc-3486ab47-b6a3-48ce-abc7-5e894515e43f   500Mi      RWO            Retain           Bound    test/my-volume-chi-repl-05-replicated-1-0-0   openebs-hostpath            6m38s
pvc-7836a130-e72c-4a8c-b8a4-d1359a22f39c   500Mi      RWO            Retain           Bound    test/my-volume-chi-repl-05-replicated-1-1-0   openebs-hostpath            6m31s
```

The PVC is 
```
ubuntu@ip-172-31-11-43:~/statefullset$ sudo kubectl get pvc -n test
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
my-volume-chi-repl-05-replicated-0-0-0   Bound    pvc-31960d13-3b44-40dd-9c2d-c44a96626940   500Mi      RWO            openebs-hostpath   30s
my-volume-chi-repl-05-replicated-0-1-0   Bound    pvc-9fd35ccc-cfdc-4fc8-93e5-eaa3973efaa2   500Mi      RWO            openebs-hostpath   23s
my-volume-chi-repl-05-replicated-1-0-0   Bound    pvc-3486ab47-b6a3-48ce-abc7-5e894515e43f   500Mi      RWO            openebs-hostpath   16s
my-volume-chi-repl-05-replicated-1-1-0   Bound    pvc-7836a130-e72c-4a8c-b8a4-d1359a22f39c   500Mi      RWO            openebs-hostpath   8s
```

## The Problem comes here 
when i **scale down**  shards to 1 and replicas to 1 
the **PVC got deleted**  and  **PV is in Released State**

When i **Scale up**  the new PV and PVC created  and bounded 

## Requirement : 
Newly  **dynamicaly created PVC's should use the old  PV's**.   
To reuse the old PV created before .
