### ISSUE TITLE
Restore deleted deployment

### ISSUE THREAD

**Issue by turowicz** [openebs/openebs#3420]
Dear @niladrih @prateekpandey14

Unfortunately during my attempt to remove the unused openebs pods (https://github.com/openebs/openebs/issues/3418) I have accidentally removed ALL pvc-* deployments from openebs namespace.

Now, the PVCs and PVs have remained and have not been deleted. Is it possible to somehow tell OpenEBS to recreate missing deployments?

**Comment by turowicz** [comment]
cc shubham14bajpai

**Comment by turowicz** [comment]
Or should I delete everything and start over?

**Comment by turowicz** [comment]
We are happy to pay for help on this

**Comment by turowicz** [comment]
![image](https://user-images.githubusercontent.com/1055391/126981510-37c0fd8e-fe7d-4674-92e7-a89e9c2bd798.png)

![image](https://user-images.githubusercontent.com/1055391/126981552-f2732431-f545-4c26-99d8-d62304c7024e.png)

**Comment by turowicz** [comment]
I need a way of recreating the `pvc-*` deployments.

**Comment by turowicz** [comment]
The solution:

1. Go to your cluster and deploy an example PVC from the script below.
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-vol1
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
```
2. `kubectl apply -f pvc.yaml`
3. In the `openebs` namespace new deployments will appear.
4. Export all new deployments (ctrl and replicas) to yaml files.
5. Delete the `status` section of each yaml file.
6. Find the first PVC you want to fix, copy it's `uuid` and look for it in the services by appending `pvc-` in front of the `uuid`.
7. Copy the service IP.
8. Replace the service IP and `pvc-` plus `uuid` in the yaml files.
9. `kubectl apply -f ` each of the yaml files.
10. Profit!

Thanks to @shubham14bajpai for helping me out with this!
