### ISSUE TITLE
How do I need to set up so that the Local PV Hostpath is only created on the Node I specify?

### ISSUE THREAD

**Issue by 1121437613** [openebs/openebs#3425]
How do I need to set up so that the Local PV Hostpath is only created on the Node I specify? 

There are many nodes in my k8s cluster, I hope openebs only provides Local PV Hostpath on some nodes, because not all nodes have enough storage space

**Comment by kmova** [comment]
@1121437613 - is there a common node label available on the nodes that have storage. 

For example, if you have hostpath as `/mnt/hostpath` and all the storage nodes where `/mnt/hostpath` is available is labeled as `openebs.io/node-role=storage`, you can use the following topology settings in the Local PV Storage class. 


```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: "/var/local-hostpath/"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/node-role
        values:
          - storage
```
