### ISSUE TITLE
pvc fails to mount for openebs-jiva-csi-default

### ISSUE THREAD

**Issue by RomanKisilenko** [openebs/openebs#3485]
## Description
1. I installed drivers on my worker node as instructed here: https://docs.openebs.io/docs/next/prerequisites.html
2. I installed latest openebs via helm chart on my kubernetes 1.18 cluster as following:
```
helm install openebs openebs/openebs --namespace openebs --create-namespace --set jiva.enabled=true
```
3. Then I created a PV using openebs-jiva-csi-default storage class as following:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: project-stock
  name: comments-storage-g2
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```
## Expected Behavior
The pvc successfully provisioned

## Current Behavior
The volume is not provisioned:
```
Events:
  Type     Reason                Age              From                                                                                    Message
  ----     ------                ----             ----                                                                                    -------
  Normal   ExternalProvisioning  3s (x3 over 6s)  persistentvolume-controller                                                             waiting for a volume to be created, either by external provisioner "jiva.csi.openebs.io" or manually created by system administrator
  Normal   Provisioning          3s (x3 over 6s)  jiva.csi.openebs.io_openebs-jiva-csi-controller-0_52c1ccbe-02fe-4b3d-b07f-988840de15db  External provisioner is provisioning volume for claim "project-stock/comments-storage-g2"
  Warning  ProvisioningFailed    3s (x3 over 6s)  jiva.csi.openebs.io_openebs-jiva-csi-controller-0_52c1ccbe-02fe-4b3d-b07f-988840de15db  failed to provision volume with StorageClass "openebs-jiva-csi-default": rpc error: code = InvalidArgument desc = Failed to validate volume capabilities
```
