### ISSUE TITLE
create jiva storagepool faild

### ISSUE THREAD

**Issue by lixiaopengy** [openebs/openebs#3495]
The service version is as follows：
kubernetes v1.18.0
Openebs 2.12

I follow the official link https://openebs.io/docs/user-guides/jiva-guide#create-a-pool create storagepool faild
```
[root@k8s1 jiva]# kubectl create -f storagepool.yaml
error: unable to recognize "storagepool.yaml": no matches for kind "StoragePool" in version "openebs.io/v1alpha1"

[root@k8s1 jiva]# cat storagepool.yaml
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: gpdpool
  type: hostdir
spec:
  path: "/home/jiva"

```

If only the default policy is used，Failed to create PVC display
```
[root@k8s1 ~]# cat sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-default
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
       - name: ReplicaCount
         value: "3"
provisioner: openebs.io/provisioner-iscsi
```

PVC error reports are as follows：
```
[root@k8s1 ~]# kubectl describe pvc demo-vol1-claim
Name:          demo-vol1-claim
Namespace:     default
StorageClass:  openebs-jiva-default
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: openebs.io/provisioner-iscsi
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                Age              From                         Message
  ----    ------                ----             ----                         -------
  Normal  ExternalProvisioning  2s (x2 over 4s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "openebs.io/provisioner-iscsi" or manually created by system administrator

```
For other component service logs, please contact me。Thank you for your help
