### ISSUE TITLE
Mount failed after installing openebs on Digitalocean

### ISSUE THREAD

**Issue by saul-data** [openebs/openebs#3533]
## Description
I installed openebs on Digitalocean with the following steps - aim is to achieve RWX:
1. One click install Openebs on the Digitalocean marketplace
2. Installed the provisioner with kubectl apply: https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/deploy/kubectl/openebs-nfs-provisioner.yaml
3. Created a storageclass as follows:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rwx-storage
  annotations:
    openebs.io/cas-type: nfsrwx
    cas.openebs.io/config: |
      - name: NFSServerType
        value: "kernel"
      - name: BackendStorageClass
        value: "do-block-storage"
provisioner: openebs.io/nfsrwx
reclaimPolicy: Delete
```

## Expected Behavior
When creating a PVC storage, I'd expect the storage to be provisioned through do-block-storage and the NFS server to be running. 

## Current Behavior
The installation has caused the do-block-storage storage class to stop working for both NFS server (openebs) and without i.e. straight do-block-storage. 

## Error message
```
MountVolume.MountDevice failed for volume "pvc-b39a6f9a-4016-4d60-8658-757f4807da3a" : rpc error: code = Internal desc = mounting failed: exit status 255 cmd: 'mount -t ext4 /dev/disk/by-id/scsi-0DO_Volume_pvc-b39a6f9a-4016-4d60-8658-757f4807da3a /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b39a6f9a-4016-4d60-8658-757f4807da3a/globalmount' output: "mount: mounting /dev/disk/by-id/scsi-0DO_Volume_pvc-b39a6f9a-4016-4d60-8658-757f4807da3a on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b39a6f9a-4016-4d60-8658-757f4807da3a/globalmount failed: Invalid argument\n"
```

I've seen a similar ticket here but with no conclusion? https://github.com/openebs/openebs/issues/3497
