### ISSUE TITLE
Upgrade 3.0.0 to 3.1.0 with cstor

### ISSUE THREAD

**Issue by allanian** [openebs/openebs#3546]
Hello, can you provide a faq for upgrade process, current documentation only working for versions like 2.1.0.
hello, i have installed openebs from helm chart 3.0.0, how i can upgrade it to 3.1.0?
When i created job for update pools with that job, i get this error - no image
```
apiVersion: batch/v1
kind: Job
metadata:
  name: cstor-spc-3.0.0-to-3.1.0
  namespace: openebs
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: openebs
      containers:
      - name:  update
        args:
	- "cstor-spc"
        - "--v=4"
        - "--from-version=3.0.0"
        - "--to-version=3.1.0"
        - "cstor-disk-pool1"
        - "cstor-disk-pool2"
        env:
	- name: OPENEBS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        tty: true
        image: openebs/m-upgrade:3.1.0
        imagePullPolicy: Always
      restartPolicy: OnFailure
```
