### ISSUE TITLE
Cspc doesn't show the newly added pool

### ISSUE THREAD

**Issue by alifiroozi80** [openebs/openebs#3604]
Hello

I've had a simple cspc in my cluster:

```shell
$ k -n openebs get cspc
NAME              HEALTHYINSTANCES   PROVISIONEDINSTANCES   DESIREDINSTANCES   AGE
cstor-pool-disk   4                  4                      4                  29d
```

And for some reasons, I want to add to them.

So, As the [docs](https://openebs.io/docs/user-guides/cstor/advanced#adding-new-disks-to-existing-nodes) said, I first added them to my configuration file:

```yaml
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-pool-disk
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "worker1"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-fcc0b069214fb88e73b4c744a586b21e"
           - blockDeviceName: "blockdevice-0487f0c6fa305ed08b69136b3201deba" #NEW
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker2"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-1d0134218cf292a9fbe56964dab9f908"
           - blockDeviceName: "blockdevice-905336dd2f5e26c2cb84c98e02e0774b" #NEW
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker3"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-141ad763fecfd113f6b2e842cb6991c1"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker4"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-50c83768f58753e03f6af761582c37d0"
     poolConfig:
       dataRaidGroupType: "stripe"
```

And I applied the file successfully.

Now, after I describe the `cspc`, I see that the new block devices have been added:

```shell
$ k -n openebs describe cspc cstor-pool-disk 
Name:         cstor-pool-disk
Namespace:    openebs
Labels:       <none>
Annotations:  <none>
API Version:  cstor.openebs.io/v1
Kind:         CStorPoolCluster
Metadata:
  Creation Timestamp:  2022-12-17T05:28:51Z
  Finalizers:
    cstorpoolcluster.openebs.io/finalizer
  Generation:  13
  Managed Fields:
    API Version:  cstor.openebs.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cstorpoolcluster.openebs.io/finalizer":
      f:status:
        .:
        f:conditions:
        f:desiredInstances:
        f:healthyInstances:
        f:provisionedInstances:
      f:versionDetails:
        .:
        f:desired:
        f:status:
          .:
          f:current:
          f:dependentsUpgraded:
          f:lastUpdateTime:
    Manager:      cspc-operator
    Operation:    Update
    Time:         2022-12-31T11:40:13Z
    API Version:  cstor.openebs.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:pools:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2023-01-15T10:30:22Z
  Resource Version:  16078450
  UID:               14a65c1b-aa67-42b8-b688-1a684d5e24bd
Spec:
  Pools:
    Data Raid Groups:
      Block Devices:
        Block Device Name:  blockdevice-fcc0b069214fb88e73b4c744a586b21e
        Block Device Name:  blockdevice-0487f0c6fa305ed08b69136b3201deba
    Node Selector:
      kubernetes.io/hostname:  worker1
    Pool Config:
      Data Raid Group Type:  stripe
    Data Raid Groups:
      Block Devices:
        Block Device Name:  blockdevice-1d0134218cf292a9fbe56964dab9f908
        Block Device Name:  blockdevice-905336dd2f5e26c2cb84c98e02e0774b
    Node Selector:
      kubernetes.io/hostname:  worker2
    Pool Config:
      Data Raid Group Type:  stripe
    Data Raid Groups:
      Block Devices:
        Block Device Name:  blockdevice-141ad763fecfd113f6b2e842cb6991c1
    Node Selector:
      kubernetes.io/hostname:  worker3
    Pool Config:
      Data Raid Group Type:  stripe
    Data Raid Groups:
      Block Devices:
        Block Device Name:  blockdevice-50c83768f58753e03f6af761582c37d0
    Node Selector:
      kubernetes.io/hostname:  worker4
    Pool Config:
      Data Raid Group Type:  stripe
Status:
  Conditions:
    Last Transition Time:  2022-12-31T11:40:13Z
    Last Update Time:      2022-12-31T11:40:13Z
    Message:               Pool manager(s) have minimum available pod
    Reason:                MinimumPoolManagersAvailable
    Status:                True
    Type:                  PoolManagerAvailable
  Desired Instances:       4
  Healthy Instances:       4
  Provisioned Instances:   4
Version Details:
  Desired:  develop-dev
  Status:
    Current:              develop-dev
    Dependents Upgraded:  true
    Last Update Time:     <nil>
Events:                   <none>
```

Bit the `cspc` still shows the `4`:

```shell
$ k -n openebs get cspc
NAME              HEALTHYINSTANCES   PROVISIONEDINSTANCES   DESIREDINSTANCES   AGE
cstor-pool-disk   4                  4                      4                  29d
```

Why?

---

I manually restarted the `statefulset.apps/openebs-cstor-csi-controller`, `deployment.apps/cspc-operator ` and `deployment.apps/openebs-cstor-admission-server` but nothing changed!

---

K8s version: `1.25.3`
