### ISSUE TITLE
Block Device stuck in Inactive.

### ISSUE THREAD

**Issue by alifiroozi80** [openebs/openebs#3615]
Hello guys, 

I have a couple of block devices in my cluster that worked perfectly. After a few days, I checked the `bd` in my cluster, and one of them is `Inactive`, and another block device has been added automatically without attaching a block device to the node!!

```shell
$ k -n openebs get bd -o wide
NAME                                           NODENAME   PATH        FSTYPE       SIZE          CLAIMSTATE   STATUS     AGE
blockdevice-0487f0c6fa305ed08b69136b3201deba   worker1    /dev/vdc1                21473771008   Claimed      Active     17d
blockdevice-079f24faba0d9f46e24c21f2b21bd335   worker2    /dev/vdb1   zfs_member   21473771008   Unclaimed    Active     93m ## The newly added block device!!
blockdevice-141ad763fecfd113f6b2e842cb6991c1   worker3    /dev/vdb1                21473771008   Claimed      Active     46d
blockdevice-1d0134218cf292a9fbe56964dab9f908   worker2    /dev/vdb1                21473771008   Claimed      Inactive   46d ## My previous block device
blockdevice-50c83768f58753e03f6af761582c37d0   worker4    /dev/vdb1                21473771008   Claimed      Active     46d
blockdevice-905336dd2f5e26c2cb84c98e02e0774b   worker2    /dev/vdc1                21473771008   Claimed      Active     17d
blockdevice-b37d4d29a87c23f85dd6780c35f829b5   worker4    /dev/vdc1                32211189248   Claimed      Active     7d23h
blockdevice-d49779f8727ac924464822e71042ac8e   worker3    /dev/vdc1                32211189248   Claimed      Active     7d23h
blockdevice-fcc0b069214fb88e73b4c744a586b21e   worker1    /dev/vdb1                21473771008   Claimed      Active     46d
```

Here is the result of the `deescribe` command on them both:

The Privous one (`blockdevice-1d0134218cf292a9fbe56964dab9f908`):

```shell
$ k -n openebs describe bd/blockdevice-1d0134218cf292a9fbe56964dab9f908
Name:         blockdevice-1d0134218cf292a9fbe56964dab9f908
Namespace:    openebs
Labels:       kubernetes.io/hostname=worker2
              ndm.io/blockdevice-type=blockdevice
              ndm.io/managed=true
              nodename=worker2
Annotations:  internal.openebs.io/uuid-scheme: gpt
API Version:  openebs.io/v1alpha1
Kind:         BlockDevice
Metadata:
  Creation Timestamp:  2022-12-17T04:52:20Z
  Finalizers:
    openebs.io/bd-protection
  Generation:  26
  Managed Fields:
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"openebs.io/bd-protection":
      f:spec:
        f:claimRef:
          .:
          f:apiVersion:
          f:kind:
          f:name:
          f:namespace:
          f:resourceVersion:
          f:uid:
      f:status:
        f:claimState:
    Manager:      ndo
    Operation:    Update
    Time:         2023-02-01T11:11:53Z
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:internal.openebs.io/uuid-scheme:
        f:labels:
          .:
          f:kubernetes.io/hostname:
          f:ndm.io/blockdevice-type:
          f:ndm.io/managed:
          f:nodename:
      f:spec:
        .:
        f:capacity:
          .:
          f:logicalSectorSize:
          f:physicalSectorSize:
          f:storage:
        f:details:
          .:
          f:compliance:
          f:deviceType:
          f:driveType:
          f:firmwareRevision:
          f:hardwareSectorSize:
          f:logicalBlockSize:
          f:model:
          f:physicalBlockSize:
          f:serial:
          f:vendor:
        f:devlinks:
        f:filesystem:
        f:nodeAttributes:
          .:
          f:nodeName:
        f:partitioned:
        f:path:
      f:status:
        .:
        f:state:
    Manager:         ndm
    Operation:       Update
    Time:            2023-02-01T12:33:13Z
  Resource Version:  23165400
  UID:               a89c381e-2367-47a8-b74b-9f3231161cc3
Spec:
  Capacity:
    Logical Sector Size:   512
    Physical Sector Size:  512
    Storage:               21473771008
  Claim Ref:
    API Version:       openebs.io/v1alpha1
    Kind:              BlockDeviceClaim
    Name:              bdc-cstor-a89c381e-2367-47a8-b74b-9f3231161cc3
    Namespace:         openebs
    Resource Version:  7118818
    UID:               ef7f0f59-9cd5-4c69-89c2-28e021cea010
  Details:
    Compliance:            
    Device Type:           partition
    Drive Type:            HDD
    Firmware Revision:     
    Hardware Sector Size:  512
    Logical Block Size:    512
    Model:                 
    Physical Block Size:   512
    Serial:                
    Vendor:                
  Devlinks:
    Kind:  by-id
    Links:
      /dev/disk/by-id/virtio-d9226a4c-13ab-4ab2-9-part1
    Kind:  by-path
    Links:
      /dev/disk/by-path/virtio-pci-0000:00:07.0-part1
      /dev/disk/by-path/pci-0000:00:07.0-part1
  Filesystem:
  Node Attributes:
    Node Name:  worker2
  Partitioned:  No
  Path:         /dev/vdb1
Status:
  Claim State:  Claimed
  State:        Inactive
Events:         <none>
```

The Newly added (`blockdevice-079f24faba0d9f46e24c21f2b21bd335`):

```shell
$ k -n openebs describe bd/blockdevice-079f24faba0d9f46e24c21f2b21bd335
Name:         blockdevice-079f24faba0d9f46e24c21f2b21bd335
Namespace:    openebs
Labels:       kubernetes.io/hostname=worker2
              ndm.io/blockdevice-type=blockdevice
              ndm.io/managed=true
              ndm.io/zpool-name=cstor-14a65c1b-aa67-42b8-b688-1a684d5e24bd
              nodename=worker2
              openebs.io/block-device-tag=zfs-localpv
Annotations:  <none>
API Version:  openebs.io/v1alpha1
Kind:         BlockDevice
Metadata:
  Creation Timestamp:  2023-02-01T11:10:55Z
  Generation:          4
  Managed Fields:
    API Version:  openebs.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:kubernetes.io/hostname:
          f:ndm.io/blockdevice-type:
          f:ndm.io/managed:
          f:ndm.io/zpool-name:
          f:nodename:
          f:openebs.io/block-device-tag:
      f:spec:
        .:
        f:capacity:
          .:
          f:logicalSectorSize:
          f:physicalSectorSize:
          f:storage:
        f:details:
          .:
          f:compliance:
          f:deviceType:
          f:driveType:
          f:firmwareRevision:
          f:hardwareSectorSize:
          f:logicalBlockSize:
          f:model:
          f:physicalBlockSize:
          f:serial:
          f:vendor:
        f:devlinks:
        f:filesystem:
          .:
          f:fsType:
        f:nodeAttributes:
          .:
          f:nodeName:
        f:partitioned:
        f:path:
      f:status:
        .:
        f:claimState:
        f:state:
    Manager:         ndm
    Operation:       Update
    Time:            2023-02-01T12:33:13Z
  Resource Version:  23165403
  UID:               78ca0171-6569-4d00-927d-861e99f36337
Spec:
  Capacity:
    Logical Sector Size:   512
    Physical Sector Size:  512
    Storage:               21473771008
  Details:
    Compliance:            
    Device Type:           partition
    Drive Type:            HDD
    Firmware Revision:     
    Hardware Sector Size:  512
    Logical Block Size:    512
    Model:                 
    Physical Block Size:   512
    Serial:                
    Vendor:                
  Devlinks:
    Kind:  by-id
    Links:
      /dev/disk/by-id/virtio-d9226a4c-13ab-4ab2-9-part1
    Kind:  by-path
    Links:
      /dev/disk/by-path/virtio-pci-0000:00:07.0-part1
      /dev/disk/by-path/pci-0000:00:07.0-part1
  Filesystem:
    Fs Type:  zfs_member
  Node Attributes:
    Node Name:  worker2
  Partitioned:  No
  Path:         /dev/vdb1
Status:
  Claim State:  Unclaimed
  State:        Active
Events:         <none>
```

---

Also, I don't know if this is relevant or not, but I'm gonna provide them anyway:

1) I'm using the `cStor` Engine, and I attach all of these block devices for it.

```yaml
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-pool-disk
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "worker1"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-fcc0b069214fb88e73b4c744a586b21e"
           - blockDeviceName: "blockdevice-0487f0c6fa305ed08b69136b3201deba"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker2"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-1d0134218cf292a9fbe56964dab9f908"
           - blockDeviceName: "blockdevice-905336dd2f5e26c2cb84c98e02e0774b"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker3"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-141ad763fecfd113f6b2e842cb6991c1"
           - blockDeviceName: "blockdevice-d49779f8727ac924464822e71042ac8e"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker4"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-50c83768f58753e03f6af761582c37d0"
           - blockDeviceName: "blockdevice-b37d4d29a87c23f85dd6780c35f829b5"
     poolConfig:
       dataRaidGroupType: "stripe"
```

```shell
$ k -n openebs get cspc
NAME              HEALTHYINSTANCES   PROVISIONEDINSTANCES   DESIREDINSTANCES   AGE
cstor-pool-disk   4                  4                      4                  46d
```

---

What should I do to fix this?

Should we replace this newly added device with the previous `Inactive` One?

---

K8s version: `1.25.3`
