### ISSUE TITLE
cannot move pod to another node with cstor 'stripe' mode 

### ISSUE THREAD

**Issue by ptrjeffrey** [openebs/openebs#3631]
## Description

 I installed openebs and cstor. then i created the strage class.
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-csi-disk
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  # cstorPoolCluster should have the name of the CSPC
  cstorPoolCluster: cstor-disk-pool
  # replicaCount should be <= no. of CSPI created in the selected CSPC
  replicaCount: "3"

---  
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-pvc
  namespace: minio-1
spec:
  storageClassName: cstor-csi-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
``` 
i deployed minio using the 'cstor-pvc' pvc,it works.
when i let the pod move from node-1 to node-2.it doesn't work.
it stucked on container creating phase. 
## Expected Behavior

the pod move the selected node with the right data which has been mounted.
## Current Behavior

new pod is creating over time.
## Possible Solution

re-select the old node. it worked.
## Steps to Reproduce

i used the official demo.but move the pod to a different node.
## Your Environment

* `kubectl get nodes`:
```
NAME       STATUS   ROLES                      AGE     VERSION
node1      Ready    controlplane,etcd,worker   24d     v1.24.9
ubuntu-1   Ready    controlplane,etcd,worker   9h      v1.24.9
ubuntu-2   Ready    controlplane,etcd,worker   5h32m   v1.24.9
```
* `kubectl get pods --all-namespaces`:
 ```
NAMESPACE             NAME                                                              READY   STATUS              RESTARTS             AGE
cattle-fleet-system   fleet-agent-8ccf6dbc8-dp5hg                                       1/1     Running             10 (4h10m ago)       23d
cattle-system         cattle-cluster-agent-5c9b89ddfb-74rjk                             1/1     Running             48 (4h10m ago)       24d
cattle-system         cattle-cluster-agent-5c9b89ddfb-jwmzf                             1/1     Running             0                    18h
cattle-system         cattle-node-agent-2xrn9                                           1/1     Running             1 (<invalid> ago)    18h
cattle-system         cattle-node-agent-rqn8l                                           1/1     Running             46 (20h ago)         24d
cattle-system         cattle-node-agent-xdxzf                                           1/1     Running             3 (<invalid> ago)    5h33m
cattle-system         kube-api-auth-5zp67                                               1/1     Running             3 (<invalid> ago)    5h32m
cattle-system         kube-api-auth-hn69c                                               1/1     Running             1 (<invalid> ago)    18h
cattle-system         kube-api-auth-s9wmt                                               1/1     Running             9 (4d13h ago)        24d
ingress-nginx         nginx-ingress-controller-72cfd                                    1/1     Running             3 (<invalid> ago)    5h32m
ingress-nginx         nginx-ingress-controller-d8746                                    1/1     Running             1 (<invalid> ago)    18h
ingress-nginx         nginx-ingress-controller-jkj9k                                    1/1     Running             9 (4d13h ago)        24d
kube-system           calico-kube-controllers-6c64c774df-4sh8n                          1/1     Running             9 (4d13h ago)        24d
kube-system           canal-dnvk6                                                       2/2     Running             18 (4d13h ago)       24d
kube-system           canal-f8c8q                                                       2/2     Running             6 (<invalid> ago)    18h
kube-system           canal-h8gbl                                                       2/2     Running             10 (<invalid> ago)   5h33m
kube-system           coredns-7cff8fbd7c-67vkj                                          1/1     Running             3 (<invalid> ago)    5h32m
kube-system           coredns-7cff8fbd7c-w94b4                                          1/1     Running             9 (4d13h ago)        24d
kube-system           coredns-autoscaler-667b9d9fbd-qrrjj                               1/1     Running             9 (4d13h ago)        24d
kube-system           juicefs-csi-controller-0                                          3/3     Running             20 (18h ago)         6d7h
kube-system           juicefs-csi-controller-1                                          3/3     Running             23 (4h10m ago)       6d7h
kube-system           juicefs-csi-node-6hftc                                            3/3     Running             6 (<invalid> ago)    18h
kube-system           juicefs-csi-node-985qx                                            3/3     Running             10 (<invalid> ago)   5h33m
kube-system           juicefs-csi-node-sdmdm                                            3/3     Running             21 (4d13h ago)       6d9h
kube-system           metrics-server-6c8589f867-r2dgg                                   1/1     Running             9 (4d13h ago)        24d
kube-system           rke-coredns-addon-deploy-job-7c7tz                                0/1     Completed           0                    18h
kube-system           rke-ingress-controller-deploy-job-gk8k2                           0/1     Completed           0                    18h
kube-system           rke-metrics-addon-deploy-job-fz4dg                                0/1     Completed           0                    18h
kube-system           rke-network-plugin-deploy-job-zn8bf                               0/1     Completed           0                    18h
minio-1               minio-77c86d6597-g5mdz                                            0/1     ContainerCreating   0                    4m17s
minio-1               minio-ddd89c69-7d6tb                                              0/1     ContainerCreating   0                    14m
openebs               cspc-operator-666b4c54dc-2dvhc                                    1/1     Running             1 (4d13h ago)        4d14h
openebs               cstor-disk-pool-7z9b-6d657596bc-wqnm2                             3/3     Running             0                    74m
openebs               cstor-disk-pool-8pb7-55d5964797-cxchz                             3/3     Running             0                    <invalid>
openebs               cstor-disk-pool-ljc8-d68f9cbd5-ctf6f                              3/3     Running             3 (<invalid> ago)    <invalid>
openebs               cvc-operator-7569979b85-h4nqk                                     1/1     Running             1 (4d13h ago)        4d14h
openebs               openebs-cstor-admission-server-584c67cd86-z876r                   1/1     Running             1 (4d13h ago)        4d14h
openebs               openebs-cstor-csi-controller-0                                    6/6     Running             11 (4h10m ago)       4d14h
openebs               openebs-cstor-csi-node-89mkd                                      2/2     Running             4 (<invalid> ago)    18h
openebs               openebs-cstor-csi-node-g7525                                      2/2     Running             7 (<invalid> ago)    5h33m
openebs               openebs-cstor-csi-node-z7ttg                                      2/2     Running             2 (4d13h ago)        4d14h
openebs               openebs-localpv-provisioner-79c75d5fc4-ftcfw                      1/1     Running             5 (4h10m ago)        4d18h
openebs               openebs-ndm-cluster-exporter-567b7646c6-29jmb                     1/1     Running             1 (4d13h ago)        4d14h
openebs               openebs-ndm-jj8vp                                                 1/1     Running             2 (<invalid> ago)    18h
openebs               openebs-ndm-jtm2f                                                 1/1     Running             4 (<invalid> ago)    5h33m
openebs               openebs-ndm-k8m2t                                                 1/1     Running             1 (4d13h ago)        4d14h
openebs               openebs-ndm-node-exporter-9d6wj                                   1/1     Running             1 (4d13h ago)        4d14h
openebs               openebs-ndm-node-exporter-djkqx                                   1/1     Running             2 (<invalid> ago)    18h
openebs               openebs-ndm-node-exporter-w6kgw                                   1/1     Running             4 (<invalid> ago)    5h33m
openebs               openebs-ndm-operator-79d8ffbbdc-vplvr                             1/1     Running             1 (4d13h ago)        4d14h
openebs               pvc-13438454-c45e-4646-b4e5-4ddd57bc0612-target-54698b48f8lhcbj   3/3     Running             0                    78m
openebs               pvc-20c86939-bd61-449e-b7bf-1674ccac4344-target-bc5dc6db-9rf4p    3/3     Running             0                    78m
openebs               pvc-3e2e8b3b-d368-4e67-aedc-e96850f55381-target-55bbcff78d7sffn   3/3     Running             0                    122m
```
* `kubectl get services`:
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   24d
```
* `kubectl get sc`:
```
NAME               PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
cstor-csi-disk     cstor.csi.openebs.io   Delete          Immediate              true                   164m
openebs-device     openebs.io/local       Delete          WaitForFirstConsumer   false                  4d18h
openebs-hostpath   openebs.io/local       Delete          WaitForFirstConsumer   false                  4d18h
```
* `kubectl get pv`:
```
NAME                                       CAPACITY    ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                        STORAGECLASS     REASON   AGE
juicefs-pg13-pv-500g                       500Gi       RWO            Retain           Bound    bgy/juicefs-pg13-pvc-500g                              6d2h
juicefs-pv                                 10Pi        RWX            Retain           Bound    bgy/juicefs-pvc                                        6d7h
pvc-13438454-c45e-4646-b4e5-4ddd57bc0612   2Gi         RWO            Delete           Bound    default/cstor-pvc            cstor-csi-disk            164m
pvc-20c86939-bd61-449e-b7bf-1674ccac4344   2Gi         RWO            Delete           Bound    minio-1/cstor-pvc            cstor-csi-disk            164m
pvc-3e2e8b3b-d368-4e67-aedc-e96850f55381   107374183   RWO            Delete           Bound    bgy/api-pvc                  cstor-csi-disk            124m
sandbox-minio-pv-5g                        5Gi         RWO            Retain           Bound    minio/sandbox-minio-pvc-5g                             23d
sandbox-pg13-pv-5g                         5Gi         RWO            Retain           Bound    pg13/sandbox-pg13-pvc-5g                               23d
```
* `kubectl get pvc`:
```
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
cstor-pvc   Bound    pvc-13438454-c45e-4646-b4e5-4ddd57bc0612   2Gi        RWO            cstor-csi-disk   173m
```
* OS (from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (from `uname -a`):
```
Linux node1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
* Install tools: rancher
* Others:

**Comment by ptrjeffrey** [comment]
the deployment yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - command:
          - sh
          - -c
          - 'date >> /mnt/openebs-csi/date.txt; hostname >> /mnt/openebs-csi/hostname.txt; sync; sleep 5; sync; tail -f /dev/null;'
        image: busybox
        imagePullPolicy: Always
        name: busybox
        volumeMounts:
        - mountPath: /mnt/openebs-csi
          name: demo-vol
      volumes:
      - name: demo-vol
        persistentVolumeClaim:
          claimName: cstor-pvc
```
the cstor pool cluster yaml
```
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "ubuntu-2"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-143431bf0a012576697dbe41e7e2bcff"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "ubuntu-1"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-16f4bd3e70e4392b31623bd83bb07d41"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "ubuntu-0"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-1d92fe307fbe106e0e06c89ce2d2a09b"
     poolConfig:
       dataRaidGroupType: "stripe"
```
the cs yaml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-csi-disk
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  # cstorPoolCluster should have the name of the CSPC
  cstorPoolCluster: cstor-disk-pool
  # replicaCount should be <= no. of CSPI created in the selected CSPC
  replicaCount: "3"
```
