### ISSUE TITLE
no matches for kind "StoragePoolClaim" in version "openebs.io/v1alpha1"

### ISSUE THREAD

**Issue by ptrjeffrey** [openebs/openebs#3633]
## Description

```yaml
#Use the following YAMLs to create a cStor Storage Pool.
# and associated storage class.
apiVersion: openebs.io/v1alpha1
kind: storagePoolClaim
metadata:
  name: cstor-disk
spec:
  name: cstor-disk
  type: disk
  poolSpec:
    poolType: striped
    # NOTE - Appropriate disks need to be fetched using `kubectl get blockdevices -n openebs`
  #
  # `Block devices` is a custom resource supported by OpenEBS with `node-disk-manager`
  # as the disk operator
  # Replace the following with actual disk CRs from your cluster `kubectl get blockdevices -n openebs`
  # Uncomment the below lines after updating the actual disk names.
  blockDevices:
    blockDeviceList:
# Replace the following with actual disk CRs from your cluster from `kubectl get blockdevices -n openebs`
    - blockdevice-143431bf0a012576697dbe41e7e2bcff
    - blockdevice-16f4bd3e70e4392b31623bd83bb07d41
    - blockdevice-1d92fe307fbe106e0e06c89ce2d2a09b
 ```
## Expected Behavior

create sctor pool 
## Current Behavior

no matches for kind "StoragePoolClaim" in version "openebs.io/v1alpha1"
## Your Environment

* `kubectl get nodes`:
```
kubectl get nodes
NAME       STATUS   ROLES                      AGE    VERSION
ubuntu-0   Ready    controlplane,etcd,worker   146m   v1.22.17
ubuntu-1   Ready    controlplane,etcd,worker   138m   v1.22.17
ubuntu-2   Ready    controlplane,etcd,worker   139m   v1.22.17
```
* `kubectl get pods --all-namespaces`:
```
NAMESPACE             NAME                                             READY   STATUS      RESTARTS       AGE
cattle-fleet-system   fleet-agent-5b5ddb87d-4kprf                      1/1     Running     1 (133m ago)   144m
cattle-system         cattle-cluster-agent-56bb597848-mns87            1/1     Running     1 (133m ago)   139m
cattle-system         cattle-cluster-agent-56bb597848-t4kvj            1/1     Running     1 (133m ago)   145m
cattle-system         cattle-node-agent-2jh5w                          1/1     Running     1 (133m ago)   145m
cattle-system         cattle-node-agent-4h69q                          1/1     Running     1 (133m ago)   139m
cattle-system         cattle-node-agent-mfbh7                          1/1     Running     1 (133m ago)   139m
cattle-system         kube-api-auth-2t6f9                              1/1     Running     1 (133m ago)   139m
cattle-system         kube-api-auth-m65xm                              1/1     Running     1 (133m ago)   139m
cattle-system         kube-api-auth-pjcf2                              1/1     Running     1 (133m ago)   145m
ingress-nginx         nginx-ingress-controller-dn8jk                   1/1     Running     1 (133m ago)   145m
ingress-nginx         nginx-ingress-controller-gc8f4                   1/1     Running     1 (133m ago)   139m
ingress-nginx         nginx-ingress-controller-pz6m4                   1/1     Running     1 (133m ago)   139m
kube-system           calico-kube-controllers-7c85dbdfc8-5nfcv         1/1     Running     1 (133m ago)   146m
kube-system           canal-77chp                                      2/2     Running     2 (133m ago)   139m
kube-system           canal-jxnm4                                      2/2     Running     2 (133m ago)   139m
kube-system           canal-v9mv7                                      2/2     Running     2 (133m ago)   146m
kube-system           coredns-76c9cc885d-44q89                         1/1     Running     1 (133m ago)   146m
kube-system           coredns-76c9cc885d-xtkxc                         1/1     Running     1 (133m ago)   138m
kube-system           coredns-autoscaler-56f4768f-lt8dg                1/1     Running     1 (133m ago)   146m
kube-system           metrics-server-5d978b4c8c-fxdgc                  1/1     Running     1 (133m ago)   146m
kube-system           rke-coredns-addon-deploy-job-pqmx6               0/1     Completed   0              146m
kube-system           rke-ingress-controller-deploy-job-nzxjx          0/1     Completed   0              145m
kube-system           rke-metrics-addon-deploy-job-54hxk               0/1     Completed   0              146m
kube-system           rke-network-plugin-deploy-job-z29c7              0/1     Completed   0              146m
openebs               cspc-operator-5dd6c4f96f-b8qnz                   1/1     Running     0              64m
openebs               cvc-operator-6679bc5c49-6n5s9                    1/1     Running     0              64m
openebs               openebs-cstor-admission-server-6947fbd4b-kpgpm   1/1     Running     0              64m
openebs               openebs-cstor-csi-controller-0                   6/6     Running     0              64m
openebs               openebs-cstor-csi-node-728hv                     2/2     Running     0              64m
openebs               openebs-cstor-csi-node-rm4rc                     2/2     Running     0              64m
openebs               openebs-cstor-csi-node-vhbs6                     2/2     Running     0              64m
openebs               openebs-localpv-provisioner-697596577c-kwvk9     1/1     Running     0              95m
openebs               openebs-ndm-7lmpp                                1/1     Running     0              63m
openebs               openebs-ndm-cluster-exporter-55c6bb94dd-szmqp    1/1     Running     0              64m
openebs               openebs-ndm-jkgr9                                1/1     Running     0              63m
openebs               openebs-ndm-node-exporter-jcdcj                  1/1     Running     0              63m
openebs               openebs-ndm-node-exporter-kk48f                  1/1     Running     0              63m
openebs               openebs-ndm-node-exporter-n4mnv                  1/1     Running     0              64m
openebs               openebs-ndm-operator-864b769d65-jb5bm            1/1     Running     0              64m
openebs               openebs-ndm-qpd8g                                1/1     Running     0              64m
```
* `kubectl get services`:
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   147m
```
* `kubectl get sc`:
```
NAME               PROVISIONER        RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-device     openebs.io/local   Delete          WaitForFirstConsumer   false                  96m
openebs-hostpath   openebs.io/local   Delete          WaitForFirstConsumer   false                  96m
```
* `kubectl get pv`:
```
No resources found
```
* `kubectl get pvc`:
```
No resources found in openebs namespace.
```
* OS (from `/etc/os-release`): 
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel (from `uname -a`):
```
Linux ubuntu-0 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
* Install tools: rke
* Others:
