### ISSUE TITLE
Duplicate VolumeSnapshotClasses crds between cstor and zfs-localpv charts without mandatory Helm Annotations

### ISSUE THREAD

**Issue by Toasterson** [openebs/openebs#3666]
## Description
Both the cstor chart and the zfs-localpv chart include a crd for VolumeSnapshotClasses and those charts are not templates so that the Helm annotations are present. Resulting in a failed install, not applied CRDS over applied CRDS and all the other fun behavior.

## Expected Behavior
OpenEBS chart can be installed with a values file like this:
```yaml
defaultStorageConfig:
  enabled: "false"

legacy:
  enabled: false

lvm-localpv:
  enabled: true

openebs-ndm:
  enabled: true
  ndm:
    probes:
      enableSeachest: false
      enableUdevProbe: false
      enableSmartProbe: false
    resources:
      requests:
        cpu: "10m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "200Mi"
  ndmOperator:
    resources:
      requests:
        cpu: "10m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "200Mi"

snapshotOperator:
  enabled: false
```

Or Helm installs the crds without issue even if they are duplicated.

## Current Behavior
A Error message is produced akin to https://github.com/helm/helm/issues/7418

## Possible Solution
Deliver all CRDS in a dedicated chart or break out base CRDS needed by multiple charts into different charts.

## Steps to Reproduce
`helm install --namespace openebs --create-namespace openebs openebs/openebs --values values.yaml` (use values from above)

## Your Environment
* OS (from `/etc/os-release`): Ubuntu 22.04 (Kubernetes installed via Kubeadm) Kubernetes Version 1.28.1
* Install tools: helm, helmfile
