### ISSUE TITLE
openebs-hostpath:basepath incorrect

### ISSUE THREAD

**Issue by soulwhisper** [openebs/openebs#3778]
## Description
openebs-hostpath has incorrect bashpath, or  openebs-etcd and openebs-loki set incorrect pvc path, helm install stucks.
- openebs-hostpath, and its doc, define basepath = "/var/openebs/local"
- openebs-etcd pvc starts with "/var/local/openebs/localpv-hostpath/etcd/pvc-"
- openebs-loki pvc starts with "/var/local/openebs/localpv-hostpath/loki/pvc-"

## Expected Behavior
openebs-hostpath works by itself, no need to alter basepath

## Current Behavior
fresh and clean install stuck at Init.

## Possible Solution
fix any path, then fix the doc if needed.

## Steps to Reproduce
```shell
helm repo add openebs https://openebs.github.io/openebs
helm repo update

helm install openebs \
     --create-namespace \
     --namespace openebs \
     --set engines.local.lvm.enabled=false \
     --set engines.local.zfs.enabled=false \
     openebs/openebs

kubectl label ns openebs \
        pod-security.kubernetes.io/audit=privileged \
        pod-security.kubernetes.io/enforce=privileged \
        pod-security.kubernetes.io/warn=privileged

kubectl describe pod openebs-etcd-0 -n openebs
kubectl get sc openebs-hostpath -o yaml

```

**Comment by soulwhisper** [comment]
I checked other issues, it seems keeps happening during mayastor version changes. This issue use latest version.

**Comment by clemric** [comment]
Same issue here (on Talos Linux), thank you for pointing this.
I managed to have a functional Chart, overriding basepaths values:
 - mayastor.etcd.localpvScConfig.basePath: "/var/openebs/local/localpv-hostpath/etcd"
 - mayastor.loki-stack.localpvScConfig.basePath: "/var/openebs/local/localpv-hostpath/loki"

**Comment by Trojanekkk** [comment]
The other way would be to correct `openebs-hostpath`'s `BasePath` parameter to `/var/local/openebs`
```
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/local/openebs"
```

If you are using Talos Linux, then you need to apply the following patch:
```
machine:
  kubelet:
    extraMounts:
      - destination: /var/local/openebs
        type: bind
        source: /var/local/openebs
        options:
          - bind
          - rshared
          - rw
```
to expose given path to the kubelet.

In my case it did the trick.
