### ISSUE TITLE
Helm bug - openebs mayastore cannot disable internal etcd

### ISSUE THREAD

**Issue by mproniakin** [openebs/openebs#3788]
Having problem with using external etcd for mayastore, using the feature to disable internal etcd and providing externalUrl:
```
etcd:
            enabled: false
            externalUrl: openebs-etcd-ext.openebs.svc.cluster.local
            localpvScConfig:
              enabled: false
            persistence:
              enabled: false
            replicaCount: 1
```
The option doesn't seem to work:
```
[root@master-1 ~]# kubectl get pod -n openebs
NAME                                        READY   STATUS    RESTARTS      AGE
nginx                                       1/1     Running   0             25h
openebs-agent-core-f65cf798c-pxbsv          2/2     Running   58 (2d ago)   2d2h
openebs-agent-ha-node-54tq5                 1/1     Running   0             29m
openebs-agent-ha-node-6tlpc                 1/1     Running   0             29m
openebs-agent-ha-node-p5gc7                 1/1     Running   0             29m
openebs-api-rest-6cdc859b-jqvdv             1/1     Running   0             2d2h
openebs-csi-controller-86d9847696-bjd78     6/6     Running   1 (47h ago)   47h
openebs-csi-node-fv54p                      2/2     Running   0             29m
openebs-csi-node-gt6sn                      2/2     Running   0             29m
openebs-csi-node-jwhwk                      2/2     Running   0             29m
openebs-etcd-0                              0/1     Running   0             24s
openebs-etcd-ext-0                          1/1     Running   0             81m
openebs-io-engine-cw5q6                     1/1     Running   0             29m
openebs-io-engine-czhks                     1/1     Running   0             29m
openebs-io-engine-t4pln                     1/1     Running   0             29m
openebs-nats-0                              3/3     Running   0             2d
openebs-nats-1                              3/3     Running   0             24h
openebs-nats-2                              3/3     Running   0             2d
openebs-obs-callhome-f486f4d94-9p4fg        2/2     Running   7 (2d ago)    2d2h
openebs-operator-diskpool-fd9df6fc7-2zxt9   1/1     Running   0             2d2h
```
Helm version: 4.1.1
