### ISSUE TITLE
Unable to create DiskPool 

### ISSUE THREAD

**Issue by kant777** [openebs/openebs#3790]
Here is my `diskpool.yaml`

```
# DiskPool for node: gke-mev-commit-gke-default-pool-faf28efd-3s4q with IP: 10.128.0.16
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: ip-10-128-0-16-diskpool
  namespace: openebs
spec:
  node: gke-mev-commit-gke-default-pool-faf28efd-3s4q
  disks: ["/dev/md0"]
  topology:
    labelled:
      openebs.io/nodename: gke-mev-commit-gke-default-pool-faf28efd-3s4q
```

After running `kubectl apply -f dispool.yaml` and then `kubectl events -A` I see the following error in the logs

```
openebs           17s                     Critical   Failure                           DiskPool/ip-10-128-0-16-diskpool                               Unable to create or import pool error in response: status code '400 Bad Request', content: 'RestJsonError { details: "create_pool::status: InvalidArgument, message: \"Failed to create a BDEV '/dev/md0': EINVAL: Invalid argument\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Mon, 07 Oct 2024 09:54:28 GMT\", \"content-length\": \"0\"} }", message: "SvcError::GrpcRequestError", kind: InvalidArgument }'
```

I ssh'ed into one of my worker node and did `lsblk /dev/md0` and below is the output

```
lsblk /dev/md0 
NAME MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINTS
md0    9:0    0  1.5T  0 raid0 /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /mnt/stateful_partition/kube-ephemeral-ssd/kubelet
                               /var/lib/kubelet
                               /var/log/pods
                               /var/lib/kubelet
                               /var/lib/containerd
                               /mnt/stateful_partition/kube-ephemeral-ssd
```

More info

```
kubectl get dsp -n openebs
NAME                      NODE                                            STATE      POOL_STATUS   CAPACITY   USED   AVAILABLE
ip-10-128-0-16-diskpool  gke-mev-commit-gke-default-pool-faf28efd-3s4q   Creating                 0          0      0
```

**Comment by kant777** [comment]
Also tried the below and got the same error

Error
```
openebs     8s          Critical   Failure   DiskPool/ip-10-128-0-16-diskpool   Unable to create or import pool error in response: status code '400 Bad Request', content: 'RestJsonError { details: "create_pool::status: InvalidArgument, message: \"Failed to create a BDEV '/dev/nvme0n1': EINVAL: Invalid argument\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Tue, 08 Oct 2024 04:03:29 GMT\", \"content-length\": \"0\"} }", message: "SvcError::GrpcRequestError", kind: InvalidArgument }'
```

`Diskpool.yaml`

```
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: ip-10-128-0-16-diskpool
  namespace: openebs
spec:
  node: gke-mev-commit-gke-default-pool-faf28efd-3s4q
  disks:
    - /dev/nvme0n1
  topology:
    labelled:
      openebs.io/nodename: gke-mev-commit-gke-default-pool-faf28efd-3s4q
```

and

```
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: ip-10-128-0-16-diskpool
  namespace: openebs
spec:
  node: gke-mev-commit-gke-default-pool-faf28efd-3s4q
  disks:
    - /dev/disk/by-uuid/a55c88c9-1b8f-4e37-80e7-a8ad75a84fd4
  topology:
    labelled:
      openebs.io/nodename: gke-mev-commit-gke-default-pool-faf28efd-3s4q
```

output by `lsblk`

```
lsblk
NAME MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINTS
sda    8:0    0  100G  0 disk  
├─sda1
│      8:1    0 99.9G  0 part  /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/da4f4841-b425-4269-abaf-d9822d1cf829/volumes/kubernetes.io~local-volume/pvc-5dbccdff-5c40-4c05-af70-1719286d0b10
│                              /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/da4f4841-b425-4269-abaf-d9822d1cf829/volumes/kubernetes.io~local-volume/pvc-5dbccdff-5c40-4c05-af70-1719286d0b10
│                              /mnt/stateful_partition/kube-ephemeral-ssd/kubelet/pods/da4f4841-b425-4269-abaf-d9822d1cf829/volumes/kubernetes.io~local-volume/pvc-5dbccdff-5c40-4c05-af70-1719286d0b10
│                              /mnt/stateful_partition/kube-ephemeral-ssd/kubelet/pods/da4f4841-b425-4269-abaf-d9822d1cf829/volumes/kubernetes.io~local-volume/pvc-5dbccdff-5c40-4c05-af70-1719286d0b10
│                              /var/lib/kubelet/pods/da4f4841-b425-4269-abaf-d9822d1cf829/volumes/kubernetes.io~local-volume/pvc-5dbccdff-5c40-4c05-af70-1719286d0b10
│                              /var/lib/kubelet/pods/da4f4841-b425-4269-abaf-d9822d1cf829/volumes/kubernetes.io~local-volume/pvc-5dbccdff-5c40-4c05-af70-1719286d0b10
│                              /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/6f973778-4c99-45f3-8ffb-63c8a44147b5/volumes/kubernetes.io~local-volume/pvc-be411ce5-1fe8-428f-80d2-d4db7217bbba
│                              /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/6f973778-4c99-45f3-8ffb-63c8a44147b5/volumes/kubernetes.io~local-volume/pvc-be411ce5-1fe8-428f-80d2-d4db7217bbba
│                              /mnt/stateful_partition/kube-ephemeral-ssd/kubelet/pods/6f973778-4c99-45f3-8ffb-63c8a44147b5/volumes/kubernetes.io~local-volume/pvc-be411ce5-1fe8-428f-80d2-d4db7217bbba
│                              /mnt/stateful_partition/kube-ephemeral-ssd/kubelet/pods/6f973778-4c99-45f3-8ffb-63c8a44147b5/volumes/kubernetes.io~local-volume/pvc-be411ce5-1fe8-428f-80d2-d4db7217bbba
│                              /var/lib/kubelet/pods/6f973778-4c99-45f3-8ffb-63c8a44147b5/volumes/kubernetes.io~local-volume/pvc-be411ce5-1fe8-428f-80d2-d4db7217bbba
│                              /var/lib/kubelet/pods/6f973778-4c99-45f3-8ffb-63c8a44147b5/volumes/kubernetes.io~local-volume/pvc-be411ce5-1fe8-428f-80d2-d4db7217bbba
│                              /home/kubernetes/containerized_mounter
│                              /home/containerd
│                              /home/kubernetes/flexvolume
│                              /home/kubernetes/bin
│                              /
├─sda14
│      8:14   0    4M  0 part  
└─sda15
       8:15   0  106M  0 part  /boot/efi
nvme0n1
│    259:0    0  375G  0 disk  
└─md0
       9:0    0  1.5T  0 raid0 /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /mnt/stateful_partition/kube-ephemeral-ssd/kubelet
                               /var/lib/kubelet
                               /var/log/pods
                               /var/lib/kubelet
                               /var/lib/containerd
                               /mnt/stateful_partition/kube-ephemeral-ssd
nvme0n2
│    259:1    0  375G  0 disk  
└─md0
       9:0    0  1.5T  0 raid0 /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /mnt/stateful_partition/kube-ephemeral-ssd/kubelet
                               /var/lib/kubelet
                               /var/log/pods
                               /var/lib/kubelet
                               /var/lib/containerd
                               /mnt/stateful_partition/kube-ephemeral-ssd
nvme0n3
│    259:2    0  375G  0 disk  
└─md0
       9:0    0  1.5T  0 raid0 /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /mnt/stateful_partition/kube-ephemeral-ssd/kubelet
                               /var/lib/kubelet
                               /var/log/pods
                               /var/lib/kubelet
                               /var/lib/containerd
                               /mnt/stateful_partition/kube-ephemeral-ssd
nvme0n4
│    259:3    0  375G  0 disk  
└─md0
       9:0    0  1.5T  0 raid0 /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet
                               /mnt/stateful_partition/kube-ephemeral-ssd/kubelet
                               /var/lib/kubelet
                               /var/log/pods
                               /var/lib/kubelet
                               /var/lib/containerd
                               /mnt/stateful_partition/kube-ephemeral-ssd
```
