### ISSUE TITLE
following the docs for local pv lvm produces an error

### ISSUE THREAD

**Issue by condaatje** [openebs/openebs#3809]
related: https://github.com/openebs/lvm-localpv/issues/349

**Comment by condaatje** [comment]
```
sudo snap install microk8s --classic --channel=1.31

truncate -s 5G /tmp/disk.img
sudo losetup -f /tmp/disk.img --show

# use the name of the disk from that last command and put it here:
sudo pvcreate /dev/loop<?>
sudo vgcreate lvmvg /dev/loop<?>       ## here lvmvg is the volume group name to be created

microk8s helm install openebs --namespace openebs openebs/openebs --set engines.replicated.mayastor.enabled=false --set engines.local.zfs.enabled=false --create-namespace
```


```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
provisioner: local.csi.openebs.io
parameters:
  storage: "lvm"
  volgroup: "lvmvg"
volumeBindingMode: WaitForFirstConsumer     ## note: when this is replaced with "Immediate" it creates a pv successfully, but the pod still can't use it for some reason
```

**Comment by condaatje** [comment]
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lvm-local-pvc
spec:
  storageClassName: openebs-lvmpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
    limits:
      storage: 1G
```

**Comment by condaatje** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: lvm-task-pv-pod-2
spec:
  volumes:
    - name: lvm-task-pv-storage
      persistentVolumeClaim:
        claimName: lvm-local-pvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/hypermount"
          name: lvm-task-pv-storage
```


ERROR:

`Warning  FailedScheduling  99s   default-scheduler  0/1 nodes are available: 1 node(s) did not have enough free storage. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.`
