### ISSUE TITLE
Is really local PV hostpath data possible to backup with velero?

### ISSUE THREAD

**Issue by pew-x2** [openebs/openebs#3821]
## Description
I installed openEBS with local PV hostpath and trying to backup the volume with velero without any luck. I interpret the documentation as that it should be possible:
 "Data protection using the Velero Backup and Restore." https://openebs.io/docs/user-guides/local-storage-user-guide/local-pv-hostpath/hostpath-installation.

But when I run a backup of a persistent volume, the volume yaml are backed up but no data. Is this the expected behaviour? 

Using one node Kubernetes cluster run on docker desktop on Mac OSX.

## Your Environment
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    backup.velero.io/backup-volumes: local-storage
spec:
  volumes:
    - name: test-pv
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    volumeMounts:
      - mountPath: "/tmp"
        name: test-pv
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
---

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: db-backup
spec:
  storageClassName: openebs-hostpath
  # storageClassName: my-class
  # persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/parwrange/Documents/dev/projects/deployment/ansible/tryout/openebs/tmp"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  annotations:
    backup.velero.io/backup-volumes: local-storage
spec:
  storageClassName: openebs-hostpath
  # storageClassName: my-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      type: db-backup

```

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:
