### ISSUE TITLE
CRDs should not be annotated by pre-upgrade hook if management is disabled in chart

### ISSUE THREAD

**Issue by solidDoWant** [openebs/openebs#3893]
## Description

The Helm chart pre-upgrade hook always annotates the volume snapshot controller CRDs even if management/ownership is disabled in the chart.

## Expected Behavior

The hook should not modify the CRDs, and should also not need permission to get or patch them.

## Current Behavior

The hook annotations the volume snapshot CRDs.

## Possible Solution

Only run the [annotate command](https://github.com/openebs/openebs/blob/develop/charts/templates/pre-upgrade-hook.yaml#L91) if management of the CRDs is enabled. Also only conditionally give the service account CRD annotation permissions if management is enabled.

## Steps to Reproduce

1. Configure the chart to not manage these CRDs via `openebs-crds.csi.volumeSnapshots.enabled: false`
2. Deploy the chart
3. Observe the behavior of the pre-upgrade hook.

## Your Environment

N/A - see https://github.com/openebs/openebs/blob/develop/charts/templates/pre-upgrade-hook.yaml#L91

**Comment by Mrbm5** [comment]
I've noticed a similar issue as described, the `pre-upgrade-hook` job always runs during the chart installation, even when it seems unnecessary. Is there a specific reason this job is designed to run every time?  Would it be possible to make its execution optional via values.yaml?

For instance, while using the [Local PV Hostpath](https://github.com/openebs/dynamic-localpv-provisioner), According to the documentation, snapshots are not supported for Local PV Hostpath, and I’ve set the relevant CRD and snapshot-related configurations to false in `values.yaml`. However, the `pre-upgrade-hook` still runs, attempts to annotate CRDs that are not even present, and subsequently deletes the `OpenEBS deployment`. There doesn't seem to be a configurable way to opt out of this behavior.

Here’s is the `values.yaml`, where all snapshot and CRD options are explicitly disabled:
```yaml

openebs-crds:
  csi:
    volumeSnapshots:
      enabled: false
      keep: false

localpv-provisioner:
  rbac:
    create: true
  localpv:
    enabled: true
    basePath: "/var/openebs/local"
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 32Mi
        cpu: 10m
  helperPod:
  analytics:
    enabled: false
  hostpathClass:
    name: openebs-hostpath
    enabled: true
    reclaimPolicy: Retain
    isDefaultClass: true 
    xfsQuota:
      enabled: true

zfs-localpv:
  crds:
    zfsLocalPv:
      enabled: false
    csi:
      volumeSnapshots:
        enabled: false

lvm-localpv:
  crds:
    lvmLocalPv:
      enabled: false
    csi:
      volumeSnapshots:
        enabled: false

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false

```

Would appreciate any insights into why the pre-upgrade-hook is required to run in this case, Is this expected due to some historical reason, or can it be considered for improvement so it can be toggled via values?

Appreciate any insights on this!

Thanks.
