### ISSUE TITLE
Io-engine crashes while importing pool

### ISSUE THREAD

**Issue by deepakbnsl** [openebs/openebs#3917]
## Description
In our openebs mayastor cluster (3 powerful servers), io-engine is repeatedly crashing at import pool step. Since pools are not imported, cluster is unusable. 
Slack thread: https://kubernetes.slack.com/archives/CUAKPFU78/p1745613452188289

## Steps to Reproduce
State of the cluster when this issue occurred: there were approximately 10 pods with PVCs (15TB each), along with around 50 total snapshots of these PVCs, and we had requested the deletion of all the snapshots. Only some of these were deleted successfully, and the system got stuck at 31 snapshots. Note that our disk pools are created over striped LVM logical volumes.

[mayastor-2025-04-30--14-09-40-UTC.zip](https://github.com/user-attachments/files/20016328/mayastor-2025-04-30--14-09-40-UTC.zip)

storage class example:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-0
provisioner: io.openebs.csi-mayastor
parameters:
  fsType: ext4
  poolAffinityTopologyLabel: 'hostname: server-0'
  repl: '1'
  thin: 'true'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

![Image](https://github.com/user-attachments/assets/c73ebb25-619b-43e8-b4f4-de6fd9af6d2e)

## Your Environment

* `kubectl get sc`:
```
NAME                          PROVISIONER               RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)          rancher.io/local-path     Delete          WaitForFirstConsumer   false                  7d4h
mayastor-etcd-localpv         openebs.io/local          Delete          WaitForFirstConsumer   false                  7d2h
mayastor-loki-localpv         openebs.io/local          Delete          WaitForFirstConsumer   false                  7d2h
mayastor-thin                 io.openebs.csi-mayastor   Delete          Immediate              true                   7d2h
openebs-hostpath              openebs.io/local          Delete          WaitForFirstConsumer   false                  7d2h
openebs-single-replica        io.openebs.csi-mayastor   Delete          Immediate              true                   7d2h
sc-rpc-platform-prod-use1-0   io.openebs.csi-mayastor   Delete          Immediate              true                   7d1h
sc-rpc-platform-prod-use1-1   io.openebs.csi-mayastor   Delete          Immediate              true                   7d1h
sc-rpc-platform-prod-use1-2   io.openebs.csi-mayastor   Delete          Immediate              true                   7d1h
```
* OS (from `/etc/os-release`): Ubuntu 24.04.2 LTS
* Kernel (from `uname -a`): 6.8.0-58-generic
* Install tools: k3s, helm
