### ISSUE TITLE
Unexpected changes in Helm chart regarding Loki and Alloy

### ISSUE THREAD

**Issue by sebastiangaiser** [openebs/openebs#3981]
Hey, thank you for providing nice storage options for on prem clusters.

I would like to make this clear, so this issue only exists for sharing feedback.
We wanted to upgrade the Helm chart to version `4.3.0` but we figured out that this release contains additional resources regarding Alloy, Loki and with the Loki umbrella chart also Minio.
We ended up disabling them by setting:

```
loki:
  enabled: false
alloy:
  enabled: false
```

For us this change was very unfortunate as the changelog is not mentioning this: https://github.com/openebs/openebs/releases/tag/v4.3.0
We only found the [corresponding PR](https://github.com/openebs/openebs/pull/3911/files) in the RC changelog list: https://github.com/openebs/openebs/releases/tag/v4.3.0-rc.0

May I kindly ask why this is enabled by default? Thanks in advance!

**Comment by Abhinandan-Purkait** [comment]
@sebastiangaiser This is an important addon, this is to collect support bundles for openebs as a whole. Earlier this feature was limited to mayastor only and now we have extended it over to OpenEBS. With this we can capture the system state for debugging and users can just hand over a tar ball that collects all the historical logs and related resources. The reason it's enabled by default is because we expect users to have this stack running so that we can collect historical information that would help us debug better. 

Now the newer Loki stack needs an object storage to run in an HA mode that's the reason we have enabled minio out of the box, if someone doesn't want that then can check the loki storage document which mentions ways to not use an object storage. Promtail is now replaced by alloy as promtail is supposed to be EOL.

**Comment by Abhinandan-Purkait** [comment]
But, thanks for pointing out the fact that isn't not documented well enough in the release notes. We will update the release notes with this information.

**Comment by sebastiangaiser** [comment]
Thanks for the explanation. Feel free to leave the issue open or close it.

**Comment by frzifus** [comment]
Enabling this by default and expecting these alloy CRDs to be installed caused my Helm upgrade to fail. I personally don't think it's good practice to make such a change. I would highlight this on the release notes, considering it as a breaking change or additional requirement for an upgrade. 😅 

**Helm**
```
$ k get helmreleases.helm.toolkit.fluxcd.io -n openebs
NAME       AGE    READY   STATUS
mayastor   113d   False   Helm upgrade failed for release openebs/openebs-mayastor with chart 
openebs@4.3.2: failed to apply CustomResourceDefinitions: 
failed to update CustomResourceDefinition(s): failed to replace object:
CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com" is invalid:
status.storedVersions[0]: Invalid value: "v1alpha2": missing from spec.versions; v1alpha2 was
previously a storage version, and must remain in spec.versions until a storage migration ensures no
data remains persisted in v1alpha2 and removes v1alpha2 from status.storedVersions && failed to
replace object: CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com"
is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": missing from spec.versions; v1alpha2
was previously a storage version, and must remain in spec.versions until a storage migration
ensures no data remains persisted in v1alpha2 and removes v1alpha2 from status.storedVersions
```

I tried to disable it loki and alloy, but it seems still to require the CRDs? At least my helm release upgrade still fails.

--

cc @michaelbeaumont

**Comment by Abhinandan-Purkait** [comment]
@frzifus How are you upgrading using the kubectl-openebs plugin or direct helm upgrade?

You are indeed correct that these should have been highlighted in the release notes. We have updated it.

**Comment by frzifus** [comment]
I did a direct helm upgrade using [flux ci](https://fluxcd.io/). 

- https://github.com/frzifus/hmlb/pull/140

Seems all this CRDs got installed on my cluster.
```
grafanaagents.monitoring.grafana.com                       2025-06-22T12:29:16Z
integrations.monitoring.grafana.com                        2025-06-22T12:29:16Z
logsinstances.monitoring.grafana.com                       2025-06-22T12:29:16Z
metricsinstances.monitoring.grafana.com                    2025-06-22T12:29:16Z
podlogs.monitoring.grafana.com                             2025-06-22T12:29:16Z
```

mh.. technically it should be disabled. Maybe its using some old artefacts on my end.  
https://github.com/openebs/mayastor-extensions/blob/2844d49bbad4482d466b73eca3ed5443fc90cdee/chart/Chart.yaml#L43-L46

**Comment by Abhinandan-Purkait** [comment]
@frzifus What is your source version? Also was loki-stack disabled on your installation, assuming you have installed mayastor from openebs umbrella chart and loki-stack was only a part of mayastor chart dependency of openebs.

**Comment by frzifus** [comment]
@Abhinandan-Purkait with source version you mean for the helm release (`a892ce9076258a0815f4c5ca4972606977cd492f5a687517a631701ea76bf9b2`)?

Thats my entire configuration for the helm repo, tagging version `4.3.2` and the config that disables `loki` and `alloy` that I updated 1 minute ago.
https://github.com/frzifus/hmlb/blob/347363a12881fd96bf622e40906c3d61086e5ec4/clusters/homelab/core/storage/openebs.yaml#L63-L66

Manual flux reconcile:
```
flux reconcile helmrelease  -n openebs mayastor --with-source
► annotating HelmRepository openebs in openebs namespace
✔ HelmRepository annotated
◎ waiting for HelmRepository reconciliation
✔ fetched revision sha256:a892ce9076258a0815f4c5ca4972606977cd492f5a687517a631701ea76bf9b2
► annotating HelmRelease mayastor in openebs namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✗ HelmRelease reconciliation failed: Helm upgrade failed for release openebs/openebs-mayastor with chart openebs@4.3.2: failed to apply CustomResourceDefinitions: failed to update CustomResourceDefinition(s): failed to replace object: CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": missing from spec.versions; v1alpha2 was previously a storage version, and must remain in spec.versions until a storage migration ensures no data remains persisted in v1alpha2 and removes v1alpha2 from status.storedVersions && failed to replace object: CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": missing from spec.versions; v1alpha2 was previously a storage version, and must remain in spec.versions until a storage migration ensures no data remains persisted in v1alpha2 and removes v1alpha2 from status.storedVersions
```

**Comment by Abhinandan-Purkait** [comment]
@frzifus I see, you are disabling the mayastor's loki dependency and not the openebs's dependency, since loki and alloy is part of the openebs umbrella chart as well now you need to do it there from there. The mayastor one is disabled by default when installed from openebs chart.

https://github.com/openebs/openebs/blob/9f927c465ce4fcdc958c3a630f1cd8145bcb6013/charts/values.yaml#L43

**Comment by Abhinandan-Purkait** [comment]
Also, I am still not sure where is the CRD `podlogs.monitoring.grafana.com` coming from, it's not installed by any versions of openebs chart.

**Comment by Abhinandan-Purkait** [comment]
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 1h
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mayastor
  namespace: openebs
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 1h
  targetNamespace: openebs
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: 4.3.2
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
    mayastor:
      csi:
        node:
          # currently necessary because the init container checks for nvmeof module but Talos compiles it in
          initContainers:
            enabled: false
      etcd:
        replicaCount: 3
      eventing:
        enabled: false
      io_engine:
        # It's the automatic mode, in the DPDK code IOVA_MODE_DC, that causes issues.
        # Confirmed by EAL debug log output that this really selects VA
        envcontext: "iova-mode=va"
      loki:
        enabled: false
      alloy:
        enabled: false
      obs:
        callhome:
          enabled: false
      storageClass:
        # we can't override reclaimPolicy so just make the classes explicit in base-config
        enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
```
Can you try with this?

**Comment by frzifus** [comment]
oh, `mayastor.<alloy||loki>.enabled` is disabled by default when set to false on the global level, no?

I tried to flip it on the higher level to `false`, still facing the same helm install issue. 🙈 
https://github.com/frzifus/hmlb/commit/386855e801e9851a07a1755394946198c320b2f3

**Comment by frzifus** [comment]
I disabled both now at both levels:
- https://github.com/frzifus/hmlb/commit/a2d6f5065acabb793cfc2e06047179e71e07b6d8
- https://github.com/frzifus/hmlb/commit/386855e801e9851a07a1755394946198c320b2f3

Just to make sure, its not failing because the CRDs are hanging around I deleted all of the grafana CRDs:
```
$ k delete crd podlogs.monitoring.grafana.com metricsinstances.monitoring.grafana.com logsinstances.monitoring.grafana.com integrations.monitoring.grafana.com grafanaagents.monitoring.grafana.com
```

Its then still expecting that the CRD is installed.
```
✗ HelmRelease reconciliation failed: Helm upgrade failed for release openebs/openebs-mayastor with chart openebs@4.3.2: failed to apply CustomResourceDefinitions: failed to update CustomResourceDefinition(s): no CustomResourceDefinition with the name "podlogs.monitoring.grafana.com" found
```

Calling reconcile twice, will again show the error message I faced earlier with the installed CRD.
```
k get crds | grep grafana              
grafanaagents.monitoring.grafana.com                       2025-06-24T14:57:11Z
integrations.monitoring.grafana.com                        2025-06-24T14:57:11Z
logsinstances.monitoring.grafana.com                       2025-06-24T14:57:11Z
metricsinstances.monitoring.grafana.com                    2025-06-24T14:57:11Z
podlogs.monitoring.grafana.com                             2025-06-24T14:57:10Z

✗ HelmRelease reconciliation failed: Helm upgrade failed for release openebs/openebs-mayastor with chart openebs@4.3.2: failed to apply CustomResourceDefinitions: failed to update CustomResourceDefinition(s): failed to replace object: CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": missing from spec.versions; v1alpha2 was previously a storage version, and must remain in spec.versions until a storage migration ensures no data remains persisted in v1alpha2 and removes v1alpha2 from status.storedVersions && failed to replace object: CustomResourceDefinition.apiextensions.k8s.io "podlogs.monitoring.grafana.com" is invalid: status.storedVersions[0]: Invalid value: "v1alpha2": missing from spec.versions; v1alpha2 was previously a storage version, and must remain in spec.versions until a storage migration ensures no data remains persisted in v1alpha2 and removes v1alpha2 from status.storedVersions
```

**Comment by Abhinandan-Purkait** [comment]
`➜  /tmp helm install openebs-openebs openebs/openebs -n openebs --create-namespace --version 4.2.0 --set mayastor.loki-stack.enabled=false`


`➜  /tmp helm upgrade openebs-openebs openebs/openebs -n openebs --create-namespace --version 4.3.2 --set loki.enabled=false --set alloy.enabled=false`

```➜  /tmp helm ls -n openebs                                                                                                                           
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
openebs-openebs openebs         2               2025-06-24 14:56:01.097100421 +0000 UTC deployed        openebs-4.3.2   4.3.2
```

That's weird, I don't seem to be hitting it, although am not sure if flux is doing something here.


```
➜  /tmp kubectl get crds           
NAME                                             CREATED AT
diskpools.openebs.io                             2025-06-24T14:56:34Z
lvmnodes.local.openebs.io                        2025-06-24T14:54:54Z
lvmsnapshots.local.openebs.io                    2025-06-24T14:54:54Z
lvmvolumes.local.openebs.io                      2025-06-24T14:54:54Z
volumesnapshotclasses.snapshot.storage.k8s.io    2025-06-24T14:54:54Z
volumesnapshotcontents.snapshot.storage.k8s.io   2025-06-24T14:54:54Z
volumesnapshots.snapshot.storage.k8s.io          2025-06-24T14:54:54Z
zfsbackups.zfs.openebs.io                        2025-06-24T14:54:54Z
zfsnodes.zfs.openebs.io                          2025-06-24T14:54:54Z
zfsrestores.zfs.openebs.io                       2025-06-24T14:54:54Z
zfssnapshots.zfs.openebs.io                      2025-06-24T14:54:54Z
zfsvolumes.zfs.openebs.io                        2025-06-24T14:54:54Z
➜  /tmp kubectl get crds | grep podlogs.monitoring.grafana.com  
```

Also, there is no `podlogs.monitoring.grafana.com` crds anywhere. :-/

**Comment by Abhinandan-Purkait** [comment]
Can you try the same using the openebs 4.3.2 kubectl plugin?

`kubectl-openebs upgrade -n openebs --set loki.enabled=false --set alloy.enabled=false`

**Comment by frzifus** [comment]
Is there a newer version available then [v0.6.0](https://github.com/openebs/openebsctl/releases/tag/v0.6.0)?

```
$kubectl-openebs version
COMPONENT                  VERSION
Client                     v0.6.0
OpenEBS LVM LocalPV        Not Installed
OpenEBS ZFS LocalPV        Not Installed
OpenEBS HostPath LocalPV   Not Installed

You are using an older version of cli, latest available version is: v4.3.0
```

**Comment by frzifus** [comment]
```
$ helm list           
NAME            	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART        	APP VERSION
openebs-mayastor	openebs  	5       	2025-06-25 10:57:08.778947005 +0200 CEST	deployed	openebs-4.3.2	4.3.2 
```

Alright, it seems to be some issue with flux itself. Using the helm CLI, I was able to upgrade OpenEBS with the following values `helm upgrade openebs-mayastor openebs/openebs -n openebs  --version 4.3.2 -f values.yaml`:
```yaml
loki:
  enabled: false
alloy:
  enabled: false
engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: true
mayastor:
  loki-stack:
    enabled: false
  csi:
    node:
      # currently necessary because the init container checks for nvmeof module but Talos compiles it in
      initContainers:
        enabled: false
  etcd:
    replicaCount: 3
  eventing:
    enabled: false
  io_engine:
    # It's the automatic mode, in the DPDK code IOVA_MODE_DC, that causes issues.
    # Confirmed by EAL debug log output that this really selects VA
    envcontext: "iova-mode=va"
  obs:
    callhome:
      enabled: false
  storageClass:
    # we can't override reclaimPolicy so just make the classes explicit in base-config
    enabled: false
```
Then I tried to apply the same using flux. Which tries again to install the grafana CRDs.

---

Thanks for your help @Abhinandan-Purkait !!
