### ISSUE TITLE
Document the usage w.r.t policy enforcement

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#863]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required ?

This issue will provide necessary content with regards to the usage of policy enforcement

## Relevant Issues

- #409

**Comment by AmitKumarDas** [comment]
### Add a volume with single replica -- old way

```bash
$ cat 1-rep-old.yaml 
```
```yaml
kind: Volume
apiVersion: v1
metadata:
  name: one-rep-old
  labels:
    volumeprovisioner.mapi.openebs.io/replica-count: 1
```
```
# add command using curl
curl -k -H "Content-Type: application/yaml" \
  -XPOST -d"$(cat 1-rep-old.yaml)" \
  http://10.0.0.85:5656/latest/volumes/

# delete command using curl
curl http://10.0.0.85:5656/latest/volumes/delete/one-rep-old
```

### Add a volume with single replica -- new way

```bash
$ cat 1-rep-new.yaml 
```
```yaml
kind: Volume
apiVersion: v1
metadata:
  name: one-rep-new
specs:
  - context: replica
    replicas: 1
```
```
# add command using curl
curl -k -H "Content-Type: application/yaml" \
  -XPOST -d"$(cat 1-rep-new.yaml)" \
  http://10.0.0.85:5656/latest/volumes/

# delete command using curl
curl http://10.0.0.85:5656/latest/volumes/delete/one-rep-new
```

### Add a volume with capacity -- old way

```bash
$ cat cap-old.yaml  
```
```yaml
kind: Volume
apiVersion: v1
metadata:
  name: cap-old
  labels:
    volumeprovisioner.mapi.openebs.io/storage-size: 1G
```
```
# add command using curl
curl -k -H "Content-Type: application/yaml" \
  -XPOST -d"$(cat cap-old.yaml)" \
  http://10.0.0.85:5656/latest/volumes/

# delete command using curl
curl http://10.0.0.85:5656/latest/volumes/delete/cap-old
```

### Add a volume with capacity -- new way

```bash
$ cat cap-new.yaml  
```
```yaml
kind: Volume
apiVersion: v1
metadata:
  name: cap-new
capacity: 1G
```
```
# add command using curl
curl -k -H "Content-Type: application/yaml" \
  -XPOST -d"$(cat cap-new.yaml)" \
  http://10.0.0.85:5656/latest/volumes/

# delete command using curl
curl http://10.0.0.85:5656/latest/volumes/delete/cap-new
```

### Add a volume with minimal properties

```bash
$ cat default-vol.yaml  
```
```yaml
kind: Volume
apiVersion: v1
metadata:
  name: def-vol
```
```
# add command using curl
curl -k -H "Content-Type: application/yaml" \
  -XPOST -d"$(cat default-vol.yaml)" \
  http://10.0.0.85:5656/latest/volumes/

# delete command using curl
curl http://10.0.0.85:5656/latest/volumes/delete/def-vol
```

### Add a volume with K8s storage class label disabled

```bash
$ cat storage-class-disabled.yaml  
```
```yaml
kind: Volume
apiVersion: v1
metadata:
  name: sc-disabled
  labels:
    k8s.io/storage-class-enabled: false
```
```
# add command using curl
curl -k -H "Content-Type: application/yaml" \
  -XPOST -d"$(cat storage-class-disabled.yaml)" \
  http://10.0.0.85:5656/latest/volumes/

# delete command using curl
curl http://10.0.0.85:5656/latest/volumes/delete/sc-disabled
```

### Add a volume with K8s storage class label enabled

```bash
$ cat storage-class-enabled.yaml  
```
```yaml
kind: Volume
apiVersion: v1
metadata:
  name: sc-disabled
  labels:
    k8s.io/storage-class-enabled: true
    k8s.io/storage-class: mysql
```
```
# add command using curl
curl -k -H "Content-Type: application/yaml" \
  -XPOST -d"$(cat storage-class-enabled.yaml)" \
  http://10.0.0.85:5656/latest/volumes/

# delete command using curl
curl http://10.0.0.85:5656/latest/volumes/delete/sc-enabled
```

#### Assumptions

- A K8s StorageClass named mysql should exist
- It can expose one or more of these properties:
  - openebs.io/capacity
  - openebs.io/jiva-replica-image
  - openebs.io/jiva-controller-image
  - openebs.io/jiva-replica-count
  - openebs.io/jiva-controller-count
