### ISSUE TITLE
Set all the default images to :latest tag in maya and expose these images as ENV variables

### ISSUE THREAD

**Issue by AmitKumarDas** [openebs/openebs#948]
## Is this a BUG REPORT or FEATURE REQUEST?
 
FEATURE REQUEST

## Why is this required

The various images used during volume provisioning should default to appropriate image name & have :latest as its tag. In addition, these images should be exposed as ENV variables in maya api service

**Comment by AmitKumarDas** [comment]
- monitoring policy's ENV variable for image
- this can be set in maya api server's deployment specs

```yaml
        env:
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "openebs/m-exporter:cim"
```
